### ISSUE TITLE
multiGet: if one key fails, the entire request fails

### ISSUE THREAD

**Issue by mobitar** [react-native-community/async-storage#106]
In https://github.com/react-native-community/react-native-async-storage/blob/9f1727c2529994865ed1f73d416cab56d4ddcdfb/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java#L124 the [try/catch](https://github.com/react-native-community/react-native-async-storage/blob/9f1727c2529994865ed1f73d416cab56d4ddcdfb/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java#L152) is placed outside of the looping of each key, so if one request fails, the entire operation halts and an error returns.

If instead we wrap the per-cursor execution in try/catch:

``` java
try {
  WritableArray row = Arguments.createArray();
  row.pushString(cursor.getString(0));
  row.pushString(cursor.getString(1));
  data.pushArray(row);
  keysRemaining.remove(cursor.getString(0));
} catch (Exception e) {
  continue;
}
```

then we get a chance to keep going if one operation fails.

You could even have an `errors` array to push to on fail, and return the errors array in addition to the data array.

I've found this behavior to be useful, as I'm currently fetching 100 keys, but one of them returns "Couldn't read row 0, col 0 from CursorWindow" (due to the item being very large in size, > 1MB) However, the rest succeed, but I'm unable to get their values with `multiGet`. So instead I'm having to use loop through keys and use `getItem` one at a time.

@react-native-community/async-storage 1.4.0

**Comment by Krizzu** [comment]
Sorry for getting back so late @mobitar.

In other cases, this would look like an expected behavior - to not continue if one of operation fails - so it's easier to know how to restore to the previous state.

I'd say to leave it like it is not for legacy, but we could include a flag that determinate this behavior at the call site for v2.

thanks.
