### ISSUE TITLE
async-storage-mock.js cannot be compiled by Jest

### ISSUE THREAD

**Issue by thomasarogers** [react-native-community/async-storage#116]
Jest hits 'Unexpected token identifier' when mocking react-native-community/react-native-async-storage following the docs on Github:
https://github.com/react-native-community/react-native-async-storage/blob/master/docs/Jest-integration.md

<img width="979" alt="image" src="https://user-images.githubusercontent.com/42372294/58707224-2b904700-83ac-11e9-8e7c-172a30c1e292.png">

I have tried using the following babel.config.js with no luck

<img width="659" alt="image" src="https://user-images.githubusercontent.com/42372294/58708078-a78b8e80-83ae-11e9-9748-7fefa7f8359b.png">

The following package.json dev dependencies:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/42372294/58708334-6647ae80-83af-11e9-8e50-4db0266f2e8a.png">

## Expected behavior

Jest should compile source and run tests successfully

## Repro steps

Write Jest test with react-native-community/react-native-async-storage as a dependency then follow doc above to Mock react-native-community/react-native-async-storage with Jest

## Environment

"@react-native-community/async-storage": "1.4"
info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
      Memory: 17.23 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.0 - ~/.nvm/v8.15.0/bin/node
      npm: 6.4.1 - ~/.nvm/v8.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 16, 19, 21, 22, 23
        Build Tools: 21.1.2, 22.0.0, 23.0.2, 25.0.2, 27.0.3
        System Images: android-21 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.1 => 0.59.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by Krizzu** [comment]
Hey @thomasarogers,

Have you checked [troubleshooting section of Jest integration doc?](https://github.com/react-native-community/react-native-async-storage/blob/master/docs/Jest-integration.md#troubleshooting)

**Comment by tgearig** [comment]
I'm running into the same error, even with modifying transformIgnorePatterns as documented in the link @Krizzu provided.

**Comment by Krizzu** [comment]
@tgearig Can you provide more info about your config? What error do you get exactly? What's your Jest config?

**Comment by tgearig** [comment]
@Krizzu I ran into these errors after upgrading to react-native 0.59.8.  I got it fixed by deleting my package-lock.json, node_modules directory, and doing an npm install again. That cleared up the errors.

**Comment by hkung77** [comment]
Hi, i'm also struggling with this problem. and the integration document link seems to have disappeared.

**Comment by Krizzu** [comment]
@hkung77 	
[It's here](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md)

**Comment by phyzical** [comment]
not adding anything to anyones problem, but i got this working within 2 minutes following the above link (thanks @Krizzu )

running  "react-native": "^0.59.9"

**Comment by genuinezack** [comment]
Thanks for pointing to that @Krizzu! Running `"react-native": "^0.59.9"` it fixed my issue right away to follow the tip in the Troubleshooting section. Indeed, well enough that I'd suggest moving it to the main instructions body for the next version's instructions.

There is, however, a small bug with the suggestion where the more aggressive "add all of the community packages" code snippet will _also_ add any package whose name starts with `react-native` (which, afaict, is like 50% of react-native package 😅). Opened [a small PR](https://github.com/react-native-community/async-storage/pull/146) to fix that issue for you.

**Comment by Krizzu** [comment]
Thanks @genuinezack!

Seems like the issue no longer exists, so closing this one.
