### ISSUE TITLE
Could not resolve project :@react-native-community_async-storage

### ISSUE THREAD

**Issue by ankha0109** [react-native-community/async-storage#122]
## You want to:  
Hello,
I'm using RN 0.59.9 and async-storage 1.4.2 but not working on android. Build failed with following error.

> FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :@react-native-community_async-storage.
     Required by:
         project :app
      > Unable to find a matching configuration of project :@react-native-community_async-storage:
          - None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Screenshot:**
![image](https://user-images.githubusercontent.com/8737838/59464454-119a3e00-8e5b-11e9-927f-4e06003a43aa.png)

**.build.gradle**
![image](https://user-images.githubusercontent.com/8737838/59464497-2bd41c00-8e5b-11e9-9526-5660438b2743.png)

**Comment by tido64** [comment]
How did you link AsyncStorage? Did you follow this [this guide](https://github.com/react-native-community/async-storage/blob/master/docs/Linking.md#android)?

**Comment by ankha0109** [comment]
> How did you link AsyncStorage? Did you follow this [this guide](https://github.com/react-native-community/async-storage/blob/master/docs/Linking.md#android)?

Yes. I have double-check for link steps.

I found solution and now it's working. Before i using yarn install packager.
`npm install @react-native-community/async-storage --save`

**Comment by SdSalaat** [comment]
This issue still presists and i have double checked all the linking steps they are all fine. Please can anyone help with this issue

MY Package.json [Dependencies]

"dependencies": {
    "@react-native-community/async-storage": "^1.5.0",
    "native-base": "^2.12.1",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-modal-datetime-picker": "^7.5.0",
    "react-native-push-notification": "^3.1.3",
    "react-navigation": "^3.11.0"
  },
  "devDependencies": {
    "@babel/core": "7.4.5",
    "@babel/runtime": "7.4.5",
    "babel-jest": "24.8.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-test-renderer": "16.8.3"
  },


![Screenshot from 2019-07-01 14-37-05](https://user-images.githubusercontent.com/30148680/60426946-2161a280-9c0f-11e9-97fd-fbe3df6730fa.png)

**Comment by Krizzu** [comment]
Hey @SdSalaat 	

Your issue is related to Gradle. `Name or service not know` is related to your network/DNS resolution. Make sure your network is fine, clean build and try again.

**Comment by SdSalaat** [comment]
hi @Krizzu if you please can you define some steps

**Comment by systemis** [comment]
This is a new issue of comunity / asyncstorage that has not been resolved. You can use the default way of react natieve modules

You try delete comunity/asyncstorage and use AsyncStorage from React Native

**Comment by Krizzu** [comment]
@systemis 	This is not AsyncStorage issue. 

@SdSalaat 	I don't know exactly your setup, so can't really help here. Do you use a proxy?

**Comment by SdSalaat** [comment]
@Krizzu yes  i do but it is turned off

**Comment by ankha0109** [comment]
> @Krizzu yes i do but it is turned off

Are you check following URLs ? Maybe you can download it directly.
![Screen Shot 2562-07-04 at 18 13 55](https://user-images.githubusercontent.com/8737838/60659285-98a16b80-9e87-11e9-806b-7a57c667d5ab.png)

**Comment by Krizzu** [comment]
@SdSalaat What `repositories` have you got in project `build.gradle`?

**Comment by forgetallthing** [comment]
@ankha0109 I can't download this：https://repo.maven.apache.org/maven2/com/android/tools/lint/lint-gradle/26.4.1/lint-gradle-26.4.1.pom
It returns to 404
Error I got when I executed. / gradlew assemble Release，How to repair it？
`* What went wrong:
Could not determine the dependencies of task ':@react-native-community_async-storage:extractReleaseAnnotations'.
> Could not resolve all task dependencies for configuration ':@react-native-community_async-storage:lintClassPath'.
   > Could not resolve com.android.tools.lint:lint-gradle:26.4.1.
     Required by:
         project :@react-native-community_async-storage
      > Could not resolve com.android.tools.lint:lint-gradle:26.4.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/26.4.1/lint-gradle-26.4.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle/26.4.1/lint-gradle-26.4.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.lint:lint-gradle:26.4.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/lint/lint-gradle/26.4.1/lint-gradle-26.4.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/lint/lint-gradle/26.4.1/lint-gradle-26.4.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.lint:lint-gradle:26.4.1.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/android/tools/lint/lint-gradle/26.4.1/lint-gradle-26.4.1.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/android/tools/lint/lint-gradle/26.4.1/lint-gradle-26.4.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings`

**Comment by eXist-FraGGer** [comment]
The same problem

```red
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':@react-native-community_async-storage:extractReleaseAnnotations'.
> Could not resolve all task dependencies for configuration ':@react-native-community_async-storage:lintClassPath'.
   > Could not resolve org.bouncycastle:bcpkix-jdk15on:1.56.
     Required by:
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools:sdk-common:26.4.1
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools.build:builder:3.4.1
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools.build:builder:3.4.1 > com.android.tools.build:apkzlib:3.4.1
      > Could not resolve org.bouncycastle:bcpkix-jdk15on:1.56.
         > Could not get resource 'https://jitpack.io/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.pom'.
            > Could not HEAD 'https://jitpack.io/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.pom'. Received status code 522 from server: Origin Connection Time-out
   > Could not resolve org.bouncycastle:bcprov-jdk15on:1.56.
     Required by:
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools:sdk-common:26.4.1
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools.build:builder:3.4.1
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools.build:builder:3.4.1 > com.android.tools.build:apkzlib:3.4.1
      > Could not resolve org.bouncycastle:bcprov-jdk15on:1.56.
         > Could not get resource 'https://jitpack.io/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.pom'.
            > Could not HEAD 'https://jitpack.io/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.pom'. Received status code 522 from server: Origin Connection Time-out
```

`gradle-wrapper.properties`
```gradle
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```

`android/build.gradle`
```gradle
dependencies {
        classpath("com.android.tools.build:gradle:3.4.1")
....
```

```"@react-native-community/async-storage": "1.6.2"```

```red
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.43 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 16, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-clean-project: 3.2.4
    react-native-cli: 2.0.1
```

**Comment by forgetallthing** [comment]
III opened a proxy, repeatedly installed certificates, can not package successfully, and finally re-installed the Windows system, and finally packaged successfully.

**Comment by eXist-FraGGer** [comment]
Replace `maven { url "https://jitpack.io" }` to `maven { url "https://www.jitpack.io" }`.
I guess it will help someone

**Comment by shaponpal6** [comment]
1st Step: **cd android && gradlew clean && cd ../**
2nd step: **react-native link**
3rd Step:  **react-native run-android**

**Comment by sandeshamin60** [comment]
In settings.gradle file find this

include ':@react-native-async-storage_async-storage' project(':@react-native-async-storage_async-storage').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-async-storage/async-storage/android')

copy the ':@react-native-async-storage_async-storage' in the include line and paste the same to implementation project line in build.gradle

Like this ->

dependencies {

......

implementation project(':@react-native-async-storage_async-storage') //<- paste this

..... }

**Comment by pravchuk** [comment]
I replaced this community dependency with react-native-async-storage and it worked!

Replaced,

`"@react-native-community/async-storage": "^1.12.0",`

With,

`"@react-native-async-storage/async-storage": "^1.14.1",`

**Comment by cristinaITdeveloper** [comment]
I have this problem. I have the aws-amplify@4.3.19 version.

**Comment by chingakhamronald** [comment]
### same problem
`
> Task :react-native-async-storage_async-storage:generateDebugRFile FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 3 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
130 actionable tasks: 119 executed, 11 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-async-storage_async-storage:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-async-storage_async-storage:debugCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /home/chingakham/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-native/0.71.0-rc.0/7a7f5a0af6ebd8eb94f7e5f7495e9d9684b4f543/react-native-0.71.0-rc.0-debug.aar.
         > Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
`

**Comment by chingakhamronald** [comment]
### Same issue in here
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-async-storage_async-storage:generateDebugRFile'.
> Could not resolve all files for configuration ':react-native-async-storage_async-storage:debugCompileClasspath'.
   > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /home/chingakham/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-native/0.71.0-rc.0/7a7f5a0af6ebd8eb94f7e5f7495e9d9684b4f543/react-native-0.71.0-rc.0-debug.aar.
         > Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by tido64** [comment]
> ### Same issue in here
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':react-native-async-storage_async-storage:generateDebugRFile'.
> 
> > Could not resolve all files for configuration ':react-native-async-storage_async-storage:debugCompileClasspath'.
> > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
> > > Execution failed for JetifyTransform: /home/chingakham/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-native/0.71.0-rc.0/7a7f5a0af6ebd8eb94f7e5f7495e9d9684b4f543/react-native-0.71.0-rc.0-debug.aar.
> > > Java heap space
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

If you look closely at the build error, you'll see that you are getting react-native 0.71.0-rc.0, which is causing the build issue. This is a known issue caused by its release on Friday. You can find fixes/workarounds in this thread: https://github.com/facebook/react-native/issues/35210

**Comment by chingakhamronald** [comment]
> > ### Same issue in here
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> >   Execution failed for task ':react-native-async-storage_async-storage:generateDebugRFile'.
> > 
> > > Could not resolve all files for configuration ':react-native-async-storage_async-storage:debugCompileClasspath'.
> > > Failed to transform react-native-0.71.0-rc.0-debug.aar (com.facebook.react:react-native:0.71.0-rc.0) to match attributes {artifactType=android-symbol-with-package-name, com.android.build.api.attributes.BuildTypeAttr=debug, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-api}.
> > > > Execution failed for JetifyTransform: /home/chingakham/.gradle/caches/modules-2/files-2.1/com.facebook.react/react-native/0.71.0-rc.0/7a7f5a0af6ebd8eb94f7e5f7495e9d9684b4f543/react-native-0.71.0-rc.0-debug.aar.
> > > > Java heap space
> > 
> > 
> > 
> > * Try:
> > 
> > > Run with --stacktrace option to get the stack trace.
> > > Run with --info or --debug option to get more log output.
> > > Run with --scan to get full insights.
> > 
> > 
> > 
> > * Get more help at https://help.gradle.org
> 
> If you look closely at the build error, you'll see that you are getting react-native 0.71.0-rc.0, which is causing the build issue. This is a known issue caused by its release on Friday. You can find fixes/workarounds in this thread: [facebook/react-native#35210](https://github.com/facebook/react-native/issues/35210)

tq

**Comment by Luyin** [comment]
In my case.

Issue has been fixed after update react-native@0.70.3. to 0.70.5

**Comment by impaaras** [comment]
![image](https://user-images.githubusercontent.com/67624437/226103756-48f4297b-df95-4594-817d-f0ae59790851.png)
I am facing this error. Please help me to solve

**Comment by impaaras** [comment]
![image](https://user-images.githubusercontent.com/67624437/226103975-83bc42c1-c674-4d34-afeb-a7de4be5c65a.png)

**Comment by Pankaj0109** [comment]
* What went wrong:
A problem occurred configuring project ':react-native-community_async-storage'.
> Failed to notify project evaluation listener.
   > org/gradle/api/plugins/MavenPlugin



I am facing this issue
