### ISSUE TITLE
[iOS] Use app groups path to save storage.

### ISSUE THREAD

**Issue by djorkaeffalexandre** [react-native-community/async-storage#126]
## Motivation
When you try to create an iOS Extension (Eg: Share Extension, Watch Extension), if you store info on AsyncStorage you do not have access to this. If you have a method to set suite name to storage path you can use folder of app group and use that.

## Description

Create a function like
```javascript
AsyncStorage.setSuite('group.example')
```
and after that AsyncStorage use the App Group's path on iOS.

## New feature implementation

Can you use code like that to select path to save storage:
```objective-c
NSURL * pathUrl = [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier: @"group.example"];
```

**Comment by Krizzu** [comment]
Hi @djorkaeffalexandre ,

Would [setting a delegate on Async Storage](https://github.com/react-native-community/async-storage/blob/master/docs/advanced/BrownfieldIntegration.md) be helpful in your case? With this, you have access from Native Side to stored data via AS.

**Comment by enahum** [comment]
This would be extremely useful to have, right now the way I go about this is to create a file that I write using the appGroupId so it I can access it from the native side in the Share Extension, so basically I'm duplicating the data.

By having a way to initialize the AsyncStorage with an `appGroup` I will no longer need to dup the data.

Perhaps something to consider for v2?

**Comment by Krizzu** [comment]
@enahum 	Yup, definitely. Going to put it on the todo. For now, I'm going to close this one.


thanks.

**Comment by yannikw23** [comment]
Hi @Krizzu ! Any news on when this might be available? Would love to use this feature!

**Comment by aanah0** [comment]
Actual for me too

**Comment by Krizzu** [comment]
I'd like to know a real use case here - As far I as know, RN is not targeting watch extensions yet.

**Comment by enahum** [comment]
@Krizzu access to data in notification extensions, share extensions, etc...

**Comment by thiagobrez** [comment]
This would be very useful for acessing data in share extensions indeed

**Comment by frankenthumbs** [comment]
+1 on this. 

the problem i forsee is that setting an appgroup dynamically might have unintended sideeffects. i'd imagine that we would want to set appgroup after hydration of the manifest.json file for data migration on existing apps but we would want to set it before hydration after saving data to the new appgroup.

**Comment by Krizzu** [comment]
My question would be if we need to do this dynamically or would setting it once do the trick? 
If it's the former, we could have a flag set in `Info.plist` and use it to change storage to app group path.

**Comment by gaodeng** [comment]
@Krizzu  Can you merge this code in?  https://github.com/RZulfikri/async-storage/tree/add/app-group  
Here is a related discussion https://github.com/alinz/react-native-share-extension/issues/166

**Comment by matanrokach** [comment]
Hey, any news about this one? This would be extremely helpful!!

**Comment by arual5** [comment]
Hi @krizzu ! :) Any news on when this might be available?
I really need to use this feature since I have been using AS library for a long time and I need to be able to access data in notification extension, widget extension, etc...

I'm sure it would be very useful and helpful to many people!

**Comment by phazei** [comment]
This would be a really useful feature, right now due to this limitation we need to implement our own custom file store on iOS, would really like to use this library instead.
