### ISSUE TITLE
Allow control over AsyncStorage location on iOS

### ISSUE THREAD

**Issue by cpojer** [react-native-community/async-storage#13]
* * *
  This issue was originally created by @sam1463 as facebook/react-native#19692.
  * * *

  
  - [x] Review the documentation: https://facebook.github.io/react-native
  - [x] Search for existing issues: https://github.com/facebook/react-native/issues
  - [x] Use the latest React Native version: https://github.com/facebook/react-native/releases
  - [x] Run `react-native info` in your terminal and paste its contents under "Environment"
  - [x] Let us know how to reproduce the issue. Include a code sample, share a project, or
    share an app that reproduces the issue using https://snack.expo.io/

## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 9.4.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.2 => 0.52.2

## Description

Currently, AsyncStorage stores data in the Documents directory on iOS. However, as discussed in [this issue](https://github.com/facebook/react-native/issues/2477), [this abandoned PR](https://github.com/facebook/react-native/pull/4561), and [this abandoned PR](https://github.com/facebook/react-native/pull/10697), there should be an option to store elsewhere, as this location is not appropriate for non-user-created content, as it is visible for apps that enable file sharing with iTunes or the Files app on iOS.

## Steps to Reproduce
This is the case on AsyncStorage on all versions of react-native to my knowledge.

## Expected Behavior
Some sort of control over the location in which AsyncStorage stores data, so that it will not be exported to iTunes, viewable via the Files app, etc. on iOS

## Actual Behavior
AsyncStorage saves to the Documents directory.

**Comment by Krizzu** [comment]
This will be included in v2 of Async Storage. Please refer to #113 for more details
