### ISSUE TITLE
Legacy storage

### ISSUE THREAD

**Issue by Krizzu** [react-native-community/async-storage#133]
This task involves reusing existing `AsyncStorage` implementation with the new API. [New API available here](https://github.com/react-native-community/async-storage/issues/113).

### To do:

- [X] Initial implementation of Legacy storage (thanks to @jeremyscatigna)

- [x] Setup an example to use said storage

- [ ] Storage creation options (while instantiating):
   - Support for different app groups paths on iOS ([reference here](https://github.com/react-native-community/async-storage/issues/126))
   - Support for different location for async storage ([reference here](https://github.com/react-native-community/async-storage/issues/13))

- [ ] Add flags as storage options:
   - Flag to tell if multi* operation should fail whole operation or just one and continue with the rest ([reference here](https://github.com/react-native-community/async-storage/issues/106))

### References:
- https://github.com/react-native-community/async-storage/issues/105
- https://github.com/react-native-community/async-storage/issues/84

This issue will be updated with any upcoming ideas/suggestions.

## Blocked
#131

**Comment by BrodaNoel** [comment]
@Krizzu question: If there are not going to be breaking changes, so, why are you considering changing the version number to `2.x.x`?

**Comment by Krizzu** [comment]
@BrodaNoel 	There are breaking changes regarding API you use ([RFC available here](https://github.com/react-native-community/async-storage/issues/113), but no breaking changes in terms of stored data.

So you'll have to update your codebase to use new API (if you decide to move on to v2), but your users won't lose data stored.

**Comment by poltak** [comment]
Are the "Storage creation options" tasks still planned for v2? 
I just saw this issue was closed and those tasks not checked off, so I wasn't entirely sure of the intention. Cheers :)
