### ISSUE TITLE
Setup an example

### ISSUE THREAD

**Issue by Krizzu** [react-native-community/async-storage#134]
We plan to make Async Storage available for more than just React Native, so let's create examples for other platforms too.

1. Create `examples/` dir in the root, hosting all other examples
2. Each example app should have all available Storages used for it
3. Examples:
	**React Native** (`examples/mobile`)
	**React** (`examples/web`)
	**Windows** (`examples/windows`)

## Blocked

#133
#131

**Comment by hmheng** [comment]
is new Asyncstorage supporting web, windows and other platforms?

**Comment by Krizzu** [comment]
@hmheng Yes, this is described in the [proposal](https://github.com/react-native-community/async-storage/issues/113)
