### ISSUE TITLE
AsyncStorage warning never disappears after updating to this version

### ISSUE THREAD

**Issue by msqar** [react-native-community/async-storage#138]
So i was using the old AsyncStorage, and all of a sudden a warning started to show up to replace it for this new one. After I did it, the warning keeps showing up, i have absolutely no usage of `react-native-async-storage` in my code. Maybe 3rd party library code is still using this? 

I tested everything I found and still couldn't remove it, I don't want to hide the warning by using the yellowBox thing, I do want to make it disappear by stop using it.

How can I solve this? Thanks.

**Comment by Krizzu** [comment]
If you don't use Community's `AsyncStorage`, then it's probably one of your dependency (or dependency of dependency) to use one from RN Core.

**Comment by Krizzu** [comment]
Closing down.

**Comment by msqar** [comment]
Sorry I missed this answer @Krizzu. Yea it's probably that. Any idea on how to search for this dependency? Attempted doing a file search on node_modules, and i don't get any result when searching for 'async-storage'. Thanks.

**Comment by Krizzu** [comment]
@msqar 	have you tried [`yarn list`](https://yarnpkg.com/lang/en/docs/cli/list/) ?

**Comment by msqar** [comment]
Oh, i don't use yarn, i use npm. You mean to list all the latest dependencies or the ones i'm falling behind? I got quite a few. I have to check 1 by 1 through all the code?

**Comment by Krizzu** [comment]
Well, you can search through your `node_modules` using grep:
`grep -rnw 'node_modules' -e 'AsyncStorage'` or some similar pattern for AsyncStorage (like `AsyncStorage. getItem`)

**Comment by msqar** [comment]
Thanks! it worked doing grep. I will check the libs i got using it like sentry and reactotron.
