### ISSUE TITLE
RN 0.60.0: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null

### ISSUE THREAD

**Issue by Riant** [react-native-community/async-storage#149]
## Current behavior
Build Successful, but always got error like below even after I run `react-native link @react-native-community/async-storage`. 

For RN 0.60.0, we do not need to run the link command for native modules, so i get error after I run `react-native link ...`: 
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - @react-native-community/async-storage (to unlink run: "react-native unlink @react-native-community/async-storage")
```

## Expected behavior
For RN 0.60.0, we do not need to run the link command for native modules. 

## Repro steps
Init a project with react-native 0.60.0 ...

## Environment

- **Async Storage version**: 1.5.0
- **React-Native version**: 0.60.0
- **Platform tested**: Android
- **Logs/Error that are relevant**: 
[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null. To fix this issue try these steps: - Run 'react-native link @react-native-community/async-storage' in the project root. - Rebuild and restart the app. ...

So what should I do to fix that for 0.60.

Thanks.

**Comment by Riant** [comment]
Ah, it looks like because the react-native-cli autolinking error: `:ReactNative:Automatic import of native modules failed`. #470

**Comment by thymikee** [comment]
The error tells you to _unlink_ automatically linked modules, so they don't collide and cause issues in future when upgrading. Can we make it more readable for you?

**Comment by dhei** [comment]
I run into the same error `AsyncStorage is null` error when migrating our test app to RN 0.60.0 today.

I resolved the issue by running `react-native unlink @react-native-community/async-storage` and `cd ios && pod install` again.

**Comment by Krizzu** [comment]
Hope that unlink fixed it for ya, @Riant . Going to add instructions in the docs for RN 0.60+
