### ISSUE TITLE
[Android] com.android.tools.build:gradle 3.4.1 gives error

### ISSUE THREAD

**Issue by rendomnet** [react-native-community/async-storage#151]
## Current behavior
For react-native-firebase we need to up the com.android.tools.build:gradle to version 3.4.1
But this gives this error:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/rendom/Documents/dh/dailyheroapp/node_modules/@react-native-community/async-storage/android/build.gradle' line: 33

* What went wrong:
A problem occurred evaluating project ':@react-native-community_async-storage'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /Users/rendom/Documents/dh/dailyheroapp/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip

## Expected behavior

Succesfull build

## Repro steps

Use 3.4.1
android/build.gradle

```
dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
```

## Environment

- **Async Storage version**:1.5.0
- **React-Native version**: 0.59.9
- **Platform tested**: Android

**Comment by Krizzu** [comment]
Hi @rendomnet ,

This comes from the fact that AS is using `3.2.1` version of build tools. I plan of upgrading, but I have to check if it's going to cause some breakages. 


For now, you can either manually set build tools version to `3.4.1` or use tools like [`patch-package`](https://github.com/ds300/patch-package#readme) to do it for you.


thanks.

**Comment by TomBerriot** [comment]
@rendomnet 
> For react-native-firebase we need to up the com.android.tools.build:gradle to version 3.4.1

Though firebase shows to upgrade to 3.4.1 as an exemple, https://rnfirebase.io/docs/v5.x.x/releases/v5.5.x , they only tell that it is necessary for gradle build tools to be above 3.3.2, not 3.4.1.
We had problems for compiling our project in release because of `com.android.tools.build:gradle: 3.4.1` and `distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip`

**Comment by rendomnet** [comment]
any updates on this?

**Comment by Krizzu** [comment]
@rendomnet 	I'm going to look into upgrading next week. For now, I'll refer to [my comment above](https://github.com/react-native-community/async-storage/issues/151#issuecomment-509024029)

**Comment by OriginLive** [comment]
> @rendomnet I'm going to look into upgrading next week. For now, I'll refer to [my comment above](https://github.com/react-native-community/async-storage/issues/151#issuecomment-509024029)

Hello, waiting for this to update, so that i can upgrade to 60.
Thanks for your kind effort!
