### ISSUE TITLE
TVOS Support

### ISSUE THREAD

**Issue by MwareSolutons** [react-native-community/async-storage#152]
## You want to:  
There does not seem to be TVOS support for asyncstorage

## Details:

  pod 'RNCAsyncStorage', :path => '../../node_modules/@react-native-community/async-storage'

and this gives error:

[!] The platform of the target `RNVAppTVOS` (tvOS 12.0) is not compatible with `RNCAsyncStorage (1.5.0)`, which does not support `tvos`.

**Comment by Krizzu** [comment]
Seems like there is some support for TV_OS, but [original authors left a note that it might not work as expected](https://github.com/react-native-community/async-storage/blob/LEGACY/ios/RNCAsyncStorage.m#L332)

cc @tido64

**Comment by MwareSolutons** [comment]
just edit the podspec file from s.platform      =:ios, "9.0" to s.platform      =:tvos, "9.0" then it works

**Comment by tido64** [comment]
Sounds like we can change this to:
```podspec
s.ios.deployment_target = '9.0'
s.tvos.deployment_target = '9.0'
```
@MwareSolutons Are you working with tvOS? It would be awesome if you could test this and submit a PR if everything works as expected.

**Comment by MwareSolutons** [comment]
Hi Tido64 that worked perfectly just tested it thanks !

**Comment by Krizzu** [comment]
@tido64 Do you think that we could add this target to `podspec`?

**Comment by tido64** [comment]
Sorry, I've been out (and still am). Does #167 solve your issue?

**Comment by Krizzu** [comment]
#167 is merged, so hopefully, it fixed this.


thanks.
