### ISSUE TITLE
upgrade database version  then  change  value 

### ISSUE THREAD

**Issue by zhouzhiqiangzzq** [react-native-community/async-storage#156]
## Motivation

my app write with react-native, and use AsyncStorage save token(for user validate)  at app lower version like 1.0 ，I want clear the token when upgrade the app version at 1.1。

**Comment by Krizzu** [comment]
Hey @zhouzhiqiangzzq,

You can read `package.json`'s version of your app, compare it with what is stored, and then wipe data you want. See docs for [remove](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/API.md#removeItem) or [multiRemove](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/API.md#multiremove).


thanks
