### ISSUE TITLE
Can't retrieve 10 mo array from AsyncStorage

### ISSUE THREAD

**Issue by AideProjet** [react-native-community/async-storage#157]
Hi, 

We're saving in AsyncStorage a 35k lines file containing all cities list, retrieve works fine on iOS but it returns null on android, we tried augmenting the limit in MainApplication.java with

long size = 100L * 1024L * 1024L; // 50 MB 
    com.facebook.react.modules.storage.ReactDatabaseSupplier.getInstance(getApplicationContext()).setMaximumSize(size);

But we keep getting the same error.

## Current behavior

await AsyncStorage.getItem("cities").then(console.log);
// return null on android but correct value on iOS

## Expected behavior

await AsyncStorage.getItem("cities").then(console.log);
// return cities list on both iOS and Android

## Repro steps

This is a 10 mo array fetched from our API containing all French cities.

## Environment

- **Async Storage version**: ^1.4.2
- **React-Native version**: 0.59.8
- **Platform tested**:  iOS and Android

**Comment by Krizzu** [comment]
Hi @AideProjet ,

This could be a limitation of CursorWindow to be able to read max 2MB row at a time. So if you try to `setItem` whole storage, it can fail to write/read. Check for native modules.


You can try to split that database into smaller chunks and use `multiSet` for storing it for different keys.
