### ISSUE TITLE
Mi 9 SE & Honor v9,  GuardedAsyncTask waits a minute before executing

### ISSUE THREAD

**Issue by gaodeng** [react-native-community/async-storage#159]
## Current behavior
on Mi 9 SE & Honor v9,  the  multiGet GuardedAsyncTask wait a minute before it's executed

## Expected behavior

GuardedAsyncTask should be executed in very short time

## Environment

- **Async Storage version**: 1.5.0
- **React-Native version**: 0.59.10
- **Platform tested**: Android

**Comment by Krizzu** [comment]
Hi @gaodeng ,

I currently don't have access to said devices, so I cannot check it out. Any chances you could debug and see what's going on?

**Comment by gaodeng** [comment]
@Krizzu  sure ,I will send a PR
