### ISSUE TITLE
Avoid using deprecated methods of gradle that is incompatible with Gradle 6.0

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/async-storage#162]
## Current behavior
A warning has been shown when I build a release version of my RN project using

`cd android && gradlew assembleRelease --warning-mode all`

```
> Task :@react-native-community_async-storage:generateReleaseRFile UP-TO-DATE
Changing the value for a property with a final value has been deprecated. This will fail with an error in Gradle 6.0.
```

It seems the build procedure uses a deprecated way to changing some value.

## Expected behavior
Building a release version without warning.

## Repro steps

Create an RN project and add react-native-community/async-storage as its dependency
and run

`cd android && gradlew assembleRelease --warning-mode all`

## Environment

- **Async Storage version**: 1.5.0
- **React-Native version**: 0.59.10
- **Platform tested**:  Android 
- **Logs/Error that are relevant**: 
> Task :@react-native-community_async-storage:generateReleaseRFile UP-TO-DATE
Changing the value for a property with a final value has been deprecated. This will fail with an error in Gradle 6.0.

**Comment by Krizzu** [comment]
Hey @SaeedZhiany, 

Thanks for bringing this one up. I'm going to keep it in mind in future development, but for now, I can suggest ignoring the warning (Gradle 6 is not out yet).


thanks.

**Comment by SaeedZhiany** [comment]
> (Gradle 6 is not out yet).

@Krizzu 
Yeah, I know, but I raised this issue to avoid using the deprecated APIs in future development and replace the currently deprecated APIs :)))

**Comment by Krizzu** [comment]
@SaeedZhiany Thanks for that :)

Going to this issue.
