### ISSUE TITLE
NativeModule: AsyncStorage is null

### ISSUE THREAD

**Issue by varun761** [react-native-community/async-storage#172]
Hello 
I am getting following issue on react-native app built with expo
This is my package.json file 
"expo": "^33.0.0",
"react": "16.8.3",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",

**Comment by cesarm16** [comment]
same issue here
RN: 0.60.4

**Comment by Krizzu** [comment]
Sorry, this package cannot be used with Expo - you'll have to eject app first, before adding a custom native modules.

**Comment by Simek** [comment]
@Krizzu It's not only an Expo issue as @cesarm16 mentioned - problem also occurs with pure React Native.

Package auto linking was successful for me but I was receiving this error after app launched (firs call to AsyncStorage). A quick solution to that problem was manual linking.

```
System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 1703.83 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
```

**Comment by Krizzu** [comment]
@Simek 	Is it a fresh project or you upgraded from <=0.59? Which platform is affected?

**Comment by Simek** [comment]
Project was upgraded from latest 0.59 release and I can only tell that iOS was affected - don't know about state of Android (project is iOS only). 

Before upgrade I wasn't using `@react-native-community/async-storage` directly in my project but I have added this package as dependency after bumping `@react-native-community/react-native-permissions` to latest [release](https://github.com/react-native-community/react-native-permissions/releases/tag/1.2.0).

This bump have caused first errors which leads me to adding `@react-native-community/async-storage` to app dependencies and later manual linking.

**Comment by Krizzu** [comment]
@Simek 	You can use [upgrade helper](https://react-native-community.github.io/upgrade-helper/) to check necessary changes.

Mind you should now have any Native Module dependencies in your Podfile, as its get linked automatically in 0.60+

**Comment by Simek** [comment]
I have read about changes in 0.60 (also auto linking) and I have used helper in upgrade process. `@react-native-community/async-storage` was the only one package that failed to work "out-of-the-box" and I was forced to link it manually.

**Comment by cesarm16** [comment]
Mine was RNNavigation. https://github.com/wix/react-native-navigation/issues/5228#issuecomment-516017618

**Comment by Krizzu** [comment]
@Simek 	How did you link `AsyncStorage` manually? Can you post your `Podfile` ?

**Comment by Simek** [comment]
I had to link `AsyncStorage` [this](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Linking.md#project-linking) way (without pods, adding `libRNCAsyncStorage.a` file).

**Comment by Krizzu** [comment]
@Simek 	Gotcha. Autolinking works for me out of the box with RN 0.60, so that's fine. What version of `AsyncStorage` do you use? Can I see your `Podfile`?

**Comment by bhaskar8088** [comment]
I am getting this error when using with react-native-web. Any solution for using with react native web?

**Comment by Krizzu** [comment]
@bhaskar8088 	That's could be probably the same case, but to be sure, you should try in RN Web issue.

**Comment by ccorcos** [comment]
I'm having this same issue. Just upgraded to 60 and everything works fine until I install this package. I think the autolinking doesn't work, but I have no idea what I'm supposed to check. There's no git diff other than the package.json dependency.

**Comment by Krizzu** [comment]
@ccorcos 	If you upgraded to 60, double-check platform files (iOS and Android) in RN-Diff - there are loc that are no longer used and break auto-linking

**Comment by ccorcos** [comment]
@Krizzu thanks. It turns out that once you use the autolinking with Podfile, you need to migrate _everything_ to use that approach. Took me a while but I figured it out.

**Comment by joan-saum** [comment]
This error happened while using asyncStorage with react-native-web. Any chance to get a solution for it ?
