### ISSUE TITLE
Getting a NaN, when reusing a variable used for the response of AsyncStorage.

### ISSUE THREAD

**Issue by NishidaRyu416** [react-native-community/async-storage#173]
## Current behaviour
```
let res = await AsyncStorage.getItem('something'); // There is no datum that is saved using the exact key, 'something' in this example but trying to get it.
res =  res ? parseInt(res, 10) : 1;
console.log(res) // I get a NaN here.
await AsyncStorage.setItem('something', `${res + 1}`);
```
## Expected behaviour
```
let res = await AsyncStorage.getItem('something');
res =  res ? parseInt(res, 10) : 1;
console.log(res) // **Of course I should get 1 here.**
await AsyncStorage.setItem('something', `${res + 1}`);
```
## Repro steps

See the current behaviour section.

## Comment—the clue to fix the bug
I guess this bug is due to a memory-related issue because when I use two variables, the one for the response of this module, and the other for calculation, I do not encounter the bug.
Hope this helps!

## Environment

- **Async Storage version**: 1.6.1: the latest version.
- **React-Native version**: 0.59.7
- **Platform tested**: iOS
- **Logs/Error that are relevant**: No logs/Errors

**Comment by Krizzu** [comment]
Hey @NishidaRyu416 ,

If you put any value but a number in `parseInt`, you'll get `NaN` every time. Can you make sure that `res` is indeed falsy?

**Comment by Krizzu** [comment]
@NishidaRyu416 	I'm closing this one. If you still have an issue, please reopen, so we can investigate further
