### ISSUE TITLE
fetch returning blob in RN 0.60.4 with AS > 1.2.1

### ISSUE THREAD

**Issue by kennym** [react-native-community/async-storage#174]
We are currently in the process of migration from RN 0.59.9 to 0.60.4, and we have evidence this package somehow alters the behavior of the `fetch` method.

```
class App extends React.Component {
  constructor(props) {
    super(props)
  }

  async componentDidMount() {
    await AsyncStorage.setItem('sample:test', 'test')

    fetch('https://jsonplaceholder.typicode.com/todos/1')
      .then(async response => {
        const text = await response.text()
        console.log(text)
      })
  }

  render() { return null }
```

Running this code with `react-native-async-storage` versions 1.2.4, 1.5.1 and 1.6.4 results in fetch returning a `response` as a Blob.

![image](https://user-images.githubusercontent.com/160117/62141855-3fc4c780-b2bb-11e9-98dd-3afcc4cfa7b4.png)

Commenting out the line `await AsyncStorage.setItem('bright:test', 'test')` without doing anything else results in the correct behavior of fetch, hence this is why I believe this place is the correct repo to report this issue.

## Expected behavior

Not return a blob.

## Repro steps

1. Clone https://github.com/bright-systems/async-storage-bug-demo
2. Install and run on simulator
3. Watch the console for `[object Blob]`

## Environment

- **Async Storage version**: any version above 1.2.4 (we don't imply things are working below 1.2.4)
- **React-Native version**: 0.60.4
- **Platform tested**: iOS

**Comment by Krizzu** [comment]
Hi @kennym 

I've run your repro app, but I was not able to get the result you do - I've always got proper json response back. This is an interesting case, but honestly, I don't think this package could somehow how `fetch` behaves. Maybe there's more to it?


I guess you see `[object Blob]` while debugging with Chrome, right? What about disabling it and checking local logs through XCode?

**Comment by kennym** [comment]
@Krizzu ran without the debugger attached - you are correct. Who should we take this to?

**Comment by kennym** [comment]
@Krizzu it's an issue with the network inspect functionality in the debugger: https://github.com/jhen0409/react-native-debugger/issues/365

Thanks for testing the issue on your side!

**Comment by Krizzu** [comment]
Glad I could help @kennym
