### ISSUE TITLE
Is there any secure storage or secure local db for react-native?

### ISSUE THREAD

**Issue by muhammadwfa** [react-native-community/async-storage#176]
I need a secure storage, or local db, or a best encryption library for react-native.

Because I want to store some keys, password inside my app.
It should be store in a secure place, here already `AsyncStorage` is exists, but it is not secure to save keys or ids.

**Comment by Krizzu** [comment]
AsyncStorage does not provide encryption layer. You'll have to do it yourself and then store the hashed values.

You can try with [https://github.com/brix/crypto-js](crypto-js).

**Comment by isaaclem** [comment]
@Krizzu : I have the similar question. From Android perspective, AsyncStorage seems to be using SQLite out of the box, wondering if we can choose to use SQLCipher instead of SQLite. Or is there any plan to encrypt SQLite at rest?

**Comment by Krizzu** [comment]
There's a plan to add secure Storage for Async Storage v2.
Current version does not include any encryption selection.
