### ISSUE TITLE
Autolinking does not seem to work

### ISSUE THREAD

**Issue by 101arrowz** [react-native-community/async-storage#177]
## Details:
I must manually link async-storage despite the fact the package supposedly supports autolinking. I am using React Native v0.60.4 with async-storage v1.6.1, running macOS Mojave 10.14.2. The issue occurs only with CocoaPods - Android autolinking works fine.

**Comment by 101arrowz** [comment]
Closed the issue because it doesn't apply to this project - the issue appears to occur for all packages, not just `async-storage`.

**Comment by Krizzu** [comment]
@101arrowz ,

You can post your `Podfile` here, so I could help you out anyway

**Comment by pmninh91** [comment]
@Krizzu I use Android on a Window environment :(

**Comment by talaikis** [comment]
+1. Autolinking doesn't work for this package.

**Comment by Krizzu** [comment]
@pmninh91 	Can you provide more details for your case?

**Comment by BeKnowDo** [comment]
too bad he didn't follow up @Krizzu - probably would have helped someone in the future :)
