### ISSUE TITLE
@react-native-community_async-storage:javaPreCompileRelease android

### ISSUE THREAD

**Issue by srhtylmz19** [react-native-community/async-storage#181]
* What went wrong:
Execution failed for task ':@react-native-community_geolocation:generateDebugRFile'.
> java.nio.file.NoSuchFileException: /Users/serhatyilmaz/Desktop/development/react/TaxiBookingApp/node_modules/@react-native-community/geolocation/android/build/intermediates/merged_man?fests/debug/../../l?brary_man?fest/debug/AndroidManifest.xml

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by Krizzu** [comment]
Hi @srhtylmz19 	,

I guess you meant to [post it on Geolocation repo, right? :)](https://github.com/react-native-community/react-native-geolocation)
