### ISSUE TITLE
can't get value with getItem

### ISSUE THREAD

**Issue by mingxin-yang** [react-native-community/async-storage#182]
## Current behavior

In Android, I can't got the value after I add Facebook SDK in to my project.(the network in china)
```
_bootstrapAsync = async () => {
    const userId = await AsyncStorage.getItem('login');
    console.log(userId);
    // This will switch to the App screen or Auth screen and this loading
    // screen will be unmounted and thrown away.
    this.props.navigation.navigate(userId ? 'App' : 'Auth');
  };
```
## Expected behavior

**get the value**
## Environment

- **Async Storage version**:1.6.1 
- **React-Native version**: 0.59.10
- **Platform tested**: Android
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
I'd need more info to know what's the problem. Are you sure you're saving the data correctly?

**Comment by mingxin-yang** [comment]
Yeah, I had saved the data, it is normal in IOS. I tried use sync storage method likes realm, It is ok, but realm is more complicated.

**Comment by mingxin-yang** [comment]
I think it is Facebook android SDK initialization‘s conflict

**Comment by mingxin-yang** [comment]
I think it is Facebook android SDK initialization‘s conflict

**Comment by Krizzu** [comment]
@mingxin-yang 	is there any error you get while retrieving the data?

**Comment by bcbcbcbcbcl** [comment]
@Krizzu I'm having the same issue, using RN v0.60.3 & Async Storage v1.6.1. No error while retrieving the data but getting null.

**Comment by bcbcbcbcbcl** [comment]
@Krizzu I'm having the same issue, tested on Android using RN v0.60.3 & Async Storage v1.6.1. No error while retrieving the data but getting null.

**Comment by mingxin-yang** [comment]
I use the DedicatedExecutor method fix the problem.
