### ISSUE TITLE
react-native link @react-native-community/async-storage working but throw bellow Error

### ISSUE THREAD

**Issue by vikasnikam** [react-native-community/async-storage#183]
ExceptionsManager.js:76 [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

To fix this issue try these steps:

  • Run `react-native link @react-native-community/async-storage` in the project root.

  • Rebuild and restart the app.

  • Run the packager with `--clearCache` flag.

  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

  • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md

If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-async-storage/issues

**Comment by Krizzu** [comment]
@vikasnikam Please do not ignore the template for issues. They're there, so I (or someone else) could provide help.
