### ISSUE TITLE
Incompatibility 'com.android.support:appcompat-v7:28.0.0' and 'com.google.firebase:firebase-core:17.0.1'

### ISSUE THREAD

**Issue by Itseme1234** [react-native-community/async-storage#185]
Hi there,

I have a problem within my app/build.gradle, when insering the lines recommended by Firebase:

implement 'com.google.firebase:firebase-core:17.0.1'

after implementing I synced the gradles files, it then states, that line 

implementation 'com.android.support:appcompat-v7:28.0.0' (in app/build.gradle, under dependencies) is wrong and following error message appears:

--> Dependencies using groupId com.android.support and androidx.* can not be combined but found IdeMavenCoordinates{myGroupId='com.android.support', myArtifactId='loader', myVersion='28.0.0', myPacking='aar', myClassifier='null'} and IdeMavenCoordinates{myGroupId='androidx.legacy', myArtifactId='legacy-support-core-utils', myVersion='1.0.0', myPacking='aar', myClassifier='null'} incompatible dependencies less... (Strg+F1) 
Inspection info:There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion).  Issue id: GradleCompatible

Does anybody have a clue what I'm doing wrong?

compileSDKVersion and targetSDKVersion both 28

**Comment by Krizzu** [comment]
@Itseme1234 Hey,

Sorry, but this does not look like it's AsyncStorage related. 

But this error is likely due to mixing `support libs` and `androidx`
