### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_asyncStorage.AsyncStorage.getItem')

### ISSUE THREAD

**Issue by King2231** [react-native-community/async-storage#187]
## Current behavior
I get the above warning and the app gets stuck. Doesn't move ahead. 

![IMG-20190812-WA0003](https://user-images.githubusercontent.com/22017215/62848222-32b2ca00-bcf8-11e9-8ea3-6e28f699adaa.jpg)

## Expected behavior

The app should move ahead of splash screen.

## Repro steps

Create new app using react-native-cli 
Integrate async-storage using yarn
usage:
AsyncStorage.getItem('key1')
.then((response)=>{
 AsyncStorge.getItem('key2')
 .then((response)=>{
  ....other code.
})
.catch((error)=>{});
});
.catch((error)=>{});

Is the nesting causing problem?

## Environment

- **Async Storage version**: on the latest version: 

- **React-Native version**: 0.60.4
- **Platform tested**: Android

**Comment by Krizzu** [comment]
Hey @King2231 ,

Nope, it's not nesting issue. From the code snippet you provided, it looks like it has a syntax error - you placed the semicolon after first `catch` block, making this expression invalid. Try removing it.

**Comment by King2231** [comment]
Did...doesn't fix the issue...

**Comment by Krizzu** [comment]
@King2231 	I'd need more details to help you

**Comment by Krizzu** [comment]
Does it resolve the issue for you, @King2231 ?

**Comment by kaopath** [comment]
If you got an error when this async function running from anywhere in the application it throws this error. Be sure to check other part of the application.

**Comment by AnonymousDrake** [comment]
@Krizzu Thanks mate. Importing as default solved my issue.

**Comment by kfbfarley** [comment]
still got the same problem

**Comment by tido64** [comment]
> @kfbfarley: still got the same problem

This issue is a year old and a lot has changed since. If you're having issues, please open a new one and provide as much details as you can and we'll try to help you.
