### ISSUE TITLE
Illegal char error

### ISSUE THREAD

**Issue by 0zkan** [react-native-community/async-storage#189]
Hi, i need help. 
I used async-storage package in my project but when i built the my project, i get error from that node_module package.

The reason of the error, when that package made built for android, it generates folder in its build folder with Turkish characters
so
android\build\intermediates\lıbrary_manıfest
it should be : android\build\intermediates\library_manifest

how can i fix that ? I'm using windows 7 Turkish language and i cant change it to English language.

Error:
Execution failed for task ':@react-native-community_async-storage:generateDebugR
File'.
> Illegal char <?> at index 7: ..\..\l?brary_man?fest\debug\AndroidManifest.xml

**Comment by 0zkan** [comment]
When i changed language of windows to English. Problem solved. Thanks.

**Comment by Krizzu** [comment]
@0zkan Hey,

Glad you got it working. It's more likely the locale setting that Gradle is using. There's probably a way to change it dynamically (probably through env variables).
