### ISSUE TITLE
Entries must be arrays of the form [key: string, value: string]

### ISSUE THREAD

**Issue by cipriancaba** [react-native-community/async-storage#190]
## Current behavior

When trying to set a null key on iOS 12.4, this error gets triggered and crashes the app `Entries must be arrays of the form [key: string, value: string]`

## Expected behavior

Fail writing the key and log a warning/error but don't crash the app

## Repro steps

Try to set an item to `null` on iOS

## Environment

- **Async Storage version**: 1.6.1
- **React-Native version**: 0.60.4
- **Platform tested**: iOS

**Comment by Krizzu** [comment]
@cipriancaba Hey,

Can you provide a code snipped you use to save that value?

**Comment by jinyang1994** [comment]
```javascript
import AsyncStorage from '@react-native-community/async-storage';
import pkg from '../package.json';

async onStateChange(state) {
  // ticket = { list: [], count: 0 }
  const {
    [TICKET_NAMESPACE]: ticket,
  } = state;

  await AsyncStorage.setItem('version', pkg.version);
  await AsyncStorage.setItem(TICKET_NAMESPACE, JSON.stringify(ticket));
},
```

**Comment by syedamirali14** [comment]
it is not yet solved?

**Comment by luancurti** [comment]
This is caused by `JSON.stringify` check if the variable `title` is not `nul`l or `undefined`

**Comment by Krizzu** [comment]
This happens on ios if either `key` or `value` is null/undefined.

Added checks for those [in this mr](https://github.com/react-native-community/async-storage/pull/259)

**Comment by lylest** [comment]
same problem
