### ISSUE TITLE
Prevent exposing confidential data after integrating Files app in iOS

### ISSUE THREAD

**Issue by aathapa** [react-native-community/async-storage#192]
## You want to:  

Store confidential data in secure location in iOS.

## Details:

![Webp net-resizeimage](https://user-images.githubusercontent.com/16545354/63494008-871a2e80-c4dc-11e9-8dde-bd9af06e71a9.png)

**Comment by Krizzu** [comment]
@aathapa ,

This feature is on todo list for v2, so stay tuned.
