### ISSUE TITLE
AsyncStorage Not Working on React Native 0.60.4

### ISSUE THREAD

**Issue by xinjing1027** [react-native-community/async-storage#193]
## To Expert :  
I have seen you in many excellent Projects.
I am doing React Native App using AsyncStorage, But I got stuck

## Details:
When app start, it gets date from AsyncStorage, But it take 20 or more than 2 minutes.
After get once it works well.
But first getItem method is stuck.
Please help me.

**Comment by xinjing1027** [comment]
I used React Native 0.58, And there was no issue.
But React Native 0.60 seems not good.
I think it happened after I installed npm library react-native-webview.
When I add that library, it seems to install kotlin-?.
I removed react-native-webview, because the app has been much heavier.

I copied your code and it worked really well.
I think it's not just your library problem.
But httpPost and other things are working really well.
Only AsyncStorage not work in a few minutes, or forever.

Please teach me how can I fix this problem.
Thanks.

**Comment by xinjing1027** [comment]
## Condition
I used my own library (with pure JS), helper.js file

I imported AsyncStorage in helper.js

import AsyncStorage from '@react-native-community/async-storage';

saveInfo: async (name, content) => {
        console.log(name);
        console.log(content);
        try {
            await AsyncStorage.setItem('@' + name, JSON.stringify(content));
            console.log(name);
            console.log(content);
        } catch (error) {
            console.error('AsyncStorage error: ' + error.message);
        }
    },
    getInfo: async (name) => {
        console.log(name);
        data = await AsyncStorage.getItem('@' + name);
        console.log(name);
        if (data) {
            return JSON.parse(data);
        }
        return null;
    },

When I call getInfo, I can see only first console.log output.

## Environment
React Native: 0.60.4
AsyncStorage: 1.6.1

**Comment by Krizzu** [comment]
@xinjing1027 	Hey,

What platform you're having an issue with? We had some similar problems with AsyncStorage on Android, taking a really long time before returning data. 

We successfully fixed it with [custom executor feature](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/DedicatedExecutor.md).

**Comment by yazhengwang** [comment]
我打印AsyncStorage.getItem（）读取时间

   console.log('11111',Date.now())
    let uid = await DeviceStorage.get('uid');
    console.log('22222',Date.now())
log time is:
2019年8月23日20时5分4秒329毫秒
2019年8月23日20时6分49秒134毫秒

我记得之前问题已经解决了
"react-native": "^0.59.8",
“@ react-native-community / async-storage”：“^ 1.6.1”，

**Comment by xinjing1027** [comment]
I used Android 7.1
Thanks I will try.
And I have set HERM, it seems works well now, I will check more And add your code.
Thanks again.

**Comment by yazhengwang** [comment]
I resolved,thanks




| |
你男人
邮箱：yazhengwang@126.com
|

签名由 网易邮箱大师 定制

On 08/23/2019 23:53, xinjing1027 wrote:

I used Android 7.1
Thanks I will try.
And I have set HERM, it seems works well now, I will check more And add your code.
Thanks again.

**Comment by xinjing1027** [comment]
Solved, Thanks.
Can you teach me why HERM is good?
I tried to find it but there's no detailed description in facebook docs.
I hope you(I respect you) to give me some ideas.
And Will React-Native the future of Mobile, Is it better than Flutter?
I don't know flutter, but I got stuck many times when building/running react-native.
React native coding is fantastic, but running/building takes more time for me.
Thanks again for your kind help.

**Comment by yazhengwang** [comment]
I don't know much about native, but I've been using RN for a while, and it's nice,
Fluuer is not mature compared with RN at present, so the future is worth looking forward to

At 2019-08-24 00:03:18, "xinjing1027" <notifications@github.com> wrote:


Solved, Thanks.
Can you teach me why HERM is good?
I tried to find it but there's no detailed description in facebook docs.
I hope you(I respect you) to give me some ideas.
And Will React-Native the future of Mobile, Is it better than Flutter?
I don't know flutter, but I got stuck many times when building/running react-native.
React native coding is fantastic, but running/building takes more time for me.
Thanks again for your kind help.

**Comment by Krizzu** [comment]
Glad you got that working.
You can try to get your questions answered on discussion platforms like reddit or something else.

**Comment by BarkhaArora** [comment]
> @xinjing1027 Hey,
> 
> What platform you're having an issue with? We had some similar problems with AsyncStorage on Android, taking a really long time before returning data.
> 
> We successfully fixed it with [custom executor feature](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/DedicatedExecutor.md).

link show 404. can you help?

**Comment by Krizzu** [comment]
@BarkhaArora 
https://react-native-community.github.io/async-storage/docs/advanced/executor
