### ISSUE TITLE
AsyncStorage.setItem not working as expected on iOS

### ISSUE THREAD

**Issue by jordangrant** [react-native-community/async-storage#195]
## Current behavior
Async Storage not working with very basic use case. When I changed my import from using the extracted repo `import AsyncStorage from '@react-native-community/async-storage';` to the core repo`import AsyncStorage from 'react-native'` it works.

```
saveFoo(template) {
        AsyncStorage.getItem('savedFoos').then(b => {
            if (b == null) {
                AsyncStorage.setItem('savedFoos', JSON.stringify([template]));
            }
            else {
                var savedFoos = JSON.parse(b);
                savedFoos.push(template);
                AsyncStorage.setItem('savedFoos', JSON.stringify(savedFoos));
            }
        });
    }
```

## Expected behavior
works

nothing was set to asyncstorage. SetItem failed.
## Repro steps
above code

## Environment

- **Async Storage version**: "@react-native-community/async-storage": "github:react-native-community/async-storage",
- **React-Native version**: RN 60.4 
- **Platform tested**: iOS
- **Logs/Error that are relevant**:

**Comment by MangalBeta** [comment]
same error on IOS
AsyncStorage.setItem not working as expected on RN 0.64

**Comment by MangalBeta** [comment]
working 
Check below changes is store file
 
 import storage from 'redux-persist/lib/storage'; 
        to
import AsyncStorage from '@react-native-community/async-storage';
and set storage =>
const persistConfig = {
  key: 'root',
  storage:AsyncStorage,
  timeout: null,
};

**Comment by Krizzu** [comment]
@jordangrant 
Is any of your dependency using Async Storage from the RN core? It looks like it does and race condition is happening in place.

**Comment by jordangrant** [comment]
@Krizzu genius. I removed all the `import AsyncStorage from 'react-native'` from all my files and used only` import AsyncStorage from '@react-native-community/async-storage';` across my entire project and now it seems to be working.

**Comment by Krizzu** [comment]
Please checkout [my comment about it here](https://github.com/react-native-community/async-storage/issues/118#issuecomment-500138053)

**Comment by danipralea** [comment]
@jordangrant exactly same issue I had. worked for me too. amazing! I've pulled so much hair over it 👍
