### ISSUE TITLE
AsyncStorage_dedicatedExecutor=true not working well

### ISSUE THREAD

**Issue by xinjing1027** [react-native-community/async-storage#196]
## You want to:  
I have issue on "https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/DedicatedExecutor.md"

## Details:
After I add "AsyncStorage_dedicatedExecutor=true", AsyncStorage.getItem worked well.
But it made another issue.
When running app, app shows blank white screen for 1.5~2 seconds.
Then shows splash screen that I implemented.

I added console.log() at App.js Constructor,
Console.log() called after white screen(1.5 ~ 2 seconds).

![blank](https://user-images.githubusercontent.com/51851294/63633155-f9724680-c675-11e9-8bb7-b5e0394c4a0f.png)

Here is log before running constructor
## Log
[05:39:55] D | ReactNative ▶︎ ReactInstanceManager.onJSBundleLoadedFromServer()

[05:39:55] D | ReactNative ▶︎ ReactInstanceManager.recreateReactContextInBackground()
                           │ ReactInstanceManager.runCreateReactContextOnNewThread()
                           └ ReactInstanceManager.tearDownReactContext()

[05:39:56] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[05:39:56] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[05:39:56] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[05:39:56] D | ReactNative ▶︎ CatalystInstanceImpl.destroy() end

[05:39:58] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge
                           │ CatalystInstanceImpl.runJSBundle()
                           │ ReactInstanceManager.setupReactContext()
                           │ CatalystInstanceImpl.initialize()
                           └ ReactInstanceManager.attachRootViewToInstance()

[05:39:59] W | ReactNativeJS ▶︎ Require cycle: node_modules\react-native-firebase\dist\utils\apps.js -> node_modules\react-na
tive-firebase\dist\modules\core\app.js -> node_modules\react-native-firebase\dist\utils\apps.js
                             │ 
                             └ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

[05:39:59] W | ReactNativeJS ▶︎ Require cycle: node_modules\react-native-firebase\dist\modules\admob\index.js -> node_modules
\react-native-firebase\dist\modules\admob\Interstitial.js -> node_modules\react-native-firebase\dist\modules\admob\index.js
                             │ 
                             │ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
                             │ Require cycle: node_modules\react-native-firebase\dist\modules\admob\index.js -> node_modules\react-native-firebase\dist\modules\admob\RewardedVideo.js -> node_modules\react-native-firebase\dist\modules\admob\index.js
                             │ 
                             └ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

[05:40:00] W | ReactNativeJS ▶︎ Require cycle: node_modules\react-native-firebase\dist\modules\database\Reference.js -> node_
modules\react-native-firebase\dist\utils\SyncTree.js -> node_modules\react-native-firebase\dist\modules\database\Reference.js                             │ 
                             │ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
                             │ Require cycle: node_modules\react-native-firebase\dist\modules\core\firebase.js -> node_modules\react-native-firebase\dist\utils\apps.js -> node_modules\react-native-firebase\dist\modules\core\app.js -> node_modules\react-native-firebase\dist\modules\database\index.js -> node_modules\react-native-firebase\dist\modules\core\firebase.js
                             │ 
                             └ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

[05:40:00] W | ReactNativeJS ▶︎ Require cycle: node_modules\react-native-firebase\dist\modules\firestore\DocumentSnapshot.js
-> node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentSnapshot.js
                             │ 
                             └ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

[05:40:00] W | ReactNativeJS ▶︎ Require cycle: node_modules\react-native-firebase\dist\modules\firestore\CollectionReference.
js -> node_modules\react-native-firebase\dist\modules\firestore\Query.js -> node_modules\react-native-firebase\dist\modules\firestore\QuerySnapshot.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentChange.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentSnapshot.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js -> node_modules\react-native-firebase\dist\modules\firestore\CollectionReference.js
                             │ 
                             │ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
                             │ Require cycle: node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js
-> node_modules\react-native-firebase\dist\modules\firestore\utils\serialize.js -> node_modules\react-native-firebase\dist\modules\firestore\DocumentReference.js
                             │ 
                             └ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

[05:40:00] W | ReactNativeJS ▶︎ Require cycle: node_modules\react-native-firebase\dist\modules\firestore\utils\serialize.js -
> node_modules\react-native-firebase\dist\modules\firestore\FieldValue.js -> node_modules\react-native-firebase\dist\modules\firestore\utils\serialize.js
                             │ 
                             │ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
                             │ Require cycle: node_modules\react-native-firebase\dist\modules\core\firebase.js -> node_modules\react-native-firebase\dist\utils\apps.js -> node_modules\react-native-firebase\dist\modules\core\app.js -> node_modules\react-native-firebase\dist\modules\functions\index.js -> node_modules\react-native-firebase\dist\modules\core\firebase.js
                             │ 
                             └ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

[05:40:00] W | ReactNativeJS ▶︎ Require cycle: node_modules\react-native-firebase\dist\modules\storage\index.js -> node_modul
es\react-native-firebase\dist\modules\storage\reference.js -> node_modules\react-native-firebase\dist\modules\storage\task.js -> node_modules\react-native-firebase\dist\modules\storage\index.js
                             │ 
                             └ Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

[05:40:00] I | ReactNativeJS ▶︎ Running application "CarShoppingApp" with appParams: {"rootTag":31}. __DEV__ === true, develo
pment-level warning are ON, performance optimizations are OFF

## Question
As you can see it took 5 seconds. And showing blank white screen.
Please help me how to remove it or how to change the screen blank to image.

**Comment by xinjing1027** [comment]
I can see these 2 comments:
Is used in your app, so that background tasks are queued most of the time
Acts weird on your device (for example, waits for some time before execution)

Which Android versions not working without this?
And what kind of Android Phone not working?

I love your AsyncStorage and like this solution, but I don't want the delay time.
At least I hope to change the background blank white screen to image.

I hope your kind help as before.
Thanks.

**Comment by xinjing1027** [comment]
Actually It's taking 5 seconds.
I used All Tricks for App Performance.

**Comment by Krizzu** [comment]
Have you tried removing Async Storage completely, to see if it's indeed impacting your app?

**Comment by xinjing1027** [comment]
Yes, when I remove "AsyncStorage_dedicatedExecutor=true", there's no delay before splash screen.
But when I remove, the first Async.getItem takes too long time.
After I added it, it shows blank white screen about 2~5 seconds.

I used Bluestacks emulator 4.12(Android 7.1)
React Native is 0.60.4
And the AsyncStorage 1.6.1

**Comment by Krizzu** [comment]
@xinjing1027 Have you tried different emulator or real device?

**Comment by xinjing1027** [comment]
Checked it on Xioami Android 7.
But it's also the same.

**Comment by Krizzu** [comment]
Strange. Can you provide a repro project so I could have a look?

**Comment by xinjing1027** [comment]
Finally, Solved that.
thanks.

**Comment by Krizzu** [comment]
@xinjing1027 	Great :) Mind sharing how you fixed that?

**Comment by xinjing1027** [comment]
Thanks for your help.
That was not your fault.
My project was so heavy.(ecommerce + SNS + a lot of library dependencies)
I optimized import, package.json & used pure component.
Also used hook.
I think your asyncstorage sometimes slow on first minutes when app is too big.
