### ISSUE TITLE
[Android] NativeModule: AsyncStorage is null when try autolinking.

### ISSUE THREAD

**Issue by tadaniya** [react-native-community/async-storage#197]
## Current behavior

`yarn add @react-native-community/async-storage`
and
`react-native run-andoid`

and this error is shown.

![Screenshot_20190826-102504](https://user-images.githubusercontent.com/7720795/63782805-ec2fb300-c926-11e9-8c99-ddffc9c36ceb.png)

## Hint

When I link it manually, 
https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Linking.md#android

it works fine.

but this error is shown on the console.

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - @react-native-community/async-storage (to unlink run: "react-native unlink @react-native-community/async-storage")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
```

## Expected behavior

autolinking works.

## Repro steps

1. `yarn add @react-native-community/async-storage`
2. `react-native run-andoid`

## Environment

- **Async Storage version** : 1.6.1
- **React-Native version**: 0.60.5
- **Platform tested**: Android

**Comment by Krizzu** [comment]
[You can read me about autolinking here](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md). 

Did you update from the previous version of RN or is it a new project?

**Comment by Jakuubzmeko** [comment]
I have this problem as well, I hav ethis problem since RN 0.59, so I upgraded to 0.60 thinking it would solve the problem, but didn't.

I tried to remove build, clean project and caches, but still nothing.

**Comment by Krizzu** [comment]
Autolinking works on Android by changing the way it's requiring the Native packages. [Have a look at RN 0.60 `MainApplication.java`](https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.60.5/RnDiffApp/android/app/src/main/java/com/rndiffapp/MainApplication.java). Compare it with your file and make changes accordingly.

**Comment by Jakuubzmeko** [comment]
@Krizzu I have RN 0.65, 
- upgraded files as in upgrade helper on official website, so i dont have ani packages or imports from external libraries other than specified in mentioned file by you
- unlinked manually all libraries
- cleared caches, deleted build file, cleaned project

I don't know whether I should see these packages in android studio, should I ?


![image](https://user-images.githubusercontent.com/49398874/63945780-3b372e80-ca74-11e9-8600-70c8359902d7.png)

Also android studio at startup says this:

```Unsupported Modules Detected: Compilation is not supported for following modules: react-native-gesture-handler, @react-native-community_async-storage, react-native-google-signin, react-native-svg, react-native-reanimated, react-native-linear-gradient, react-native-vector-icons, rn-fetch-blob. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project.```

These are the modules that are shown on the picture. I don't know whether it is connected to the problem

**Comment by Jakuubzmeko** [comment]
I linked the libraries manualy, async-storage, gesture-handler and google-sign-in, and it works fine. 
Either they dont support autolinking, or autolinking doesn't work at my project

**Comment by royhanrahim** [comment]
Do you have to be linked to run this library ?? 
isn't it for react-native@0.60.5 no need to link ??
if I error in IOS

**Comment by Krizzu** [comment]
@Jakuubzmeko 	What's the content of your `MainApplication.java`?

**Comment by Jakuubzmeko** [comment]
@Krizzu It was the same, so I wanted to show you, so I unlinked them again, and edited the ```MainApplication.java``` then I ran it and it works just fine. 
What I think happend, that i did not unlink them properly before by react-native unlink, but just removed references from ```build.gradle``` and ```MainApplication.java```. So maybe linking and unlinking helped. Still wandering what happened.

**Comment by ianmcgregor** [comment]
Got the same error. Doing a `cd android/ && ./gradlew clean` before `run-android` fixed autolinking for me.

**Comment by trungnguyencmu** [comment]
Show add ` new AsyncStoragePackage());` in MainApplication.java
https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Linking.md#android
