### ISSUE TITLE
AsyncStorage.js: Unexpected token, expected ";" (40:5)

### ISSUE THREAD

**Issue by tgmarinho** [react-native-community/async-storage#198]
Hi, I got this error when I am trying to compile:

``` 
 Starting compilation in watch mode...
 Found 0 errors. Watching for file changes.
 Starting the development server...
 Failed to compile.
/Users/myuser/Developer/tindev-monorepo/node_modules/@react-native-community/async-storage/lib/AsyncStorage.js
SyntaxError: /Users/myuser/Developer/tindev-monorepo/node_modules/@react-native-community/async-storage/lib/AsyncStorage.js: Unexpected token, expected ";" (40:5)

  38 | }
  39 | 
> 40 | type ReadOnlyArrayString = $ReadOnlyArray<string>;
     |      ^
  41 | 
  42 | type MultiGetCallbackFunction = (
  43 |   errors: ?$ReadOnlyArray<Error>,
```

Versions:

"@react-native-community/async-storage": "^1.6.1",
"react-native-web": "0.11.1",
 "react-native": "^0.60.5"

**Comment by Krizzu** [comment]
I'd need more info about your setup - it seems like your app is not transpiled somehow. What's your `.babelrc/babel.config.js` content?

**Comment by r-bman** [comment]
Same issue here.

```
// babel.config.js...

module.exports = {
  presets: ["module:metro-react-native-babel-preset"]
}

```

**Comment by Krizzu** [comment]
@r-bman 	Have you tried to clean metro's cache?
`react-native start --resetCache`

**Comment by AnyByte** [comment]
Getting the same error with this code
```
const storage = Platform.select({
  web: () => require("localforage"),
  android: () => require("@react-native-community/async-storage").default
})();
```
when compiling for the **WEB**. I don't understand why bundler still tries to import it when it clearly shouldn't.

**Comment by jason-cf** [comment]
I'm still seeing this exact error, and I'm using react-native-web too, but an even later version: 0.13.14

@AnyByte, where is packages/web/config-overrides.js? Can you give the full path? is this a webpack file?

Anyone else having this issue?



react: ^16.13.1 => 16.13.1 
react-native: 0.62.2 => 0.62.2 
react-native-web: ^0.13.14
@react-native-community/async-storage: ^1.8.1

**Comment by muazazhar** [comment]
I'm also getting this error. I've tried reseting cache, cleaning gradle, uninstalling and installing again. I only get this error in i18n confign file. In other files same code works fine

    "@react-native-async-storage/async-storage": "^1.17.11",
    "react": "17.0.2",
    "react-i18next": "^11.15.4",
    "react-native": "0.66.5",


code:
`const lang = await AsyncStorage.getItem('language');`

**Comment by tido64** [comment]
@muazazhar: This issue is probably no longer relevant to the error you're seeing. We've sinced migrated AsyncStorage to TypeScript. If you're still seeing Flow issues, it's not because of AsyncStorage.
