### ISSUE TITLE
Why uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared ?

### ISSUE THREAD

**Issue by romreed** [react-native-community/async-storage#199]
## You want to:  

I got this error. Why minSdk 19? You break a lot of old devices. 
## Details:

ERROR: Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:@react-native-community_async-storage] /Users/reed/WebstormProjects/asist/node_modules/@react-native-community/async-storage/android/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="com.reactnativecommunity.asyncstorage" to force usage (may lead to runtime failures)

**Comment by Krizzu** [comment]
You can override AsyncStorage's mininum SDK by providing your own `minSdkVersion` value in root project extension.

**Comment by romreed** [comment]
@Krizzu I override but I interested if it will work as it should at old devices.

**Comment by Krizzu** [comment]
AsyncStorage is based on SQLite which was available in android prior to 19 (kitkat), so I'd say it should work.

**Comment by romreed** [comment]
@Krizzu thank you

**Comment by Krizzu** [comment]
@romreed 	you're welcome
