### ISSUE TITLE
Error compiling the app  in android

### ISSUE THREAD

**Issue by franjorub** [react-native-community/async-storage#205]
## Current behavior

Error running the app android

## Expected behavior

compile the app

## Repro steps
yarn add @react-native-community/async-storage
react-native run-android

## Environment

- **Async Storage version**: 1.6.1
- **React-Native version**: 0.60.4
- **Platform tested**: android
- **Logs/Error that are relevant**: \node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java:34: error: cannot find symbol
@ReactModule(name = AsyncStorageModule.NAME)

**Comment by Krizzu** [comment]
@franjorub Please clean your build and reinstall dependencies.

**Comment by christopherney** [comment]
Same issue

**Comment by Dav1nx1** [comment]
Why you close the issue?

**Comment by tido64** [comment]
This is an almost two year old issue. With how much has progressed since, It may no longer be relevant. If you're having issues, please create a new issue and fill out the form as best as you can, and we'll try to provide help where possible.

**Comment by Dav1nx1** [comment]
Ok, nice, thanks for the answer.
