### ISSUE TITLE
[General] Cleanup

### ISSUE THREAD

**Issue by Krizzu** [react-native-community/async-storage#21]
## About
I call this cleanup task, but it's actually a `to do` that I believe will increase the usability of this repo.
Open for any discussion/proposals. If someone would like to help with anything, feel free to (just post in this issue).

### Auto-generated documentation
- [ ] In progress

I believe simple HTML-from-markdown generator would do the job. We currently have two pages - API and Manual Linking - so GitHub pages should be sufficient to display them as HMTL.

### Unit tests for JS interface
- [ ] In progress

Test public interface that consumes the native module.

## Done:

<strike>

### GitHub template issues 

To help maintainers maintain and issuers issue, unified way of communication is the key. I believe a separate template for bugs, feature request, and questions would be helpful here.
</strike>

<strike>

### Write CONTRIBUTORS guide

A helpful guide for newcomers, willing to help out with Async Storage.
</strike>

<strike>

### Automatic sematic releases

Automatic, regular, semantic releases with patches/fixes would be useful.
</strike>

----

## More to come

The list will keep growing over time, so feel free to post your ideas/thoughts.

Thanks!

**Comment by jcurtis** [comment]
I've noticed the "Manual Linking" guide is missing info for iOS https://github.com/react-native-community/react-native-async-storage/blob/master/docs/Linking.md

**Comment by Krizzu** [comment]
@jcurtis 	Hey,

Would you like to help with that?
I'd love this guide to have some screenshots from manual linking steps, I find those more useful than raw text.

thanks.

**Comment by jcurtis** [comment]
@Krizzu I ended up using the steps from the react native docs 👉  https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking

**Comment by Krizzu** [comment]
Closing this in favor of v2.
