### ISSUE TITLE
AsyncStorage not working on iOS 13, RN 0.60.5

### ISSUE THREAD

**Issue by gabrielbull** [react-native-community/async-storage#211]
## Current behavior

No error thrown, `getItem` simply always returns null

## Expected behavior

`getItem` should return value set by `setItem`

## Repro steps

```js
AsyncStorage.setItem('test', '123', err => {
  if (err) console.error(err)
  else {
    AsyncStorage.getItem('test', result => {
      console.log(result) // ALWAYS null
    })
  }
})
```

## Environment

- **Async Storage version**: 1.6.1, 1.5.1
- **React-Native version**: 0.60.5, 0.60.4
- **Platform tested**: iOS 13.0

**Comment by nikilarigela** [comment]
@gabrielbull  did you find the solution.

**Comment by gabrielbull** [comment]
Yeah, I must of been half awake when I tumbled on this issue. The code sample will never work because it is wrong. It should be:

```js
AsyncStorage.setItem('test', '123').then(() => {
  AsyncStorage.getItem('test').then(result => {
    console.log(result) // ALWAYS null
  })
})
```

That's what happens when you overwork your employees 🤣
