### ISSUE TITLE
Problem with getItem

### ISSUE THREAD

**Issue by alexandre033** [react-native-community/async-storage#215]
Hello,
I want to use the getItem to check if there are any value in the storage and if not try to log the user. But when i use await AsyncStorage.getItem('@access') it return a weird object.. Or the storage is empty !!

the object is like : 
{"_40":0, "_65":0,"_55":null,"_72":null}
It's normal ?

**Comment by Krizzu** [comment]
@alexandre033 What you see is likely a stringified Promise object. All AsyncStorage methods are `async`, so you need to either `await` them (if used in `async` function) or use `then/catch`.

**Comment by m2mathew** [comment]
@alexandre033 I had this same issue the first time I used `AsyncStorage` from this package. I realized I missed an `await` before my call to `getItem()`. +1 Krizzu 😎 

If you are using `async/await`, then it might look something like this:

```JavaScript
const STORAGE_KEY = 'Test';
export const readCookieFromStorage = async () => {
  const data = await AsyncStorage.getItem(STORAGE_KEY, () => console.log('getItem completed));
  return data;
};
```

Though, I would suggest adding a `try/catch` in async functions, too. 😉
