### ISSUE TITLE
Build failed with an exception. Android

### ISSUE THREAD

**Issue by EmmanuelID** [react-native-community/async-storage#217]
## Current behavior

After installing the package with yarn add @react-native-community/async-storage the build fails with this error:

What went wrong:
A problem occurred configuring project ':@react-native-community_async-storage'.
 - Could not resolve all artifacts for configuration ':@react-native-community_async-storage:classpath'.
   - Could not download bundletool.jar (com.android.tools.build:bundletool:0.5.0)
      - Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.5.0/bundletool-0.5.0.jar'.
         -Failed to create SHA1 hash for file /home/emmanuel/.gradle/caches/modules-2/files-2.1/com.android.tools.build/bundletool/0.5.0/ffd6077d13937213b860c0022174ece60000eabc/bundletool-0.5.0.jar.`

## Environment

- **Async Storage version**: "^1.6.1",
- **React-Native version**: "0.60.5"
- **Platform tested**: Android

**Comment by Krizzu** [comment]
@EmmanuelID Can you try again? Seems like the package was down for some reason, but now it's available again.

**Comment by EmmanuelID** [comment]
Thanks, it worked.
