### ISSUE TITLE
error when build a debug apk

### ISSUE THREAD

**Issue by Abdalmajid** [react-native-community/async-storage#220]
Hi,

I got an error when build a debug apk for android, How can fix the issue

command: 
./gradlew assembleDebug

Log:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':@react-native-community_async-storage:extractDebugAnnotations'.
> Could not resolve all task dependencies for configuration ':@react-native-community_async-storage:lintClassPath'.
   > Could not resolve org.bouncycastle:bcpkix-jdk15on:1.56.
     Required by:
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools:sdk-common:26.4.1
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools.build:builder:3.4.1
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools.build:builder:3.4.1 > com.android.tools.build:apkzlib:3.4.1
      > Could not resolve org.bouncycastle:bcpkix-jdk15on:1.56.
         > Could not get resource 'https://jitpack.io/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.pom'.
            > Could not GET 'https://jitpack.io/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.pom'. Received status code 522 from server: Origin Connection Time-out
   > Could not resolve org.bouncycastle:bcprov-jdk15on:1.56.
     Required by:
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools:sdk-common:26.4.1
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools.build:builder:3.4.1
         project :@react-native-community_async-storage > com.android.tools.lint:lint-gradle:26.4.1 > com.android.tools.build:builder:3.4.1 > com.android.tools.build:apkzlib:3.4.1
      > Could not resolve org.bouncycastle:bcprov-jdk15on:1.56.
         > Could not get resource 'https://jitpack.io/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar'.
            > Could not HEAD 'https://jitpack.io/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar'. Received status code 522 from server: Origin Connection Time-out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s

---------------------------------------
## Environment
"@react-native-community/async-storage": "^1.6.2",
"react": "16.8.6",
"react-native": "0.60.5",
"Platform tested: Android

**Comment by Krizzu** [comment]
[Fixed it](https://github.com/react-native-community/async-storage/issues/218#issuecomment-535377621)
