### ISSUE TITLE
[Android] Project with path ':@react-native-community_async-storage' could not be found in project ':app'.

### ISSUE THREAD

**Issue by anniewey** [react-native-community/async-storage#221]
Hi, I was trying to upgrade to RN 0.60 but receive below error when compile the build and `gradlew clean`. Is there any step that I missed? FYI, I already unlinked the library.

```
Script '/Users/xxx/dev/xxx/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 107

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':@react-native-community_async-storage' could not be found in project ':app'.
```

native_modules.gradle
```
void addReactNativeModuleDependencies() {
    reactNativeModules.forEach { reactNativeModule ->
      def nameCleansed = reactNativeModule["nameCleansed"]
      project.dependencies {
        // TODO(salakar): are other dependency scope methods such as `api` required?
        implementation project(path: ":${nameCleansed}") // line 107
      }
    }
  }
```

"@react-native-community/async-storage": "^1.6.2"
"react-native": "0.60.0"

**Comment by anniewey** [comment]
Found the issue is actually caused by this line in `build.gradle`. Removing it fixes the issue.

```
apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

**Comment by adamsythe** [comment]
what is that line supposed to do and is deleting it safe?

**Comment by Krizzu** [comment]
This line adds auto-linking task to gradle task. Removing this will cause auto-linking to stop working.

**Comment by adamsythe** [comment]
so the real issue is that  the version of
react-native-community_async-storage 
Doesnt use autolinking and is causing an error, so the solution is probably to up the version of that?

**Comment by Krizzu** [comment]
The issue most people have with auto-linking is that the manual linking is still in place, while it should be removed.

**Comment by anniewey** [comment]
> The issue most people have with auto-linking is that the manual linking is still in place, while it should be removed.

This indeed was the cause. Upon removing all traces of manual linking, it starts to work. I added that piece of code back for auto linking. 

_PS: I didn't update here after I managed to get it to run correctly._

**Comment by jordenchang55** [comment]
@anniewey I had the same issue, and I fixed it by add this line into `android/setting.gradle`.

```groovy
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
```

**Comment by Anujmoglix** [comment]
> ```groovy
> apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
> ```

Getting android/undefined'at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)

**Comment by tido64** [comment]
@Anujmoglix: This issue is a year old and your issue may not be related at all. Please open a new issue and with more details so we can help you.
