### ISSUE TITLE
Deprecated API Android

### ISSUE THREAD

**Issue by LukePenkava** [react-native-community/async-storage#223]
React Native version: 0.61.2
RNC-Async-Storage version: 1.6.2
Platform: Android, Android studio 3.4.2

## Current behavior

Building in Android studio throws this Java compiler information. Not sure how big deal it is.

```
/Users/home/Desktop/APLIKACE/test/node_modules/@react-native-community/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.
```

**Comment by Krizzu** [comment]
@LukePenkava From my research - not a big deal for now.

**Comment by Andriiklymiuk** [comment]
This prevents from building the app, how it can be fixed?

**Comment by Krizzu** [comment]
@Andriiklymiuk but this is a warning, right? Warnings won't stop your build

**Comment by Andriiklymiuk** [comment]
@Krizzu well, in my case it was plain crash, but it somehow disappeared after project cleanup.
So yes, it is not big deal

**Comment by tomhallam** [comment]
> @Krizzu well, in my case it was plain crash, but it somehow disappeared after project cleanup.
> So yes, it is not big deal

What did you do to clean your project up? I am struggling with errors from a number of libraries which means that the app cannot be packaged.

**Comment by Krizzu** [comment]
I'd need an error message that actually says the cause the crash.
Warnings do not prevent your package to be build

**Comment by tomhallam** [comment]
Ultimately the failure is:

`Type com.google.android.gms.common.internal.zzf is referenced as an interface from com.google.android.gms.internal.zzcku`.

There appear to be deprecated APIs in a couple of my dependencies, but as you say I don't believe these warnings are causing the build to fail. But something is!

From Android Studio:

![Screenshot 2019-10-11 at 16 59 16](https://user-images.githubusercontent.com/202395/66666476-96019f80-ec48-11e9-99cb-4ecd3b2de199.png)

**Comment by James-E-Adams** [comment]
In the same boat trying to upgrade React Native from 0.59 -> ^0.61. Have tried `async-storage` on v1.3.3 and v1.6.2 but getting this error and can't build on Android. Anyone come up with a temp solution?

**Comment by Krizzu** [comment]
@tomhallam @James-E-Adams Are you using firebase by any chance?

**Comment by maxKimoby** [comment]
- Delete `node_modules`
- run `npm install` or `yarn`
- run `jetifier`

Do you still have the issue?

**Comment by Malikkhoja** [comment]
In case of release build on 0.61.2, how should we run jetifier?

**Comment by maxKimoby** [comment]
I believe when you run `jetifier` it parses all your `node_modules` and changes the deprecated imports to remove support libraries. When running `react-native run android` (development mode), it calls jetifier by default. So I think you have to run jetifier at the root of your project so it can modify the deprecated imports in your node_modules and then build your app for release.

You should see this line:

`Jetifier found 1353 file(s) to forward-jetify. Using 4 workers...`

**Comment by ste001** [comment]
I know this issue is closed, but I'm encountering the same exact issue as @LukePenkava, even the behaviour is the same.

I tried @maxKimoby solution, but it didn't solve it, I still got the same error on `AsyncStorageModule.java`.

The problem is, it's not a warning, it's an error that prevents me from building the app.

**Comment by carmelocatalfamo** [comment]
@ste001 for me `npx jetify` it works.
I have this command on `postinstall` script but seems not work after `npm install` or `yarn install`
It works running manual

**Comment by Gra55h0pper** [comment]
Ran into the same issue here. However, it only seems to stop the build process in Android Studio. When running 'react-native run-android' it compiles OK for me.

**Comment by hrezah** [comment]
I have the same issue here ... 
this warning prevent me from releasing the app . 

error is : 
![image](https://user-images.githubusercontent.com/28643300/70089867-e0aaf280-15cd-11ea-8911-0396021c4554.png)


and im sure adding async storage cause this error . 

however its 'npx react-native run-android' works fine

**Comment by hrezah** [comment]
I have the same issue here ...
this warning prevent me from releasing the app .

error is :
* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'npx.cmd'' finished with non-zero exit value 1

and im sure adding async storage cause this error .

however its 'npx react-native run-android' works fine

**Comment by hrezah** [comment]
I have the same issue here ...
this warning prevent me from releasing the app .

error is :

What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
Process 'command 'npx.cmd'' finished with non-zero exit value 1

and im sure adding async storage cause this error .

however 'npx react-native run-android' works fine

**Comment by cmcleese** [comment]
This should be reopened.
I'm also stuck building my app with the following error:

I've tried v1.6.3 , 1.7.1 same error

```
node_modules\@react-native-community\async-storage\android\src\main\java\com\reactnativecommunity\asyncstorage\AsyncStorageModule.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.
```

**Comment by luatnd** [comment]
If you Recompile with -Xlint:deprecation for details, you'll get:
>[deprecation] GuardedAsyncTask(ReactContext) in GuardedAsyncTask has been deprecated

**Solution:**
- Use `react-native link` or manual linking to link your dependency instead.
  ```
  @react-native-community/async-storage
  ```
- If another error appears => Prevent auto-linking in react-native
  project_root/react-native.config.js
  ```
  function getDisableAutoLinkingConf() {
  return {
    platforms: {
      ios: null // disable iOS platform, other platforms will still autolink if provided
    },
    hooks: {},
    assets: [],
    params: []
  }
}

module.exports = {
  dependencies: {
    "reactnativecommunity\asyncstorage": getDisableAutoLinkingConf(),
  }
}
  ```

**Comment by mgarabedian** [comment]
I've been having this issue to. It appears in Android Studio for me, seemingly out of nowhere.

I was able to finally get around it, using a combination of deleting the .idea folder, 'npx jetify', opening the project, syncing the project with gradle, cleaning the project and then Invalidate Caches and Restart.

**Comment by teradeiriz** [comment]
`npx jetify` didn't help. Here how I fixed the problem

1. Deleted `./node_modules`, `./android/.idea` and `./android/gradle` folders
2. Increased daemon memory heap. Added this lines to `./android/gradle.properties`
```
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4096m
```
3. Restarted computer
4. Ran `yarn && cd android && ./gradlew clean && ./gradlew app:assembleRelease`

**Comment by sintylapse** [comment]
`npx jetify` didn't help. Here how I fixed the problem

1. Deleted `./node_modules`, `./android/.idea` and `./android/gradle` folders
2. Increased daemon memory heap. Added this lines to `./android/gradle.properties`
```
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4096m
```
3. Restarted computer
4. Ran `yarn && cd android && ./gradlew clean && ./gradlew app:assembleRelease`

**Comment by RnbWd** [comment]
I just ran into this issue, but it turned out that asyncstorage was not what was causing the build to fail, it was the 90% of the error message though

**Comment by happyfloat** [comment]
This fixed my problem after adding react-native sentry:
https://stackoverflow.com/a/62459483

**Comment by Anzormumladze** [comment]
if you are facing this error now ,try clean gradlew and run this command npx react-native run-android

**Comment by alexxfreitag** [comment]
I'm having this problem... clean gradlew didn't work :(

**Comment by tido64** [comment]
> @alexxfreitag: I'm having this problem... clean gradlew didn't work :(

This issue is a year old and a lot has changed since. If you're having issues, please open a new one and provide as much details as you can and we'll try to help you.
