### ISSUE TITLE
Data must be migrated? What are those @ on beginning of keys on the samples?

### ISSUE THREAD

**Issue by jacargentina** [react-native-community/async-storage#225]
• When i migrated from 

`import AsyncStorage from react-native`
to:
`import AsyncStorage from '@react-native-community/async-storage'` 

as both APIs are equal, i was hoping no data migration was needed; but now when loading data i'm getting a `rawData` key on the loaded data, which should not be there? Maybe i'm missing something there... Any advice would be nice

• Samples like this
```javascript
storeData = async () => {
  try {
    await AsyncStorage.setItem('@storage_Key', 'stored value')
  } catch (e) {
    // saving error
  }
}
```
Why key `storage_Key` is prefixed with an @ ? Do it MUST be prefixed like that ? Or is it simply some nomenclature ?

**Comment by Krizzu** [comment]
Regarding key naming - it's up to you. Some people prefer to prefix all keys with, for example, app name.

There's no need to do data migration - it's the same Async Storage that was on Core. Do you have a repro steps/repo that shows `rawData` being returned?

**Comment by jacargentina** [comment]
@Krizzu now i've found my confusion; i was using `react-native-storage` before; sorry about this. Closing now.
