### ISSUE TITLE
 Async Storage It takes a long time to the first call

### ISSUE THREAD

**Issue by Alekano** [react-native-community/async-storage#226]
## You want to:  
 Async Storage It takes a long time to the first call getItem.. , why ? 

## Details:
• Expo Sdk 33 
• React Native 0.59 

When I use getItem and it is the first time it takes a long time to solve it

**Comment by Krizzu** [comment]
@Alekano You cannot use this library with Expo.

**Comment by Alekano** [comment]
¿ Algun motivo en especial ?

Necesitaria saber por que podria suceder eso ya que en Iphone no sucede pero en Android Si
