### ISSUE TITLE
App crashes on iOS, device only

### ISSUE THREAD

**Issue by Hatko** [react-native-community/async-storage#229]
## Current behavior

Whenever I send an object to AsyncStorage it crashes on iOS level (reproducable only for device)

## Expected behavior

I would expect a promise, which is returned from `setItem` to fail instead

## Repro steps

`AsyncStorage.setItem('key', {'foo': 'bar'})`

## Environment

- **Async Storage version**: 1.6.2
- **React-Native version**: 0.59.10
- **Platform tested**:  iOS, device only
- **Logs/Error that are relevant**: 
```
RCTFatalException: Exception '-[__NSDictionaryM length]: unrecognized selector sent to instance 0x280d14620' was thrown while invoking multiSet on target RNCAsyncStorage with params ( ( ( "@CONNECTED_CARS:deviceToken"
```

**Comment by Krizzu** [comment]
@Hatko 
can you show me a snippet you use to save item and item itself?
Also, remember to stringify the value you're saving - only values as strings are supported.

**Comment by Hatko** [comment]
@Krizzu 

Thanks for a response. 

Actually, not stringifying causes issues. As I noted, the behavior for objects varies between platforms and it crashes an app only on an iOS device. Whenever you try to save `an object` the lib will ignore it in all the cases (android, simulator android, simulator ios) and only crash on a real iOS device.

I understand, that following the instructions and typings is a good idea, but this type of behavior can create some unexpected results and crashes. It might make sense to make the promise which `setItem` returns fail whenever a non-string value was passed.

**Comment by Krizzu** [comment]
Some kind of warning in dev mode would be useful actually.

Mind opening a PR? :)

**Comment by Hatko** [comment]
@Krizzu can do this/next week

**Comment by Hatko** [comment]
As there is already a PR fixing it, we can close the issue
