### ISSUE TITLE
Android not compiling on production

### ISSUE THREAD

**Issue by dragonfire1119** [react-native-community/async-storage#235]
## Current behavior

When I use ``react-native run-android --variant=release`` I get ``java.nio.file.NoSuchFileException: ...@react-native-community/async-storage/android/build/intermediates/res/symbol-table-with-package/release/package-aware-r.txt``

## Expected behavior

Compile on release variant

## Repro steps

Run react-native run-android --variant=release

## Environment

- 1.6.2: @react-native-community/async-storage 
- 0.61.2: React Native 
- Android: 
- N/A:

**Comment by Praveencena88** [comment]
Hi, Were you able to solve the issue

**Comment by Krizzu** [comment]
@Praveencena88 If you see any error while building, please post it here

**Comment by Praveencena88** [comment]
while building with variant i got this issue

**Error log** : 
```
* What went wrong:
Execution failed for task ':app:processExternalDevReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.nio.file.NoSuchFileException: C:\Users\gokul.p\Senvion\applications\service_guide_mobile_v2.0\node_modules\@react-native-community\async-storage\android\build\intermediates\res\symbol-table-with-package\release\package-aware-r.txt 
```

**Version :**
```
react-native: "^0.61.4"
@react-native-community/async-storage: "^1.6.2"
OS : "Android"
```

**Comment by Krizzu** [comment]
@Praveencena88 Can you try remove `build` from `node_modules\@react-native-community\async-storage\android\` and try again?

**Comment by Praveencena88** [comment]
@Krizzu Same issue is occuring, i tried after removing the build

**Comment by Krizzu** [comment]
@Praveencena88 Can you post the whole error log you get?
