### ISSUE TITLE
Read values from asyncStorage in native module

### ISSUE THREAD

**Issue by dominiczaq** [react-native-community/async-storage#238]
## You want to:  
Read (and possibly write) data from asyncStorage in native module (java/swift)

## Details:
Hi there 👋 
Is there a way to read (and possibly write) saved data by js code from native module?
I found some workarounds for java on Stackoverflow but posts there are from more than 3 years ago.
If currently there is no public api for it could you please point me into right direction of implementing something which might be at least a bit future proof (considering ASv2 work)?

**Comment by Krizzu** [comment]
@dominiczaq We have implemented the [delegate that can read/write to storage on iOS.](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/BrownfieldIntegration.md)

Currently there is no equivalent for Android, unfortunately.

I haven't give much thought about allowing access to saved data from native, although I think that's something we could discuss for the v2 in the future.

**Comment by dominiczaq** [comment]
thanks for the quick response!

looking at the android source code, getting value might be possible by
using

ReactDatabaseSupplier::getInstance
and
AsyncLocalStorageUtil::getItemImpl

I'll try to confirm that when I'm not on mobile 😅

**Comment by gordoneliel** [comment]
In the same boat. Looking to save an item from native iOS in a notification service extension into AsyncStorage. In a sea of linking issues. Anyone successfully done this?

**Comment by Krizzu** [comment]
@gordoneliel what kind of linking issues you see?

**Comment by dominiczaq** [comment]
> I'll try to confirm that when I'm not on mobile 😅

I've used 
```
AsyncLocalStorageUtil.getItemImpl(ReactDatabaseSupplier.getInstance(context).get(), "key"));
```
and it seems to be working.

Question is - is it safe? Is there a possibility of ie. memory leaks?

**Comment by Krizzu** [comment]
@dominiczaq Can't tell for sure, but it seems like it's fine (they way you used those classes are the same way of how the module is using them).

**Comment by gordoneliel** [comment]
@Krizzu Thanks for the response. I'm getting these linking issues. 
![Screen Shot 2019-11-07 at 2 25 54 PM](https://user-images.githubusercontent.com/5516761/68433120-a71bce80-016a-11ea-9fa6-43fabb9f6ff5.png)
![Screen Shot 2019-11-07 at 2 26 12 PM](https://user-images.githubusercontent.com/5516761/68433121-a71bce80-016a-11ea-9c29-eda4e8495c98.png).

I also also wondering what the best way to achieve saving state from an app extension to AsyncStorage is. What I'm trying to do now is create an instance of AsyncStorage with the current js bundle and save to AsyncStorage with the multiSet function. Do you know if this would work in the first place?

![Screen Shot 2019-11-07 at 2 29 34 PM](https://user-images.githubusercontent.com/5516761/68433314-109bdd00-016b-11ea-8082-913ec8ad5c8c.png)

**Comment by Krizzu** [comment]
@gordoneliel Hard to tell just from ss what's wrong. Have you tried to clean and rebuild the project? Are you opening project through `.xcworkspace` ?

Regarding your question - I've never had a case that I had to access `AsyncStorage` from native side. Although, I think your approach is fine. I'd also add some helper to write/read from it, as using `.multi*` directly is not super elegant IMO.

**Comment by gordoneliel** [comment]
@Krizzu I am using the xcworkspace file. Below is my pods for the service extension
target 'notificationService' do
  inherit! :search_paths
end

The project has no problem importing the header files for 
#import <React/RCTBundleURLProvider.h>
#import <React/RCTBridge.h>

However, when I try to create an instance of any react native library, I get a linker error. Is there a setup for a project with extensions?

**Comment by Krizzu** [comment]
@gordoneliel AFAIK, you don't need any extra setup. cc @tido64

**Comment by tido64** [comment]
@gordoneliel It looks like you're not linking `libReact.a` and `libRNCAsyncStorage.a`. How are you consuming React Native? Does your `Podfile` include it? Are you using auto-linking?

**Comment by gordoneliel** [comment]
@tido64 I am using autolinking. This is my Podfile. I used   inherit! :search_paths on my notificationService extension. It's able to import the header files, just not the actual implementations. Do I have to link them manually?

```
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'comingsoon' do
  # Pods for ComingSoon
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  
  use_native_modules!
  
end

target 'comingsoonTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'notificationService' do
  inherit! :search_paths
  
end
```

**Comment by tido64** [comment]
@gordoneliel: As far as I understand (I'm no CocoaPods expert), `comingsoon` is the only target that will link with React Native and any other native modules. `notificationService` will only inherit the search paths as you've declared, but will rely on the native modules being present in whatever they will be linked into. If it is supposed to be standalone, you'll need to add your `pod` lines here as well. There might be a clever way to do this without having to copy but I don't know how that would look like off the top of my head.

**Comment by gordoneliel** [comment]
@tido64  I updated my Podfile with these dependencies. I am not including the Dev-Support pod but I have build issues with an API that is not available to share extensions so the build breaks.

```
  target 'notificationService' do
    inherit! :search_paths
    
    pod 'React', :path => '../node_modules/react-native/'
    pod 'React-Core', :path => '../node_modules/react-native/'
    pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  
    pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
```

![Screen Shot 2019-11-18 at 12 00 10 PM](https://user-images.githubusercontent.com/5516761/69086386-288d1f80-09fb-11ea-9172-0dbc926a086c.png)

**Comment by gordoneliel** [comment]
For anyone running into this issue, I was able to resolve it by marking "Require Only App-Extension-Safe API" to No, under Xcode's build settings. Looks like react-native is using some API unavailable to App extensions.

**Comment by gordoneliel** [comment]
@Krizzu @tido64  Was able to resolve the linking issues. Thanks for the help! However, I'm still finding a hard time trying to save data into AsyncStorage from native iOS to JS. I implemented the delegates for storage but can't seem to use the default storage implementation to save to the same store that JS uses. Any ideas?

**Comment by dominiczaq** [comment]
> @dominiczaq We have implemented the [delegate that can read/write to storage on iOS.](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/BrownfieldIntegration.md) [](/react-native-community/async-storage/blob/HEAD@{2019-11-06T14:22:35Z}/docs/advanced/BrownfieldIntegration.md)
> 
> Currently there is no equivalent for Android, unfortunately.
> 
> I haven't give much thought about allowing access to saved data from native, although I think that's something we could discuss for the v2 in the future.

Sorry for digging out some antics but could you elaborate on the delegate? Do I understand that correctly that when using `RNCAsyncStorageDelegate` I'll have to implement all delegate's protocol methods by myself?

**Comment by tido64** [comment]
@dominiczaq, @gordoneliel: Once you've implemented `RNCAsyncStorageDelegate`, you're in charge of storing/retrieving data. JS will store/retrieve data the same way native does, and not vice versa, if that makes sense. E.g. if I had an `RNCAsyncStorageDelegate` implementation that stores everything in memory only, JS will do the exact same thing (after all, it's the exact same code being executed).

If you don't want to implement the storage yourself, you can also retrieve the RNCAsyncStorage instance and access the storage directly. I've outlined how it can be done in #80.

**Comment by TBH-TPB** [comment]
> @dominiczaq We have implemented the [delegate that can read/write to storage on iOS.](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/BrownfieldIntegration.md)
> 
> Currently there is no equivalent for Android, unfortunately.
> 
> I haven't give much thought about allowing access to saved data from native, although I think that's something we could discuss for the v2 in the future.

@Krizzu I follow the link in your post but it's not available anymore. Can you give me the updated link? Thanks

**Comment by Krizzu** [comment]
Yup, [it's in our docs](https://github.com/react-native-community/async-storage/blob/master/docs/advanced/BrownfieldIntegration.md)

**Comment by focux** [comment]
@Krizzu  Isn't there a way to just get the value without having to implement all the delegate methods?

**Comment by dominiczaq** [comment]
see first comment here
https://github.com/react-native-community/async-storage/issues/80

**Comment by cabelin** [comment]
Here [brownfield](https://react-native-community.github.io/async-storage/docs/advanced/brownfield) has a example using Objective C, anyone has a example using Swift?

**Comment by jamescampbell02** [comment]
> Yup, [it's in our docs](https://github.com/react-native-community/async-storage/blob/master/docs/advanced/BrownfieldIntegration.md)

This link is also no longer available, is there an updated one?

**Comment by jamescampbell02** [comment]
> Yup, [it's in our docs](https://github.com/react-native-community/async-storage/blob/master/docs/advanced/BrownfieldIntegration.md)

This is link is also no longer available, is there an updated one?

**Comment by jaydips2020** [comment]
Hi @gordoneliel @tido64  we created one extention for app (custom keyboard) that can handle from react native. i tried to import asyncStorage in this files but we can't get access.if you know how to get access then please help me.

This is the file structure for extention:

![image](https://user-images.githubusercontent.com/68462761/142420159-4dad8cce-dea9-49c3-9f50-a748f03cef1e.jpg)

This is the KeyboardViewController.h file
```#import <UIKit/UIKit.h>
#import "React/RCTAsyncLocalStorage.h"
#import "RNCAsyncStorage.h"

@interface KeyboardViewController : UIInputViewController

@end
```
KeyboardViewController.m file like this

```
#import "KeyboardViewController.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <React/RCTAsyncLocalStorage.h>
#import <React/RCTBridgeModule.h>
#import "RNCAsyncStorage.h"
#import <CodePush/CodePush.h>


@interface KeyboardViewController ()
  @property (nonatomic, strong) UIButton *nextKeyboardButton;
  @property (nonatomic) RCTRootView *rootView;
  @property (nonatomic) RCTBridge *bridge;
  @property (nonatomic) UIView *circleView;
@end

KeyboardViewController * keyboardViewController = nil;

@implementation KeyboardViewController

- (void)updateViewConstraints {
    [super updateViewConstraints];
    
  
    if (self.rootView) {
        NSLog(@"chaning root view dimensions");
        self.rootView.frame = CGRectMake(0, 0, self.view.frame.size.width, self.view.frame.size.height);
    }
}

- (void)viewDidLoad {
    [super viewDidLoad];
  
    CGFloat _expandedHeight = 240;
    NSLayoutConstraint *_heightConstraint =
        [NSLayoutConstraint constraintWithItem: self.view
                                   attribute: NSLayoutAttributeHeight
                                   relatedBy: NSLayoutRelationEqual
                                      toItem: nil
                                   attribute: NSLayoutAttributeNotAnAttribute
                                  multiplier: 0.0
                                    constant: _expandedHeight];
    [self.view addConstraint: _heightConstraint];
    
    RNCAsyncStorage *asyncStorage = [_bridge moduleForClass:[RNCAsyncStorage class]];
    asyncStorage.delegate = self;

    NSLog(@"Added loading view");
    
    /* Custom RN View */
    self.bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:@{@"keyboardExtension": self}];
  
    NSDictionary *props = @{@"isKeyboard" : @true};
    self.rootView = [[RCTRootView alloc] initWithBridge:self.bridge
                                                     moduleName:@"RNKeyboard"
                                               initialProperties:props];
    [self.view addSubview:self.rootView];
    /* Custom RN View - end */
  
    
    [self updateViewConstraints];
    keyboardViewController = self;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  #if DEBUG
    return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"qurpKeyboard" fallbackResource:nil];
  #else
    return [CodePush bundleURL];
  #endif
}

- (void)viewWillLayoutSubviews
{
    self.nextKeyboardButton.hidden = !self.needsInputModeSwitchKey;
    [super viewWillLayoutSubviews];
}

- (void)textWillChange:(id<UITextInput>)textInput {
    // The app is about to change the document's contents. Perform any preparation here.
}

- (void)textDidChange:(id<UITextInput>)textInput {
    // The app has just changed the document's contents, the document context has been updated.
    
    UIColor *textColor = nil;
    if (self.textDocumentProxy.keyboardAppearance == UIKeyboardAppearanceDark) {
        textColor = [UIColor whiteColor];
    } else {
        textColor = [UIColor blackColor];
    }
    [self.nextKeyboardButton setTitleColor:textColor forState:UIControlStateNormal];
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
}
@end

```

KeyboardExtension.m like this

![image](https://user-images.githubusercontent.com/68462761/142418490-bc4a43f3-1799-4f49-bea7-b3f6b71d92cc.png)

**Comment by tido64** [comment]
@jaydips2020: Isn't this kinda backwards? It looks like you're trying call `moduleForClass:` before the bridge has been instantiated:
```objc
    RNCAsyncStorage *asyncStorage = [_bridge moduleForClass:[RNCAsyncStorage class]];
    asyncStorage.delegate = self;

    NSLog(@"Added loading view");
    
    /* Custom RN View */
    self.bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:@{@"keyboardExtension": self}];
```

**Comment by jaydips2020** [comment]
@tido i putted after initialization of keyboard but its not works.

**Comment by jaydips2020** [comment]
Hi @tido64  @gordoneliel  if you know about this then pls help us.

**Comment by jaydips2020** [comment]
> @jaydips2020: Isn't this kinda backwards? It looks like you're trying call `moduleForClass:` before the bridge has been instantiated:
> 
> ```objc
>     RNCAsyncStorage *asyncStorage = [_bridge moduleForClass:[RNCAsyncStorage class]];
>     asyncStorage.delegate = self;
> 
>     NSLog(@"Added loading view");
>     
>     /* Custom RN View */
>     self.bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:@{@"keyboardExtension": self}];
> ```

@tido i putted after initialization of keyboard but its not works.
 I changed to this.
```
    self.bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:@{@"keyboardExtension": self}];
    self.bridge = [self.bridge moduleForClass:[RNCAsyncStorage class]];
```
