### ISSUE TITLE
AsyncStorage is not available in expo 

### ISSUE THREAD

**Issue by duylinhdang1998** [react-native-community/async-storage#244]
![image](https://user-images.githubusercontent.com/40199004/68458565-b0be3880-0235-11ea-8cf7-65cbca629816.png)
I installed react-native-community/async-storage and using App but got error in my picture! How do fix that?? Thanks you

**Comment by el-angel** [comment]
How did you fix it?

**Comment by duylinhdang1998** [comment]
wait expo support it

**Comment by darrylyoung** [comment]
Using Expo, has anyone come across a solution to this other than sticking with the now-deprecated React Native _official_ AsyncStorage package?

**Comment by saur2729** [comment]
> Using Expo, has anyone come across a solution to this other than sticking with the now-deprecated React Native _official_ AsyncStorage package?

no not yet, I'm waiting for the developers to add a support for EXPO apps
In the meanwhile, you can use this - 
import { AsyncStorage } from 'react-native'

**Comment by shanhuiyang** [comment]
looking forward resolving this issue.

**Comment by saur2729** [comment]
> looking forward resolving this issue.

Thanks man.
It would be great if you could prioritise it. As a beginner I'm more into expo for ease of configuration.

**Comment by LouisJS** [comment]
Up :)

**Comment by spit4520** [comment]
> > Using Expo, has anyone come across a solution to this other than sticking with the now-deprecated React Native _official_ AsyncStorage package?
> 
> no not yet, I'm waiting for the developers to add a support for EXPO apps
> In the meanwhile, you can use this -
> import { AsyncStorage } from 'react-native'

If you use the above suggestion ^^ it will clear up most standard issue. Cannot guarantee for edge cases

**Comment by Gregoirevda** [comment]
up

**Comment by code-by** [comment]
any update? )

**Comment by Waleed9042** [comment]
up

**Comment by chris-chao** [comment]
Is this a known issue? I am running Expo 37 and am running into this as well. I have tried all the steps listed in the Error screenshot and still nothing. Thanks.

**Comment by Krizzu** [comment]
Addressed here
https://github.com/react-native-community/async-storage/pull/368
