### ISSUE TITLE
Truly async storage for web

### ISSUE THREAD

**Issue by forabi** [react-native-community/async-storage#245]
## Motivation

It looks like web support for async storage is actually backed by a sync storage (`localStorage` or `sessionStorage`) which could be problematic when serializing large objects.

## Description

There should be no functional changes.

## New feature implementation

Would you be interested in implementing this via https://github.com/WICG/kv-storage? I can take a stab at it.

**Comment by Krizzu** [comment]
@forabi 

Let's discuss including `kv-storage` as additional option to web-storage.
I would keep the local and session storage and include `kv-storage` as additional option (maybe set as default).

From the link you provided, I understand it's a proposal that's yet to be implemented, right?

**Comment by forabi** [comment]
@Krizzu 

> This feature would be implemented as a built-in module. It would also use IndexedDB as its backing store; see more on that below.

This is a new kind of "built-in" modules that are designed to be easily polyfillable but the browsers supporting them natively would just use the native implementation and not load the polyfill.

More info here: https://www.npmjs.com/package/idb-keyval

I'm totally open to using something else, like, e.g. [`idb-keyval`](https://www.npmjs.com/package/idb-keyval)

**Comment by Krizzu** [comment]
@forabi Thanks,

Looks like using `idb-keyval`, which is based on `IndexedDB` is less hassle than including [import maps](https://developers.google.com/web/updates/2019/03/kv-storage#import_maps) and [module scripts](https://developers.google.com/web/updates/2019/03/kv-storage#what_about_browsers_that_dont_support_modules_at_all) to get `kv storage`, right?

**Comment by forabi** [comment]
@Krizzu yes, I was trying to "future-proof" the implementation but I do agree that `idb-keyval` is much simpler (also has decent TS support).

**Comment by Krizzu** [comment]
Sounds good to me. Let me know if you need any help/have a question regarding implementation 💪

**Comment by Krizzu** [comment]
Implemented in latest `master` branch.
