### ISSUE TITLE
Question: result order of .mutliGet method

### ISSUE THREAD

**Issue by ziyoshams** [react-native-community/async-storage#246]
## You want to:  

For `multiGet` method, is order of returned results guaranteed to match the order of arguments?

**Comment by Krizzu** [comment]
[It looks like it does](https://github.com/react-native-community/async-storage/blob/LEGACY/lib/AsyncStorage.js#L252-L254)

**Comment by ziyoshams** [comment]
> [It looks like it does](https://github.com/react-native-community/async-storage/blob/LEGACY/lib/AsyncStorage.js#L252-L254)

Thank you 🙏
