### ISSUE TITLE
* What went wrong: A problem occurred evaluating project ':app'. > Failed to apply plugin [id 'com.android.application']    > Minimum supported Gradle version is 5.4.1. Current version is 4.8.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip for Android Studio

### ISSUE THREAD

**Issue by amit6061** [react-native-community/async-storage#248]
## Environment

- **Async Storage version**: 
- **React-Native version**: 
- **Platform tested**: 
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Update Gradle version, like the info you copied over says.

**Comment by amit6061** [comment]
But I have changed the version but problem is same
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.8.1. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip

**Comment by Krizzu** [comment]
You need to change version in gradle wrapper (if you're using the wrapper). Otherwise, use higher version of Gradle CLI.

**Comment by amit6061** [comment]
I have changed the gradle wrapper version ,I got the same error.

**Comment by Krizzu** [comment]
And you run your gradle tasks through `gradlew`, correct?

**Comment by amit6061** [comment]
yes
