### ISSUE TITLE
expired async-storage

### ISSUE THREAD

**Issue by datpham96** [react-native-community/async-storage#250]
## Expected behavior

I use async-storage. After setItem, I turn off the app, after about 2 hours to 3 am I can go back to the app to get it?

## Environment

- **Async Storage version**: "^1.6.2"
- **React-Native version**: "0.59.9"
- **Platform tested**: Android/Ios
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Hey @datpham96 

I'd need more info about what's actually happening. Repro project would be best.

**Comment by Krizzu** [comment]
@datpham96 any update?
