### ISSUE TITLE
AsyncStorageModule.java: uses or overrides a deprecated API. Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by harleenarora** [react-native-community/async-storage#252]
Hi, I am using current version of async-storage:1.6.3 and react-native:0.61.4 but I got a error after install the package. 

Error: AsyncStorageModule.java: uses or overrides a deprecated API. Recompile with -Xlint:deprecation for details.

**Comment by ste001** [comment]
Didn't work for me, but it looked like [this comment](https://github.com/react-native-community/async-storage/issues/223#issuecomment-545134717) solved this problem for some people.

You can try this, or if you scroll up on the comments, someone tried to clean Gradle and/or re-install Android Studio with the SDKs.

As for me, I found a solution which worked, but I still don't know how or why. I went to the `build.gradle` on Project Level, and added a specific `kotlinVersion` to it, like this:

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        kotlinVersion="1.3.41"
    }
...
```

**Comment by ricaragao** [comment]
Can you check if you MainActivity.java on line 19 is with correct Override annotation:

`@Override`

Mine was without `@`

**Comment by Krizzu** [comment]
@ricaragao then it's not an annotation

**Comment by Krizzu** [comment]
@harleenarora 
Can you provide the full error code/message?

**Comment by harleenarora** [comment]
Hi, I have already solved this issue using `multiDexEnabled true `

**Comment by Krizzu** [comment]
@harleenarora Great, closing the issue then 👍

**Comment by cmcleese** [comment]
I'm also still experiencing this issue.
Enabling `multiDexEnabled` did not help.

See my cross post : [here](https://github.com/react-native-community/async-storage/issues/223#issuecomment-569537022)
