### ISSUE TITLE
Passing null or undefined as a value to setItem or multiSet doesn't result in an error.

### ISSUE THREAD

**Issue by leemcmullen** [react-native-community/async-storage#253]
## Current behavior

If `null` or `undefined` is passed as a value to `setItem` or `multiSet` then no error is generated and therefore any listening `.catch()` methods/`catch` blocks/error callbacks don't fire to let you know something went wrong.

## Expected behavior

I would expect an error to be generated in the same way as if any other invalid value was passed e.g. number, bool, object.

## Repro steps

```
            try {
              await AsyncStorage.setItem('aTestKey', null, e => {
                console.error(`Error in callback`, { e });
              });
            } catch (e) {
              console.error(`Error in catch`, { e });
            }
```

## Environment

- **Async Storage version**: 1.6.2
- **React-Native version**: 0.61.4
- **Platform tested**: Android
- **Logs/Error that are relevant**: N/A

**Comment by Krizzu** [comment]
hi @leemcmullen 

Why would you expect to see the error here? Passing `null` or `undefined` (which is parsed as `null`/`nil` in android/ios) is normal thing, in situations like clearing stored data.

**Comment by leemcmullen** [comment]
Hi @Krizzu 

I should have been slightly more clear in my description, apologies.

I'm **assuming** it's causing an error because if I chain a `.then()` to `setItem` with a null value, the function within then is never fired. Similarly using the `await` syntax instead, it never gets to the next line after it's awaited.

So based on that, I'm assuming something is going wrong within `setItem` which is causing the promise to fall over and not resolve or reject. 

I would expect the promise to resolve if `setItem` completes successfully and the fact that it doesn't appear to be doing with a null or undefined value so is what led me to assume an error was occurring.

Thanks,
Lee

**Comment by Krizzu** [comment]
@leemcmullen 

Got it. Yeah, that seems like an issue to me too. I'll try to check it out

**Comment by leemcmullen** [comment]
@Krizzu 

Great, thanks. Let me know if you need anything else from me or if I can help any further.

Cheers,
Lee

**Comment by Krizzu** [comment]
@leemcmullen Yes, you're right - the error is being swallowed [in here](https://github.com/react-native-community/async-storage/blob/LEGACY/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java#L227-L229).

Going to fix that :)

**Comment by leemcmullen** [comment]
Fantastic, thanks @Krizzu - much appreciated 👍

**Comment by Krizzu** [comment]
@leemcmullen do you mind checking out #259 ?
