### ISSUE TITLE
Can't read item in Android, works in IOS

### ISSUE THREAD

**Issue by Sbphillips19** [react-native-community/async-storage#256]
I am setting up push notifications with react native firebase and have followed this tutorial:

https://medium.com/@anum.amin/react-native-integrating-push-notifications-using-fcm-349fff071591

Everything works fine on IOS, but for android I can't get it working and it seems that the issue is due to async storage.

This is my current toggle for  turning notifications on:

```
export const toggleNotifications = (channel) => {

  return async (dispatch, state) => {
    const currentUserID = firebaseService.auth().currentUser.uid;
    const channelNotification = FIREBASE_REF_NOTIFICATIONS.child(channel).child(currentUserID)
  
      let fcmToken = await AsyncStorage.getItem('fcmToken');
      
      // ON IOS THIS COMES BACK AS TOKEN
      // ON ANDROID I GET NULL
      alert(fcmToken)
      channelNotification.set(fcmToken)
      dispatch(loadNotificationsSuccess(channel, fcmToken))
  }
}
```

Here are the versions I am using:

```
 "@react-native-community/async-storage": "^1.6.3",
 "react-native": "0.60.5",
```

Why would I be getting back the token for IOS, but not android?  If I put an alert in my initial render I get the same response for each so I think fetching the token works-

  ```
render() {
    alert(JSON.stringify(AsyncStorage.getItem('fcmToken')))
    return (
      <Provider store={store}>
          <ChatApp />
      </Provider>)
  }
```

**Comment by Krizzu** [comment]
@Sbphillips19 How do you store your token?
Is it possible that you (or your dependencies) still use `AsyncStorage` from RN core?

**Comment by Sbphillips19** [comment]
import AsyncStorage from '@react-native-community/async-storage';

  ```
//3
  async getToken() {
    let fcmToken = await AsyncStorage.getItem('fcmToken');
    if (!fcmToken) {
      fcmToken = await firebase.messaging().getToken();
      if (fcmToken) {
        // user has a device token
        await AsyncStorage.setItem('fcmToken', fcmToken);
      }
    }
  }
```

**Comment by Krizzu** [comment]
@Sbphillips19 
> Is it possible that you (or your dependencies) still use AsyncStorage from RN core?

When you read from storage after you `.setItem`, do you see `null` value?

Also:
```js
async getToken() {
  let fcmToken = await AsyncStorage.getItem('fcmToken');
  if (!fcmToken) {
    fcmToken = await firebase.messaging().getToken();
    if (fcmToken) {
      // console.log here, so you know that token was read from firebase.
      // user has a device token
      await AsyncStorage.setItem('fcmToken', fcmToken);
    }
  }
}
```

**Comment by Sbphillips19** [comment]
So unfortunately firebase stopped working in debug mode for me when I upgraded to >.60 so I haven't been able to use console.logs.  They said they would not be supporting react native/ had no intention to change the package, but it works fine outside of debug mode.  Therefore I can't use console.logs and only alerts.  Here is how I run it:

  ```
//3
  async getToken() {
    let fcmToken = await AsyncStorage.getItem('fcmToken');
// HERE IS WHERE I GET TOKEN IOS
// DON'T RECEIVE ANYTHING BACK ANDROID
    alert(fcmToken)
    if (!fcmToken) {
      alert("tok fc")
      fcmToken = await firebase.messaging().getToken();
      if (fcmToken) {
        // user has a device token
        alert(fcmToken)
        await AsyncStorage.setItem('fcmToken', fcmToken);
      }
    }
  }
```

**Comment by Krizzu** [comment]
@Sbphillips19 you can run `react-native log-android` in your terminal to see logs.

> how would I completely remove the old async storage? I thought by importing the community version it would be using that

Search through `node_modules` for `AsyncStorage` key.

**Comment by Sbphillips19** [comment]
@Krizzu thanks for the help.  I can’t reproduce anymore and it’s working now.  I rolled back my code to before I tried to implement push notifications due to another bug and didn’t see async anywhere.  My guess is you were right and somehow it was using async as a dependency vs the community version.  Thanks for the help
