### ISSUE TITLE
Async Storage automatically cleared on iOS

### ISSUE THREAD

**Issue by dylancompanjen** [react-native-community/async-storage#257]
## Current behavior
I'm having multiple users report that they lost their app data (which is currently stored with AsyncStorage).
Somewhere I read that this could be due to saving too large stringified data under 1 key. 
I used to save a whole redux store to 1 key in order to persist data but now I grouped data into separate keys. Still I'm having users report that they lose data after a while, so it doesn't seem related to a max string limit.

Is this related to some iOS behavior that auto clears up async storage?

## Expected behavior
I expect that all data persists and doesn't get erased automatically.

## Repro steps
It happens in some cases so it's hard to define the exact repro steps.

## Environment
- **Async Storage version**: v1.6.3
- **React-Native version**: 0.61.4
- **Platform tested**: iOS

**Comment by Krizzu** [comment]
@dylancompanjen This looks like an issue that has been reported few times for iOS. It seems like using both Community AsyncStorage and the one from core. [You can read my comment regarding here.](https://github.com/react-native-community/async-storage/issues/118#issuecomment-500138053)

**Comment by dylancompanjen** [comment]
@Krizzu I'm only using the Community AsyncStorage. Some folks said this happened after restarting their iPhone.

**Comment by Krizzu** [comment]
@dylancompanjen Sure, but it can happen that one (or more) of your dependencies uses Core's `AsyncStorage`, hence the condition race. Try finding reference in your `node_modules`.

**Comment by dylancompanjen** [comment]
@Krizzu can't find a dependency that uses AsyncStorage in my node_modules.

**Comment by Krizzu** [comment]
@dylancompanjen Hmm, that's odd then. And only happens on phone restart? Did you mange to repro this?

**Comment by codecog** [comment]
Users also reporting this for me as well. Sometimes things being cleared 4/5 times within a half-hour period.

**Comment by dylancompanjen** [comment]
@Krizzu No, not necessarily on phone restart. Still getting reports from new users but I'm not sure how to repro it...

**Comment by codecog** [comment]
I'm not sure if this should be closed. Have this happening for me as well and looks like it may be the same issue on 2.0 where the log just randomly says "deleting store" without it being requested.

**Comment by Krizzu** [comment]
@codecog You're talking about the logger from v2?

**Comment by AndresAltomobile** [comment]
Any update? I have users reporting the same, users are losing their data stored with AsyncStorage when they restart the application.

This only happens on iOS.

### Repro steps
I was able to reproduce something similar 
Close the app -> open the app via deep link -> the data that was stored with AsyncStorage disappears.

### Environment 
**Async Storage version**: ^1.15.5
**React-Native version**: 0.64.0
**Platform tested**: iOS

**Comment by lorissikora** [comment]
Issue still perists. I've met this issue while using the library in a managed expo project. From what I experienced, it could be related to some under the hood racing issue. One kind-of-ish way to reproduce for me was to rapidly reload the app while using the expo dev server. This often caused the data to be lost.

**Comment by developeritsec** [comment]
i am facing the same issue on android 
any solution?

**Comment by aqigif** [comment]
i think i'm facing this kind of issue, how to solved this?
