### ISSUE TITLE
 App crashes after setting state from asyncstorage

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [react-native-community/async-storage#258]
React Native version:
```

System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 152.31 MB / 7.70 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4

```
Steps To Reproduce

On click I wanted to remove a link
```

function remove(index) {
    AsyncStorage.setItem(
      'links',
      JSON.stringify(Array.from(links).filter((item, i) => i !== index)),
    ).then(() =>
      AsyncStorage.getItem('links')
        .then(link => {
          setLinks(JSON.parse(link));
        })
        .then(() => ToastAndroid.show('Deleted', ToastAndroid.SHORT)),
    );
  }

```
Describe what you expected to happen:
View should be updated but I get this error.

error link[https://user-images.githubusercontent.com/16081083/69478141-f160a900-0e14-11ea-8a03-a91464ac16df.png](https://user-images.githubusercontent.com/16081083/69478141-f160a900-0e14-11ea-8a03-a91464ac16df.png)

Snack, code example, screenshot, or link to a repository:
[https://github.com/a-c-sreedhar-reddy/Link/blob/master/pages/Home.js#L26](https://github.com/a-c-sreedhar-reddy/Link/blob/master/pages/Home.js#L26)

**Comment by a-c-sreedhar-reddy** [comment]
@a-c-sreedhar-reddy whats legacy tag?

**Comment by Krizzu** [comment]
It's related to `LEGACY` AsyncStorage.

The error you see comes from the fact that View is being updated from non-UI thread. `AsyncStorage` does not modify view in anyway. What about not using `ToastAndroid` in your example?

**Comment by a-c-sreedhar-reddy** [comment]
@Krizzu I tried by removing toast even then the error exists.

**Comment by Krizzu** [comment]
Right, going to look into that

**Comment by Krizzu** [comment]
@a-c-sreedhar-reddy 

Checked your example, the issue is not related to AsyncStorage. If'd look through the stack trace, you'll see that the issue comes from the `Touchable*` from `react-native-gesture-handler`. Replacing this with `Touchable*` from RN does not produce the problem.


Head over to `react-native-gesture-handler` and report issue there.

**Comment by a-c-sreedhar-reddy** [comment]
Yeah. thanks @Krizzu . VSCode imported it from RNGestureHandler.
