### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.

### ISSUE THREAD

**Issue by anastely** [react-native-community/async-storage#260]
## Current behavior

 when I install async-storage **1.6.3 "last version"**

> I Don't change anything in native android code 

I got an error when running the app I'm trying to remove it and rebuild my app BUT the issue still I don't know why!!

## Expected behavior

build the app successfully!

## Repro steps

I'm tried to run these command 

    rm -rf node_modules 
    npm install

then

    cd android && gradlew clean
 
and it's building successfully without any error

but after run
react-native run-android

I got 

> * What went wrong: Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> > com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException:
> com.android.builder.dexing.DexArchiveMergerException: Error while
> merging dex archives:    The number of method references in a .dex
> file cannot exceed 64K.   Learn how to resolve this issue at
> https://developer.android.com/tools/building/multidex.html

 
SO how can I solve it? please it's important "I'm in deadline" 

## Environment
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 161.06 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 16, 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-16 | Intel x86 Atom, android-23 | Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
- *

**Comment by Krizzu** [comment]
@anastely 

```
The number of method references in a .dex
file cannot exceed 64K. Learn how to resolve this issue at
https://developer.android.com/tools/building/multidex.html
```
Like the error says, your project exceeds 64k limit of methods in a single `.dex` file. [You need to enable mutlidex in your build](https://developer.android.com/studio/build/multidex)

**Comment by anastely** [comment]
I follow up it but my app crashed IDK why,
But I installed more than one package and I didn't get the same error when I install asyncStorage package

**Comment by Krizzu** [comment]
@anastely checkout out logs regarding the crash and go from there. If it's related to `AsyncStorage`, please reopen the issue.
