### ISSUE TITLE
AsyncStorage is null. Can't open iOS simulator.

### ISSUE THREAD

**Issue by Wout-Vanneste-student** [react-native-community/async-storage#264]
## Current behavior

When I run 'react-native run-ios --simulator' i get this error:
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening <myproject>.xcworkspace.

So I opened my project from xCode, that works until the app starts. Then I get this error:
![Screenshot 2019-12-07 at 10 44 45](https://user-images.githubusercontent.com/44393610/70372396-9e8bf480-18de-11ea-90c0-e1a664a2505d.png)

My podfile already includes the following:

- require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

- pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

- use_native_modules!

Even after I ran 'pod install' the error remains the same.

## Expected behavior

The app doesn't have a problem with AsyncStorage and starts up normally.

## Environment

- "@react-native-community/async-storage": "^1.6.3"
- "react": "16.9.0"
- "react-native": "0.61.5"
- Platform tested: iOS simulator

**Comment by chronikum** [comment]
Hi,

I had a similar problem. 
I fixed it with killing all node processes, deleting my node_modules, reinstalling them, linking them, pod install, recompiling the app via Xcode (not the npm command!) and checking the build phases, they always mess up at my app.

Hope it helps somehow.

**Comment by Wout-Vanneste-student** [comment]
@chronikum Hi, thanks for the response.

Unfortunately that didn't do the trick. Well, I'm not sure what caused it, but now I can't even open my xcode project, as xcode crashes just seconds after starting up. I did find a solution for this but it doesn't seem to work for me ([https://stackoverflow.com/questions/4455903/xcode-crashing-when-opening-project-file]). My '*.pbxproj' file doesn't seem to be corrupter or anything.

Thanks for the possible solution tho, sure it could've helped if my case was more similar to yours.

**Comment by Krizzu** [comment]
@Wout-Vanneste-student 

I've seen `error code 65` being related to `.xcworkspace` not in sync with pods.
Did you run `pod install` to install pods after adding `AsyncStorage`?

**Comment by Wout-Vanneste-student** [comment]
@Krizzu I believe I did, but after setting up my project again to try and work my way around this, I'm now dealing with the error: "Ivariant Violation: Native module cannot be null." At least as annoying...

**Comment by Krizzu** [comment]
@Wout-Vanneste-student And it's only iOS related, right?

Can you post your podfile?

**Comment by Wout-Vanneste-student** [comment]
@Krizzu yes, I can run my app without problems on my Android device, it's only when I run the app on the simulator.

This is my podfile:
![image](https://user-images.githubusercontent.com/44393610/70375717-6518b080-1901-11ea-8710-f99a80747d61.png)

**Comment by Krizzu** [comment]
@Wout-Vanneste-student Can you try to remove `RNReanimated` and run `pod install` again?

**Comment by Wout-Vanneste-student** [comment]
@Krizzu unfortunately that didn't help. Even tried to remove the whole package (react-native-reanimated) and tried `pod install` after that, or after adding the package back. Still receiving the same error "Invariant Violation..."

**Comment by Krizzu** [comment]
@Wout-Vanneste-student So I'd suggest disable all native packages and add them one by one to see which causes the issue

**Comment by Wout-Vanneste-student** [comment]
@Krizzu The error only shows up after adding the package `react-native-reanimated`. So that's indeed where the issue is coming from. Is there a way to make my project work without this package? Because right now if it's not installed I get this error:
![image](https://user-images.githubusercontent.com/44393610/70376303-d22f4480-1907-11ea-8105-a8b53e1fbbc8.png)

Ideally I would like to be able to make the package work in my project, but I've already tried auto-linking and manually linking the library in Xcode.

**Comment by Wout-Vanneste-student** [comment]
I opened a new issue for this error: [#306](https://github.com/react-navigation/stack/issues/306)
