### ISSUE TITLE
Error on set with array of strings

### ISSUE THREAD

**Issue by ScreamZ** [react-native-community/async-storage#269]
## Current behavior

"com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.String"

When passing an array of string to `set` ["90:FD:9F:73:11:48"]

If I stringify / parse, like in the legacy, it's OKAY

## Expected behavior

Should work

## Repro steps

```ts
import AsyncStorageFactory from "@react-native-community/async-storage";
import LegacyStorage from "@react-native-community/async-storage-backend-legacy";

const legacyStorage = new LegacyStorage();

export type StorageModel = {
  bluetoothDevices: string[];
};

const storage = AsyncStorageFactory.create<StorageModel>(legacyStorage, { errorHandler: console.log, logger: console.log() });

export default storage;
```

## Environment

- **Async Storage version**: ^2.0.0-rc.1
- **React-Native version**: 0.61.5
- **Platform tested**: Only tested on android
- **Logs/Error that are relevant**: 

"com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.String"

**Comment by srk-stack** [comment]
Yah even I'm facing this Error ReadableNativeMap cannot be cast to String. when I logged the value, it is coming as null

**Comment by mikunimaru** [comment]
I have the same problem.
The same behavior as topic contributors occurs with arrays and sets of objects.

**Comment by Krizzu** [comment]
Legacy backend is still using old (Legacy) version of async storage underneath, so any limitations from there, applies to this backend too.

**Comment by mikunimaru** [comment]
In relation to this, we have found a problem that does not catch when writing fails.

``` typescript
    storage
      .set("test", ["a", "b", "c"])
      .then(async () => {
        // Processing to be called when writing is successful.
        const array = await storage.get("test");
        console.log("set success");
        console.log(array);
      })
      .catch(() => {
        // Processing to be called when writing fails.
        console.log("set error");
      });
```
Execution result
```
# set success
# null
```
My environment is the same as the topic contributor.

**Comment by Krizzu** [comment]
"Legacy Storage" is actually using current version of `AsyncStorage` (v1). So every value has to be stringified before saving and parsed before reading.
