### ISSUE TITLE
Upgrade to use 0.61.5 RN

### ISSUE THREAD

**Issue by emmajam** [react-native-community/async-storage#272]
## Current behavior

Async Storage crashes the app when used with the latest stable version of RN (0.61.5)

## Expected behavior

Async Storage should not to crash the application, and work as expected. 

## Repro steps

Upgrade to latest RN 0.61.5 and attempt to use async storage. You will see a crash when Async Storage passes through a WritableArray instead of a ReadableArray

## Environment

- **Async Storage version**: latest
- **React-Native version**: 0.61.5
- **Platform tested**: Android
- **Logs/Error that are relevant**: 

```
No interface method pushArray(WritableArray) in AsyncStorageModule.java 
```

## Fix
Need to modify any methods using pushArrary() or pushMap() to pass through a ReadableArray or ReadableMap, since RN changed the API 
https://github.com/facebook/react-native/commit/1a2937151b8d36e8741ef9d4fbe7d2ebf65cb775#diff-5245d1955ab3db308d8457ee644d939c

**Comment by lmarques6** [comment]
Just ran into this same issue with RN v0.63.0, how did you resolve it?
