### ISSUE TITLE
Store data in async storage

### ISSUE THREAD

**Issue by yhugow** [react-native-community/async-storage#275]
## Question
Hi there, 
I’m new in react native. Would like to ask if its okay to store a data in **async-storage** like  firstname, lastname, email address, userId, username and gender for offline purposes. Password is not involved in here. Or is there any secured way to store data like that? 

Really appreciate for your advised.
Thank you

**Comment by Krizzu** [comment]
Hey @yhugow 

AsyncStorage does not provide any security layer to stored data, so it is up to you to decide in that matter.

**Comment by yhugow** [comment]
> Hey @yhugow
> 
> AsyncStorage does not provide any security layer to stored data, so it is up to you to decide in that matter.

Thank you @Krizzu
