### ISSUE TITLE
mocking v2 async storage in jest

### ISSUE THREAD

**Issue by codecog** [react-native-community/async-storage#278]
## You want to:  
Trying to write some tests around my code with the v2 version but having a bit of trouble mocking out the native module. Some direction here would be great as i think it is a bit different to how legacy is mocked.

**Comment by codecog** [comment]
Great! Thanks @Krizzu

**Comment by JoseLion** [comment]
@Krizzu I wrote a [basic mock implementation](https://gist.github.com/JoseLion/374fa9d6cd49334ec4aa008211cf81d8) which so far seems to be working just fine 🙂 I'd really appreciate it if you could take a quick look to be sure there's nothing missing. Thanks a lot!!

**Comment by Krizzu** [comment]
@JoseLion 
This looks legit. Unfortunately, I'm putting v2 on hold from my side, but feel free to open PR.
