### ISSUE TITLE
Support for Maccatalyst

### ISSUE THREAD

**Issue by giregk** [react-native-community/async-storage#283]
## Current behavior

I'm trying to make my react-native app work with MacOS (Maccatalyst).
Everything works fine (after some fixes on react-native modules which I can provide if necessary) except for React-Native Async-Storage.

When I try to build my project for MacOS, I get the following error
```
ld: library not found for -lRNCAsyncStorage
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Indeed, the library does not appear in the build folder (`~/Library/Developer/Xcode/DerivedData/myapp/Build/Products/Debug-maccatalyst`)
However, no error arise on the build of the library itself (the only error I see is the one above and it appears under the main project)

I'm not totally sure if this comes from this lib or if it comes from react-native, but all my other native libraries work fine.

Thank you all for your help.

## Expected behavior

It should build fine.

## Repro steps
- Fix react-native to work with MacCatalyst
Since this is too big to put inside the issue, I published an article for how to fix react-native 0.59 to work with MacCatalyst. [https://github.com/giregk/react-native-0.59-fix-maccatalyst](https://github.com/giregk/react-native-0.59-fix-maccatalyst)
- Attempt building the project after linking @react-native-community/async-storage

## What I have tried so far

I have tried to apply the following changes to the RNCAsyncStorage Project:
- Project -> info -> iOS deployment target 9.0
- Project -> build settings -> deployment -> macOS deployment Target = macOS 10.15
- Project -> build settings -> Mac Catalyst deployment -> Derive Mac Catalyst Product Bundle Identifier = NO
- Project -> build settings -> Mac Catalyst deployment -> Supports Mac Catalyst = YES

I have also tried to let XCode fix the warning about the the recommended settings

Of course, before each build attempt, I have applied "Product Menu > clean build folder"

//////////
Edit
I also tried to copy paste the module in my project manually and it works. So it is not a problem in the code, but rather a problem in the project config
//////////

## Environment

- **Async Storage version**: 1.7.1
- **React-Native version**: 0.59.10
- **Platform tested**: iOS (Maccatalyst also known as UIKitForMac)
- **Logs/Error that are relevant**:  NA

**Comment by Krizzu** [comment]
Hey @giregk 
I'd love to help here but I have no Maccatalyst experience.
Maybe @tido64 would help here

**Comment by tido64** [comment]
Hi @giregk, how did you add RNCAsyncStorage to your app? Besides linking to it, did you also add a dependency to it anywhere?

**Comment by giregk** [comment]
@tido64 I simply linked it, which added it as a Library in XCode and as a dependency in the build process. Is that what you mean ? I did not do anything custom besides that.

**Comment by tido64** [comment]
@giregk Just so I understand, you added RNCAsyncStorage to

  1. Project > Build Phases > Link Binary With Libraries
  2. Project > Build Phases > Dependencies

Correct? Given that you added those dependencies to the correct target(s), that should be all that you need to do. Are there multiple targets? To be sure, the target that failed to link to RNCAsyncStorage, does it also have this correctly set up?

**Comment by giregk** [comment]
@tido64

OK, sorry for my imprecision in my previous comment.
I had not added RNCAsyncStorage as a dependency in Project > Build Phases > Dependencies.
I only had added it to Project > Build Phases > Link Binary

When I add it to Project > Build Phases > Dependencies, it works.
Thank you very much for your help !

Could you explain why this is needed ? I don't have to do it for other libraries.

**Comment by giregk** [comment]
@Krizzu thank you for sending @tido64 to my rescue !!

**Comment by tido64** [comment]
> Thank you very much for your help !

No problem. Happy to help!

> Could you explain why this is needed ? I don't have to do it for other libraries.

_Project > Build Phases > Link Binary With Libraries_ only tells Xcode what your app should be linked with. It doesn't tell it where to get it from. You _may_ have gotten some of your dependencies by other means (e.g. a downloaded tarball). Since Xcode tries to build things in parallel, it may or may not have built all your dependencies before trying to link the app. By adding RNCAsyncStorage to _Project > Build Phases > Dependencies_, you're telling Xcode that RNCAsyncStorage should be built before building the app. I think you have to do the same for all of your dependencies. I think you just lucked out on the fact that some of your dependencies got built before the app.

**Comment by giregk** [comment]
@tido64 OK, very clear. That's weird though because all my dependencies are npm modules, linked with the `react-native link` command, and that command does not add the library to the list of dependencies, which you seem to believe is mandatory. Thanks again for your help and for the explanation.
