### ISSUE TITLE
Should getItem() return undefined or error when data with given key is not present?

### ISSUE THREAD

**Issue by mrTuomoK** [react-native-community/async-storage#287]
## Motivation
I'd suggest that getItem(keyName) should return either undefined or error when data with given key is not present. Currently data is returned as null if no data available. Now an additional check has to be implemented to check if returned data is null before parsing for example JSON-data.

## Description

Return an error with describing error message or undefined since it's well... undefined

## New feature implementation

^ explained already

**Comment by Krizzu** [comment]
`null` is an absence of a value - it makes more sense to return it instead of `undefined` (uninitialized value) or throwing an error.

**Comment by mrTuomoK** [comment]
ECMAScript® 2019 Language Specification says:

4.3.10 undefined value
primitive value used when a variable has not been assigned a value

4.3.12 null value
primitive value that represents the intentional absence of any object value

And in this case if you have not saved/assigned a value with some key you're trying to get it imho should return undefined. Null itself does not imply a missing value since you can also set some key's value explicitly to null which is a value.

**Comment by Krizzu** [comment]
But you treat both cases either way, correct? Either `null` and `undefined` indicates that the value is not there (either not set yet or set to no value). Having only one "value" for "no value" saves you from having more headaches.

Besides, in regards to NativeModules for React-Native, data is serialized to JSON back and forward through the bridge - and Native languages (Java/Objc in our case) use `null` value as indicator for no value. So either way, if you send `undefined` from JS, it'll be treated as `null` on Native side.

**Comment by mrTuomoK** [comment]
Ah, that's true that the bridge also limits the value type, good point! :) I've also implemented some bridged components but never needed to send or get undefined.
