### ISSUE TITLE
Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null

### ISSUE THREAD

**Issue by nikeshk** [react-native-community/async-storage#289]
## Details:
- I have already tried running `npx react-native link @react-native-community/async-storage` and restarted the build with all the options shown in the screen. 

while running `pod install` there are still errors
` - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.
`

![image](https://user-images.githubusercontent.com/23579781/73626009-5fc0b380-466f-11ea-89f3-d6e87ba11348.png)

Can anyone help, what's wrong with the steps?

**Comment by Krizzu** [comment]
@nikeshk Hey,

What RN version you use?

**Comment by luco** [comment]
Same here.
`"react-native": "0.61.5",`

**Comment by nikeshk** [comment]
@Krizzu 
The react-native version is: 
`"react-native": "0.61.5"`

@luco How can I use `native_framework` ??

**Comment by Krizzu** [comment]
@nikeshk 
With version 0.60+, you should not use `link` feature, because there's auto-linking in place. [Please checkout the RN template's Podfile and compare it with yours](https://github.com/facebook/react-native/blob/master/template/ios/Podfile#L78).  `use_native_modules!` makes auto-linking work (remember to import it through `require_relative` at the top of the file).

**Comment by luco** [comment]
@nikeshk I'm sorry, I miswrote it. It's `use_native_modules!`. You should put it before the `end` section of your target on your podfile.

**Comment by Tidy13** [comment]
Hi! 

I'm facing the same issue "Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null".

In iOS everything work's fine, but not in android. I manually linked but still the same problem.

I'm using:
`"react-native": "0.61.5"`
`"@react-native-community/async-storage": "^1.7.1",`

I let you the actual state of the android files after the link:
**MainApplication**   
```
import com.reactnativecommunity.asyncstorage.AsyncStoragePackage;
....
@Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      packages.add(new AsyncStoragePackage());
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      return packages;
    }

```

**android/app/build.gradle:**
```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':@react-native-community_async-storage')
```

**android/settings.gradle:**

```
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
include ':@react-native-community_async-storage'
project(':@react-native-community_async-storage').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-community/async-storage/android')
```

Can anyone help?

**Comment by jessegranger** [comment]
I have this error when trying to debug a RN app in Expo on Android.

I don't have a podfile to use a `use_native_modules!` line in (podfiles are for iOS only, afaik).

**Comment by Nashid95** [comment]
I'm having the same exact issue. 

I installed same version as you for react native.

Here's my package.json
{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.0",
    "@signalwire/react-native": "^1.0.1",
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.5",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-incall-manager": "^3.2.7",
    "react-native-reanimated": "~1.4.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-unimodules": "~0.7.0",
    "react-native-web": "~0.11.7",
    "react-native-webrtc": "^1.75.3"
  },
  "devDependencies": {
    "@babel/core": "~7.6.0",
    "babel-jest": "~24.9.0",
    "jest": "~24.9.0",
    "metro-react-native-babel-preset": "~0.56.0",
    "react-test-renderer": "~16.9.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
 and I added the use_native_modules! right before end, then stopped and expo started and still same issue.

**Comment by roscioli** [comment]
Added `use_native_modules!` at the end. Added `require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'` right in the beginning of the Podfile. Getting a `ld: 520 duplicate symbols for architecture x86_64` error in xcode on build :/

**Comment by yassati** [comment]
- add this in Podfile : `pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'`
- cd ios && pod install

**Comment by ShyamPanchal** [comment]
Having this issue on Android, how can I fix it ?
using rn 0.61.5 and @react-native-community/async-storage 1.7.1

**Comment by eman-star** [comment]
> @nikeshk
> With version 0.60+, you should not use `link` feature, because there's auto-linking in place. [Please checkout the RN template's Podfile and compare it with yours](https://github.com/facebook/react-native/blob/master/template/ios/Podfile#L78). `use_native_modules!` makes auto-linking work (remember to import it through `require_relative` at the top of the file).

where to use-native-modules exact place for andriod rn version 0.61.5 and  where to import require relative  exact place and line

**Comment by rbsharma** [comment]
@jessegranger were you able to solve the issue. I am also testing on android and there's no podfile for android to work on.
