### ISSUE TITLE
setMultiple on Legacy AsyncStorage not working

### ISSUE THREAD

**Issue by muhamad-rizki** [react-native-community/async-storage#290]
## Current behavior

await storage.setMultiple([{ 'asdasd1': '2' }, { 'asdasd2': 'oooo' }]); // no error / warning
await storage.get('asdasd1'); // return null

await storage.set('asdasd1', 'value'); // no error / warning
await get('asdasd1'); // return 'value';

## Expected behavior

await storage.setMultiple([{ 'asdasd1': '2' }, { 'asdasd2': 'oooo' }]); // no error / warning
await storage.get('asdasd1'); // return '2'

await storage.set('asdasd1', 'value'); // no error / warning
await get('asdasd1'); // return 'value';

## Repro steps

using single set is working, but with setMultiple not working

## Environment

- "@react-native-community/async-storage": "2.0.0-rc.2"
- "@react-native-community/async-storage-backend-legacy": "2.0.0-rc.2",
- "react-native": "0.59.9",
- **Platform tested**: Android
- **Logs/Error that are relevant**: -

**Comment by SaveYourTime** [comment]
I got a similar error with `setMultiple` on Legacy AsyncStorage.
Follow the usage of the example. [setmultiple](https://github.com/react-native-community/async-storage/blob/master/packages/core/docs/API.md#setmultiple)

```js
const value1 = { key1: 'hello1' };
const value2 = { 
    key2: {  
      name: 'jerry',
      age: 25
    }
};
await storageInst.setMultiple([ value1, value2 ])
```

## Error
```
JSON value '(
    key1,
        {
        key1 = hello1;
    }
)' of type NSMutableArray cannot be converted to NSString
```
<img width="584" alt="截圖 2020-03-18 下午12 53 11" src="https://user-images.githubusercontent.com/35715664/76926786-2fc82980-6918-11ea-81a2-2751d1dc3dd0.png">

## Environment
"@react-native-community/async-storage": "^2.0.0-rc.2",
"@react-native-community/async-storage-backend-legacy": "^2.0.0-rc.2",
"react": "16.13.0",
"react-native": "0.61.5"

**Comment by Krizzu** [comment]
Fixed in the latest RC (3).
