### ISSUE TITLE
ERROR: Could not find method android() for arguments [build_1rg1v59oeriv4kmihpnqlgtzy$_run_closure1$_closure3$_closure4@d963f4d] on project ':@react-native-community_async-storage' of type org.gradle.api.Project.

### ISSUE THREAD

**Issue by HelSirius** [react-native-community/async-storage#292]
## can't build the application on android studio 

```
        android {
            buildToolsVersion '28.0.0'
            compileSdkVersion rootProject.ext.compileSdkVersion
            buildToolsVersion rootProject.ext.buildToolsVersion
            defaultConfig {
                minSdkVersion rootProject.ext.minSdkVersion
                targetSdkVersion rootProject.ext.targetSdkVersion
            }
```
## Environment

- **Async Storage version**: 
- **React-Native version**: 
- **Platform tested**: 
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Hey @HelSirius ,
Could you describe the issue in bit more details? 
To follow up, could you format your `build.gradle` output better please? [Here's a Github Markdown guide to help out.](https://guides.github.com/features/mastering-markdown/)

**Comment by HelSirius** [comment]
I wanted to build an application and I go to **file** then **sync project with Gradle files** then I got the error "Could not find method android() for arguments [build.... ] on project  ':@react-native-community_async-storage' " 
The error leads me to 
```android {
            buildToolsVersion '28.0.0'
            compileSdkVersion rootProject.ext.compileSdkVersion
            buildToolsVersion rootProject.ext.buildToolsVersion
            defaultConfig {
                minSdkVersion rootProject.ext.minSdkVersion
                targetSdkVersion rootProject.ext.targetSdkVersion
            }```

**Comment by Krizzu** [comment]
@HelSirius 

Could you post full `build.gradle` content please? It seems like you're missing android plugin

**Comment by HelSirius** [comment]
here it is ... this is the project  `<build.gradle>` file

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 24
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        jcenter()
        google()
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
        classpath 'com.google.gms:google-services:4.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

subprojects {
    afterEvaluate {
        android {
            buildToolsVersion '28.0.0'
            compileSdkVersion rootProject.ext.compileSdkVersion
            buildToolsVersion rootProject.ext.buildToolsVersion
            defaultConfig {
                minSdkVersion rootProject.ext.minSdkVersion
                targetSdkVersion rootProject.ext.targetSdkVersion
            }
        }
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            // Local Maven repo containing AARs with JSC library built for Android
            url "$rootDir/../node_modules/jsc-android/dist"
        }
        maven {
            url "https://jitpack.io"
        }
    }
}
```

**Comment by Krizzu** [comment]
@HelSirius 
What about `app/build.gradle`?

**Comment by HelSirius** [comment]
`app/build.gradle`
```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js",
    bundleConfig: "metro.config.js",
    enableHermes: false,
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

if (System.getenv("SENTRY_ENABLED") == "true") {
    project.ext.sentryCli = [
        logLevel: "error",
        flavorAware: false
    ]

    apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
}

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc-intl:r241213'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.mattermost.rnbeta"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative60"
        versionCode 258
        versionName "1.27.0"
        multiDexEnabled = true
        ndk {
            abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
        }

    }
    signingConfigs {
        release {
            if (project.hasProperty('MATTERMOST_RELEASE_STORE_FILE')) {
                storeFile file(MATTERMOST_RELEASE_STORE_FILE)
                storePassword MATTERMOST_RELEASE_PASSWORD
                keyAlias MATTERMOST_RELEASE_KEY_ALIAS
                keyPassword MATTERMOST_RELEASE_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
        unsigned.initWith(buildTypes.release)
        unsigned {
            signingConfig null
            matchingFallbacks = ['release']
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}

repositories {
    maven {
        url 'https://maven.google.com'
    }
}

configurations.all {
    resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.name == 'play-services-base') {
                details.useTarget group: details.requested.group, name: details.requested.name, version: '15.0.1'
            }
            if (details.requested.name == 'play-services-tasks') {
                details.useTarget group: details.requested.group, name: details.requested.name, version: '15.0.1'
            }
            if (details.requested.name == 'play-services-stats') {
                details.useTarget group: details.requested.group, name: details.requested.name, version: '15.0.1'
            }
            if (details.requested.name == 'play-services-basement') {
                details.useTarget group: details.requested.group, name: details.requested.name, version: '15.0.1'
            }
        }
    }
}

dependencies {
    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }

    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation project(':react-native-document-picker')
    implementation project(':react-native-keychain')
    implementation project(':react-native-doc-viewer')
    implementation project(':react-native-video')
    implementation project(':react-native-navigation')
    implementation project(':react-native-image-picker')
    implementation project(':react-native-device-info')
    implementation project(':reactnativenotifications')
    implementation project(':react-native-cookies')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-svg')
    implementation project(':react-native-local-auth')
    implementation project(':jail-monkey')
    implementation project(':react-native-youtube')
    implementation project(':react-native-exception-handler')
    implementation project(':rn-fetch-blob')
    implementation project(':react-native-webview')
    implementation project(':react-native-gesture-handler')
    implementation project(':@react-native-community_async-storage')
    implementation project(':@react-native-community_netinfo')
    implementation project(':@sentry_react-native')
    implementation project(':react-native-android-open-settings')
    implementation project(':react-native-haptic-feedback')

    implementation project(':react-native-fast-image')
    // For animated GIF support
    implementation 'com.facebook.fresco:fresco:2.0.0'
    implementation 'com.facebook.fresco:animated-gif:2.0.0'
    // For WebP support, including animated WebP
    implementation 'com.facebook.fresco:animated-webp:2.0.0'
    implementation  'com.facebook.fresco:webpsupport:2.0.0'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}


project.ext.envConfigFiles = [
        debug: ".env",
        release: ".env",
        anothercustombuild: ".env",
]


apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
apply plugin: "com.android.application"

apply plugin: 'com.google.gms.google-services'
```

**Comment by Krizzu** [comment]
@HelSirius You have duplicated `apply plugin: "com.android.application"` - can the remove the bottom one?

**Comment by HelSirius** [comment]
@Krizzu I did and still the same error

**Comment by HelSirius** [comment]
@Krizzu  I did and still not working 
![photo_2020-02-10_14-41-23](https://user-images.githubusercontent.com/45997793/74147099-9b312400-4c13-11ea-9772-e37772f26801.jpg)

**Comment by Krizzu** [comment]
@HelSirius 
Right, so in your root `build.gradle` you have `subprojects { afterEvaluate { } }` configurations. This goes through all modules that are added to your project, including AsyncStorage. 

If Async Storage is used a module (in your case, it is) it does not include `android` plugin, hence no `android` block is available.

To fix that, add a check if `android` block exists:

```
subprojects{
    afterEvaluate {
        // check if `android` block is available
        if(it.hasProperty('android')){
            android {
               // your content here
            }
        }
    }
}
```

**Comment by HelSirius** [comment]
There is android block available there  and it is 
```

subprojects {
    afterEvaluate {
        android {
            buildToolsVersion '28.0.0'
            compileSdkVersion rootProject.ext.compileSdkVersion
            buildToolsVersion rootProject.ext.buildToolsVersion
            defaultConfig {
                minSdkVersion rootProject.ext.minSdkVersion
                targetSdkVersion rootProject.ext.targetSdkVersion
            }
        }
    }
}
```

**Comment by Krizzu** [comment]
@HelSirius 
Please add `if(it.hasProperty('android'))`, like in my example. This will ensure that `android` block will be used in modules that use `android` build tools.

**Comment by HelSirius** [comment]
@Krizzu Thank you.... The error got fixed but it is showing another error that says `react.gradle` doesn't exist inside `/node_modules/react-native` folder.

**Comment by tido64** [comment]
@HelSirius: Since you've 👍'd @Krizzu's suggestion, does that mean that you've resolved your issue?

**Comment by HelSirius** [comment]
@tido64 Yes I did and thank you @Krizzu

**Comment by tido64** [comment]
Great! I'll close this issue then.

**Comment by maazshaikh1711** [comment]
Hello.
I'm getting this error.



FAILURE: Build failed with an exception.

* Where:
Script '/Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 124

* What went wrong:
A problem occurred evaluating root project 'unifiedApp'.
> Could not find method implementation() for arguments [DefaultProjectDependency{dependencyProject='project ':react-native-async-storage_async-storage'', configuration='default'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

BUILD FAILED in 6s

    at makeError (/Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/user/mobile-app/node_modules/@react-native-community/cli/build/index.js:192:9)

**Comment by zaheersani** [comment]
> Hello. I'm getting this error.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script '/Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 124
> * What went wrong:
>   A problem occurred evaluating root project 'unifiedApp'.
> 
> > Could not find method implementation() for arguments [DefaultProjectDependency{dependencyProject='project ':react-native-async-storage_async-storage'', configuration='default'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> BUILD FAILED in 6s
> 
> ```
> at makeError (/Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
> at /Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async runOnAllDevices (/Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
> at async Command.handleAction (/Users/user/mobile-app/node_modules/@react-native-community/cli/build/index.js:192:9)
> ```

Did you get any solution to this problem?

**Comment by skizzo** [comment]
> Hello. I'm getting this error.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script '/Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 124
> * What went wrong:
>   A problem occurred evaluating root project 'unifiedApp'.
> 
> > Could not find method implementation() for arguments [DefaultProjectDependency{dependencyProject='project ':react-native-async-storage_async-storage'', configuration='default'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
> 
> BUILD FAILED in 6s
> 
> ```
> at makeError (/Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
> at /Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async runOnAllDevices (/Users/user/mobile-app/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
> at async Command.handleAction (/Users/user/mobile-app/node_modules/@react-native-community/cli/build/index.js:192:9)
> ```

Hi, I'm running into this as well. Did you find a solution?

**Comment by pranayjain29** [comment]
I am getting an error while building a flutter app on android studio.
![image](https://github.com/react-native-async-storage/async-storage/assets/98742685/bc57f789-35d0-46ca-a822-dae379eb9098)

**Comment by pranayjain29** [comment]
> I am getting an error while building a flutter app on android studio. ![image](https://user-images.githubusercontent.com/98742685/268510301-bc57f789-35d0-46ca-a822-dae379eb9098.png)

My app/build.gradle code:
plugins {

    // Add the Google services Gradle plugin
    id("com.google.gms.google-services")

}

defaultConfig {
    applicationId "com.example.flutterapp"
    minSdkVersion 21
    targetSdkVersion 31
    versionCode flutterVersionCode.toInteger()
    versionName flutterVersionName
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new FileNotFoundException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}


apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"


android {
    namespace "com.example.flutterapp"
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.flutterapp"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion flutter.minSdkVersion
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:32.3.1')
    implementation 'com.google.firebase:firebase-analytics-ktx'
}

I am wanting to integrate Firebase in my app.
