### ISSUE TITLE
React Native 0.61.5 crashed whenever I install any version of AsyncStorage

### ISSUE THREAD

**Issue by nateblog** [react-native-community/async-storage#293]
## Current behavior
React Native 0.61.5 crashed whenever I install any version of AsyncStorage

## Expected behavior
It should not crash

#Device
Tested on Android

How do I sort this out? What version am I going to use? Are there any tweak I need to do?

**Comment by nateblog** [comment]
I sorted it out by manually linking the package, weird, I thought it is automatically linked. Anyways it is all okay now.

**Comment by theanhmx** [comment]
> I sorted it out by manually linking the package, weird, I thought it is automatically linked. Anyways it is all okay now.

would you mind give more detail on how to link it manually on iOS?
