### ISSUE TITLE
Async-Storage compatiblility with react-native 0.62.0-rc2?

### ISSUE THREAD

**Issue by 0x01Brain** [react-native-community/async-storage#299]
## You want to:  

I am using Async-Storage since it is required by redux-persistence. currently, I have react-native version 0.59 I would like to upgrade to 0.60+ but I am getting some errors during runtime regarding Async Storage not sure if it is a bug or something I missed during the upgrade process.
But the app compiles fine without any issues as I manually linked the library.
Is Async-Storage compabtible with react-native 0.62.0-rc2?
## Details:

The error I am having:
![image](https://user-images.githubusercontent.com/13728193/74683717-3d887300-51e3-11ea-8d44-c194f8a597d9.png)

**Comment by Krizzu** [comment]
Seems like some  "leftovers" from 0.59 are blocking auto-linking. Have you tried what error message says?

**Comment by 0x01Brain** [comment]
> Seems like some "leftovers" from 0.59 are blocking auto-linking. Have you tried what error message says?

What do you mean by "leftovers"?

**Comment by 0x01Brain** [comment]
Btw the react-native version is 0.62 cause I did the upgrade manually depending on the following git changes here:
https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.62.0-rc.2

**Comment by 0x01Brain** [comment]
@Krizzu Can you please tell me what is the problem I am having?

**Comment by tido64** [comment]
Do you have something like the following snippet in your `MainApplication`?
```java
@Override
protected List<ReactPackage> getPackages() {
    List<ReactPackage> packages = new PackageList(this).getPackages();
    packages.add(new AsyncStoragePackage());
    return packages;
}
```
If so, you've added `AsyncStoragePackage` twice. Once with auto-linking, and again manually. You should remove the latter.

**Comment by 0x01Brain** [comment]
@tido64 That was it, thank you, sir. I am closing this now.

**Comment by Krizzu** [comment]
@0x01Brain sorry, I've been off for some time.

By "leftovers" I meant code that was used pre-upgraded to link native modules. Since there's auto-linking in place in 0.60+, there's no need for that.

Happy to see that you've got it fixed :)
