### ISSUE TITLE
Data lost when using 1.8.0 with redux-persist

### ISSUE THREAD

**Issue by ouabing** [react-native-community/async-storage#300]
## Current behavior

I'm using redux-persist with AsyncStorage which will rehydrate store data on startup. After upgrading to 1.8.0, data got lost 100% on first start on iOS. The log shows `Manifest does not exist` when migrating but I dumped the container data and found the old data still live in `Documents/RCTAsyncLocalStorage_V1`.

## Expected behavior

Upgrading to 1.8.0 will migrate old data smoothly.

## Repro steps

Use a simple redux app with redux-persist can reproduce this issue.

## Environment

- **Async Storage version**: 1.8.0
- **React-Native version**: 0.61.5
- **Platform tested**: iPhone XR, iOS 13.3.1
- **Logs/Error that are relevant**: 
```
[RNCAsyncStorage.m:205] Failed to copy old storage directory to new storage directory location during migration: Error Domain=NSCocoaErrorDomain Code=4 "文件“RCTAsyncLocalStorage_V1”不存在。" UserInfo={NSSourceFilePathErrorKey=/var/mobile/Containers/Data/Application/BFCD6C74-6C53-468C-99F6-0278FA46B3E2/Documents/RCTAsyncLocalStorage_V1, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/var/mobile/Containers/Data/Application/BFCD6C74-6C53-468C-99F6-0278FA46B3E2/Library/Application Support/com.g-cores.GCGameMedia/RCTAsyncLocalStorage_V1, NSFilePath=/var/mobile/Containers/Data/Application/BFCD6C74-6C53-468C-99F6-0278FA46B3E2/Documents/RCTAsyncLocalStorage_V1, NSUnderlyingError=0x28376df80 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
2020-02-19 09:57:35.331 [tid:com.facebook.react.AsyncLocalStorageQueue][RNCAsyncStorage.m:380] Manifest does not exist - creating a new one.
```
- **AppData Info**
![image](https://user-images.githubusercontent.com/1430376/74795027-c4cb0900-52ff-11ea-85fc-ca2fdb521396.png)

**Comment by frankenthumbs** [comment]
hey @ouabing this looks like the bug i've been trying to track down.. just opened a new issue. you beat me by 30 minutes :) 
https://github.com/react-native-community/async-storage/issues/301

**Comment by ouabing** [comment]
@frankenthumbs provide a repro project, close this issue and see #301
