### ISSUE TITLE
Android - Gradle Sync Issue - Duplicate module in IML file

### ISSUE THREAD

**Issue by avinashlng1080** [react-native-community/async-storage#302]
## You want to:  Ask a question

Hello Guys,
While installing react-native-firebase and react-native-async-storage, I encountered the below issue. 
Currently, I'm deleting each duplicate module manually; but this is not ideal.
Can you please suggest me what is the best way to fix this ? 

## Details:

ERROR: The modules ['async-storage-android-@react-native-community_async-storage', 'react-native-community_async-storage'] point to the same directory in the file system.
Each module must have a unique path.

**Comment by Krizzu** [comment]
Hey @avinashlng1080 

What RN version are you using? I suspect that the AsyncStorage might be linked two times - manually and by auto-linking feature.

**Comment by avinashlng1080** [comment]
Hello @Krizzu ,
I'm on "react-native": "0.61.4",.

**Comment by Krizzu** [comment]
How does your `MainApplication.java` and `settings.gradle` look like?

**Comment by CongBaDo** [comment]
Same problem, anyone solved it?

**Comment by avinashlng1080** [comment]
It finally solved out by installing the latest android studio, updating the gradle build plugin to 3.6.0.

Optionally, I also ran npx react-native link packageName and remove the imported package from the mainapplication.java file only while leaving the path inside the setting.grDle file.

**Comment by buraksahin59** [comment]
> It finally solved out by installing the latest android studio, updating the gradle build plugin to 3.6.0.

Thank you, updating Android Studio and gradle to 3.6.1 were fixed my problem
