### ISSUE TITLE
[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null

### ISSUE THREAD

**Issue by engineertdog** [react-native-community/async-storage#304]
## Current behavior
The common AsyncStorage null exception.

## Repro steps
I'm building a small app that was initialized via Expo. I'm trying to use AsyncStorage for my redux store and for a framework. Currently, I have it working for testing using the old `react-native` module for storage. But I'm trying to make it work with the current, community, version. Steps I took are as follows:

- `npm i @react-native-community/async-storage`
- `expo eject`
- `react-native link @react-native-community/async-storage`
- `cd ios && pod install`
- `react-native run-ios`
- `expo start -c`
- Removed `npm_modules` and reinstalled.

One error I receive after running `react-native run-ios` is the following, but I have already run `pod install` in the `ios` folder, and re-running tells me that there are 54 (55) modules install (55 if I link async storage).

> error Could not find the following native modules: RNCMaskedView, react-native-netinfo, RNGestureHandler, RNReanimated, react-native-safe-area-context, RNScreens, RNSVG. Did you forget to run "pod install" ?

I've also tried referencing the native modules in the podfile, after `use_react_native!`. But that hasn't worked either
```
 require_relative '../node_modules/react-native/scripts/autolink-ios.rb'
 require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 use_react_native!
 use_native_modules!
```

Linking tells me that the module is already linked. I have also tried unlinking and running that way, same issue. Simple code I am using is as follows (looks like v2 may be a little different?):
```js
import AsyncStorage from "@react-native-community/async-storage";

// Redux Persistence Config.
const persistConfig = {
  key: config.redux.persistKey,
  storage: AsyncStorage
}
```

## Environment
- **Async Storage version**: 1.8.0
- **React-Native version**: 0.61.4
- **Platform tested**: iOS
- **Expo version**: 36.0.0

Podfile
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'pilogger' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.14.4",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true

  # Install unimodules
  require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
  use_unimodules!(
    modules_paths: ['../node_modules'],
    exclude: [
      'expo-bluetooth',
      'expo-in-app-purchases',
      'expo-payments-stripe',
    ],
  )

 # Install React Native and its dependencies
 require_relative '../node_modules/react-native/scripts/autolink-ios.rb'
 use_react_native!

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|

      if pod_name == 'ExpoKit'
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'
          
          # Enable Google Maps support
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS_UTILS=1'
          
        end
      end



      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end


      # Can't specify this in the React podspec because we need to use those podspecs for detached
      # projects which don't reference ExponentCPP.
      if pod_name.start_with?('React')
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        end
      end

      # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
      # RCT_ENABLE_PACKAGER_CONNECTION disabled
      next unless pod_name.start_with?('React')
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end

    end
  end
end
```

**Comment by micabe** [comment]
de lete Podfile.lock and reinstall

**Comment by engineertdog** [comment]
Last pod install log. However, I still receive the error on `expo start` with my iPhone.

> pod install
> Installing unimodules:
>  expo-app-loader-provider@8.0.0 from ../node_modules/expo-app-loader-provider/ios
>  expo-barcode-scanner@8.0.0 from ../node_modules/expo-barcode-scanner/ios
>  expo-camera@8.0.0 from ../node_modules/expo-camera/ios
>  expo-constants@8.0.0 from ../node_modules/expo-constants/ios
>  expo-error-recovery@1.0.0 from ../node_modules/expo-error-recovery/ios
>  expo-file-system@8.0.0 from ../node_modules/expo-file-system/ios
>  expo-font@8.0.0 from ../node_modules/expo-font/ios
>  expo-keep-awake@8.0.0 from ../node_modules/expo-keep-awake/ios
>  expo-linear-gradient@8.0.0 from ../node_modules/expo-linear-gradient/ios
>  expo-location@8.0.0 from ../node_modules/expo-location/ios
>  expo-permissions@8.0.0 from ../node_modules/expo-permissions/ios
>  expo-sqlite@8.0.0 from ../node_modules/expo-sqlite/ios
>  expo-web-browser@8.0.0 from ../node_modules/expo-web-browser/ios
>  unimodules-barcode-scanner-interface@5.0.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
>  unimodules-camera-interface@5.0.0 from ../node_modules/unimodules-camera-interface/ios
>  unimodules-constants-interface@5.0.0 from ../node_modules/unimodules-constants-interface/ios
>  unimodules-core@5.0.0 from ../node_modules/@unimodules/core/ios
>  unimodules-face-detector-interface@5.0.0 from ../node_modules/unimodules-face-detector-interface/ios
>  unimodules-file-system-interface@5.0.0 from ../node_modules/unimodules-file-system-interface/ios
>  unimodules-font-interface@5.0.0 from ../node_modules/unimodules-font-interface/ios
>  unimodules-image-loader-interface@5.0.0 from ../node_modules/unimodules-image-loader-interface/ios
>  unimodules-permissions-interface@5.0.0 from ../node_modules/unimodules-permissions-interface/ios
>  unimodules-react-native-adapter@5.0.0 from ../node_modules/@unimodules/react-native-adapter/ios
>  unimodules-sensors-interface@5.0.0 from ../node_modules/unimodules-sensors-interface/ios
>  unimodules-task-manager-interface@5.0.0 from ../node_modules/unimodules-task-manager-interface/ios
> 
> Detected React Native module pods for RNCAsyncStorage, RNCMaskedView, RNGestureHandler, RNReanimated, RNSVG, RNScreens, react-native-netinfo, and react-native-safe-area-context
> Analyzing dependencies
> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
> Pre-downloading: `ExpoKit` from `http://github.com/expo/expo.git`, tag `ios/2.14.4`
> Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> Downloading dependencies
> Installing ExpoKit 36.0.0
> Installing RNCMaskedView (0.1.5)
> Installing RNGestureHandler (1.5.6)
> Installing RNReanimated (1.4.0)
> Installing RNSVG (11.0.1)
> Installing RNScreens (2.0.0-alpha.12)
> Installing react-native-netinfo (4.6.0)
> Installing react-native-safe-area-context (0.7.3)
> Generating Pods project
> Integrating client project
> Pod installation complete! There are 62 dependencies from the Podfile and 69 total pods installed.

**Comment by Krizzu** [comment]
Hi @engineertdog ,

Since it's React Native version 0.60+, I'd keep the `use_native_module!` and remove any manually linked  pods from Podfiles.

What's the output for `react-native config` ?

**Comment by engineertdog** [comment]
I've tried both linked and unlinked. I've attached the config output since it's long.
[config.txt](https://github.com/react-native-community/async-storage/files/4245364/config.txt)

**Comment by Krizzu** [comment]
@engineertdog Can you post your `Podfile`?

**Comment by yassati** [comment]
- add this in Podfile : `pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'` 
- cd ios && pod install

**Comment by miuel** [comment]
Hi, I have the same error but with CLI. 
Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.
I followed all the steps recommended after error:
To fix this issue try these steps:
  • Run `react-native link @react-native-community/async-storage` in the project root.
  • Rebuild and restart the app.
  • Run the packager with `--clearCache` flag.
  • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

Error still happened
react-native-cli: 2.0.1
ios env

any other solution?
 Thanks, in advance

**Comment by engineertdog** [comment]
I've deleted the iOS folder, re-ejected, reinstalled, and it still doesn't work.

`source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'pilogger' do
  pod 'ExpoKit',
    :git => "http://github.com/expo/expo.git",
    :tag => "ios/2.14.4",
    :subspecs => [
      "Core"
    ],
    :inhibit_warnings => true

  # Install unimodules
  require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
  use_unimodules!(
    modules_paths: ['../node_modules'],
    exclude: [
      'expo-bluetooth',
      'expo-in-app-purchases',
      'expo-payments-stripe',
    ],
  )

 # Install React Native and its dependencies
 require_relative '../node_modules/react-native/scripts/autolink-ios.rb'
 use_react_native!

 pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  post_install do |installer|
    installer.pods_project.main_group.tab_width = '2';
    installer.pods_project.main_group.indent_width = '2';

    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|

      if pod_name == 'ExpoKit'
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'EX_DETACHED=1'

          # Enable Google Maps support
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS_UTILS=1'

        end
      end



      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end


      # Can't specify this in the React podspec because we need to use those podspecs for detached
      # projects which don't reference ExponentCPP.
      if pod_name.start_with?('React')
        target_installation_result.native_target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
          config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        end
      end

      # Build React Native with RCT_DEV enabled and RCT_ENABLE_INSPECTOR and
      # RCT_ENABLE_PACKAGER_CONNECTION disabled
      next unless pod_name.start_with?('React')
      target_installation_result.native_target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_DEV=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end

    end
  end
end
`

**Comment by nuyunhai** [comment]
I have the same error in my andoid project. The version of react native is 0.60.6.I have  tried to link ,but failed.Here is  my package.json。

`{
  "name": "ExpenseManager",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "ios": "node node_modules/react-native/local-cli/cli.js run-ios",
    "android": "node node_modules/react-native/local-cli/cli.js run-android"
  },
  "dependencies": {
    "react": "^16.8.6",
    "react-native": "^0.60.6"
  }
}`
and  here is my application:

`public class CloudpenseApplication extends Application implements ReactApplication {

    private static CloudpenseApplication _instance;

    public static int[] scrennSize = new int[2];

    public static CloudpenseApplication getInstance() {
        return _instance;
    }

    @Override protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, false);
    }

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
            //注意：BuildConfig需要导入自己项目包名下的BuildConfig
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new MyReactPackage()
            );

        }
    };

}`

**Comment by gwumkt** [comment]
im having the same issue with native one..
`import { AsyncStorage } from 'react-native';
import log from './log';

export default class LocalStorage {
	static async getItem(key) {
		try {
			const value = await AsyncStorage.getItem(key);
			try { return JSON.parse(value); } catch (e) { return value; }
		} catch (e) {
			log.err('LocalStorage getItem', e);
			return null;
		}
	}`

![image](https://user-images.githubusercontent.com/28900951/79155832-735c6900-7dda-11ea-908f-bf7837f4aded.png)

**Comment by tfeijo** [comment]
Try import from 'react-native', like:
import AsyncStorage from "react-native";

**Comment by leotm** [comment]
Just had this too but with a varying setup:

<img width="379" alt="Screenshot 2020-04-19 at 12 45 59" src="https://user-images.githubusercontent.com/1881059/79686929-c0599880-823b-11ea-8560-beb6722078ad.png">

Xcode was failing to build on `Assume.cpp` unable to `#include <glog/logging.h>`.

Turned out I'd assumed my previous `pod install` was successful before closing the terminal pane, but it had failed.

Now it's working autolinked and generated the appropriate `Podfile.lock`

---

- **Async Storage version**: 1.9.0
- **React-Native version**: 0.62.2
- RN Community RN TS template: 6.4.4

**Comment by idanavs** [comment]
Can you share you Podfile.lock?
Because it updated mine successfully but still not working

**Comment by leotm** [comment]
@idanavs Sure: https://gist.github.com/leotm/330ba353425e485043f3522d31850789

**Comment by idanavs** [comment]
i have the same thing.. but still not working..

**Comment by ZimmermannLeon** [comment]
Hi, 
have the same Error on Android and IOS...

Async Storage version: 1.9.0
React-Native version: 0.62.2

**Comment by gwumkt** [comment]
@ZimmermannLeon your using expo? ejected or not?

**Comment by ZimmermannLeon** [comment]
@gwumkt yes i using expo and i have ejected it first. It also linked successfully but still get the error.

**Comment by gwumkt** [comment]
i created now new project, and i put all the files + npm i, then i ejected the app and pod install and it seems to be ok for now..
i will update if its working on the device itself. but for now the simulator is working..cd ios

**Comment by gwumkt** [comment]
Nope, not working on the device.. only on the simulator

**Comment by LukasChiama** [comment]
I'm using expo and I have the same issue

**Comment by gwumkt** [comment]
i gave up and now im using the AsyncStorage of react-native..
i have issue before but now its working somehow

**Comment by ZimmermannLeon** [comment]
@gwumkt thats my solution too ;)

**Comment by alfredzh** [comment]
Same here!

When I use
```
import { AsyncStorage } from 'react-native';
```

It works fine, but with warning!
￼
![1587959959617](https://user-images.githubusercontent.com/3643340/80332827-8feaad80-887e-11ea-91b6-7a66b1ff26b9.jpg)

Then I follow this, changed import to
```
import AsyncStorage from '@react-native-community/async-storage';
```

It's dead!

![1587959951721](https://user-images.githubusercontent.com/3643340/80332887-c0324c00-887e-11ea-9264-72c26df1703d.jpg)

I'm confused!

**Comment by Krizzu** [comment]
You get that error because the Async Storage from Community has to be linked (either manually or auto-linking). 

- With RN 0.60+, auto linking works for project that did not change any native code (out of the box).
- If you added Async Storage recently, you need to re-run `react-native run-android`, to make RN aware of new native module
- If you've changed any Native code (like `MainApplication.java`) you need to link this package manually.

**Comment by rpweb** [comment]
Expo still needs in SDK 37 (Didn't check 36):
```import { AsyncStorage } from 'react-native';```
but at the same time ```import NetInfo from "@react-native-community/netinfo";```
Following setup works for me:
```
"expo": "37.0.8",
"@redux-offline/redux-offline": "https://github.com/webstudios/redux-offline/raw/2.5.2-native.3-expo37/redux-offline-redux-offline-v2.5.2-native.3.tgz",
```

My @redux-offline/redux-offline version is only for temporary usage!

**Comment by doteric** [comment]
I'm taking a guess that the author already solved this, but for people searching a solution:  
  
You shouldn't have to link in react-native >=0.6.  
I had the same issue, but it was just that I didn't run `react-native run-android`. I compiled in android studio only. Running `react-native run-android` and then rebuilding in android studio should solve this.  
  
Take a read on this: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

**Comment by engineertdog** [comment]
I did not solve the issue. None of the answers provided have done anything to fix it. I'll be developing with Quasar from here on out.

**Comment by chuhemiao** [comment]
@engineertdog re-compile your app

**Comment by Krizzu** [comment]
I did summary here:
https://github.com/react-native-community/async-storage/issues/304#issuecomment-619798943

I can help to get this up and running, but I need more info about setup (if it's custom, or react native from CLI etc.).

I'm closing this down - Please let me know if needed.

**Comment by ahtevus** [comment]
I had  faced the same issue, but none of the React Native Expert solutions have worked so far - simply frustrated with using RN, i am facing hell of issue building my startup - this is the shittiest language ever developed.

**Comment by tuanngocptn** [comment]
I have the same issue and I deal with it after.
- remove the app in the Ios simulator
- run `npm start --reset-cache`
- reinstall app with `react-native run-ios`
the problem solved.

**Comment by RobinBobin** [comment]
I had the same problem. My scenario was that my app was using my package, that was using AsyncStorage. AsyncStorage was specified as a dependency of that my package and looks like the building system couldn't understand it should use AsyncStorage while building the app. When I specified AsyncStorage in my app's package.json everything worked.

**Comment by karlmarxlopez** [comment]
> I had faced the same issue, but none of the React Native Expert solutions have worked so far - simply frustrated with using RN, i am facing hell of issue building my startup - this is the shittiest language ever developed.

@ahtevus 

React Native is not a programming language. 

Stay away from `expo` if you don't want headaches, just use the bare react native setup, using `react-native-cli`. I'm also experiencing this issue, but I'm telling the client to ditch expo in favor of the bare react-native cli generated project.

**Comment by truetechcode** [comment]
I had the same issue, was able to get it working by following this:
`@react-native-community/async-storage has been renamed. To upgrade:
- remove @react-native-community/async-storage from package.json
- run "expo install @react-native-async-storage/async-storage"
- update your imports manually, or run "npx expo-codemod sdk41-async-storage './**/*'".`

**Comment by denvinnpaolo** [comment]
> I had the same issue, was able to get it working by following this:
> 
> ```
> @react-native-community/async-storage has been renamed. To upgrade:
> - remove @react-native-community/async-storage from package.json
> - run "expo install @react-native-async-storage/async-storage"
> - update your imports manually, or run "npx expo-codemod sdk41-async-storage './**/*'".
> ```

Got it to work! Thank you!

**Comment by kodejuice** [comment]
Just got this issue, it gave the error on my physical device but not on my emulator, so i uninstalled from my device and renistalled then it went away.

**Comment by davelamichhane** [comment]
1. using react-native-cli and not expo
2. been using my android phone and not emulators
3. removed the ios folder, _tests folder to narrow down the problem
4. i get this error when i call the Auth from aws-amplify. I installed @react-native-async-storage/async-storage as a dependency while installing aws-amplify
5. tried resetting the cache, rebuilt the app 100 times, but nothing's work. 
Can someone point me in the right direction?
