### ISSUE TITLE
NativeModule: AsyncStorage is null

### ISSUE THREAD

**Issue by Shair17** [react-native-community/async-storage#307]
My current:
MacBook Air,
App for iOS

I think you know this.

![Captura de Pantalla 2020-02-26 a la(s) 20 55 43](https://user-images.githubusercontent.com/18153674/75405032-68a54d80-58da-11ea-8b47-270ce74b304b.png)

I had linked the modules, and tried with --reset-cache, but it doesn't work for me.

**Comment by Krizzu** [comment]
Please provide more info like RN version, `Podfile` or anything that would help to track this down.

**Comment by Shair17** [comment]
React Native version is the latest

**Comment by danieldecsi** [comment]
Are you using Expo? I tried to use this package inside of an Expo project but it looks like it's not supported yet, so I ended up importing AsyncStorage directly from React Native for now.

**Comment by Shair17** [comment]
No, i am not using expo. I was using React Native cli

**Comment by filipemelo2002** [comment]
Same problem here. My project is Expo managed. Any alternative so far?

**Comment by Shair17** [comment]
@filipemelo2002 this project **React Native Async Storage** doesn't work for expo, only react native cli.

**Comment by Shair17** [comment]
@Krizzu Can you help me? I just need these commands, I am using MacBook, also React Native (NOT EXPO).

I do:
first:  `react-native link @react-native-community/async-storage` (although I am using react native> 0.60 I did this, since this does it automatically as I understand it.)
second: `as I understand the rebuild and restart the application is to close everything and run it again.` (If I am wrong, please give me a solution)
third: How it's supposed to execute `--clearCache` flag? (I don't know, lol)
Finally: i run `pod install` into `ios` directory, but it doesn't work for me.

**Comment by Krizzu** [comment]
@Shair17 
you don't have to run `react-native link`, because there's auto-linking in place. Rebuild and reinstall means to either use IDE (Xcode/Android studio) to run build and run your app again or use `react-native run-android/run-ios` to do so.
For CocoaPods, [here's a link to getting started page](https://guides.cocoapods.org/using/getting-started.html)

**Comment by Shair17** [comment]
@Krizzu Thank you, I'll do it later, I don't have access right now.

**Comment by Shair17** [comment]
I've fix.
1: Run `yarn add @react-native-community/async-storage`.
2: Go to ios folder, then run, `pod install` (only if you're using cocoapods) => `cd ios && pod install && cd ..`
3: I dont knew why it doesn't work for me last tame, I think you should take a coffee and try it again.

**Comment by Krizzu** [comment]
Glad you have it fixed :)

**Comment by BruceSuperProgramer** [comment]
I am able to solve it after deleting the app from ios simulator and install it again after pods re-installed. And start app from XCode workspace
