### ISSUE TITLE
Using async storage without return promise

### ISSUE THREAD

**Issue by duongkhoangiam** [react-native-community/async-storage#308]
I have using AsyncStorage with redux initial state
my question is how to return value without promise
Here is my code 
```
const getStorageData = async state => {
  try {
    const value = await AsyncStorage.getItem('setting');
    if (value !== null) {
      return await JSON.parse(value);
    }
  } catch (error) {}
  return state;
};

```

```
const defaultState = {
  locale: 'en',
  language: [
    { key: 'en', text: 'English' },
    { key: 'ar', text: 'Arabic' }
  ]
};
```

initialState
```
const initialState = { 
  setting: getStorageData(defaultState)
};
```
the return value is Promise Object , i need return value is raw Object
i need return initState without Promise.

**Comment by Krizzu** [comment]
In your `initialState` you have to await `getStorageData` - that function returns Promise.

**Comment by duongkhoangiam** [comment]
Can you explain @Krizzu

**Comment by Krizzu** [comment]
@duongkhoangiam 
```
const initialState = { 
  setting: await getStorageData(defaultState) // you need to await for the value, since `getStorageData` is async
};
```

**Comment by duongkhoangiam** [comment]
How to using await inside async @Krizzu 
'await' expression is only allowed within an async function.

**Comment by xdlgj** [comment]
I have the same problem

**Comment by shivansal** [comment]
Any progress on this?

**Comment by Krizzu** [comment]
`AsyncStorage` is by nature asynchronous, so you can either use Promise or Callback to retrieve/save value. 
[Here's API doc with example on how to use it](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/API.md)

**Comment by Krizzu** [comment]
If you have more question please post them here. Closing for now.

**Comment by anhquan291** [comment]
Hi Krizzu,

> `AsyncStorage` is by nature asynchronous, so you can either use Promise or Callback to retrieve/save value.
> [Here's API doc with example on how to use it](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/API.md)

Hi Krizzu, the link is dead. Could you please give me an example about this one?
```
const initialState = { 
  setting: await getStorageData(defaultState) // you need to await for the value, since `getStorageData` is async
}; 
```
Thank you so much

**Comment by Krizzu** [comment]
Here's the link [to the API](https://react-native-async-storage.github.io/async-storage/docs/api)

**Comment by kenny15335** [comment]
Having the same issues @Krizzu

**Comment by Krizzu** [comment]
@kenny15335 I'd need more details, like code snippets, to help you out
