### ISSUE TITLE
[AsyncStorage] Using undefined type for key is not supported.

### ISSUE THREAD

**Issue by farbexot** [react-native-community/async-storage#318]
## Current behavior

I'm using AsyncStorage to store some strings. I'm connected with my iPad and getting this warning in the Metro Bundler console.

[AsyncStorage] Using undefined type for key is not supported. This can lead to unexpected behavior/errors. Use string instead.
Key passed: undefined

Wierdly I'm only getting those on my iPad, not on my iOS simulator.

## Expected behavior

Everything seems to work. Just want to understand where it comes from?

## Environment

- **Async Storage version**: 1.8.1
- **React-Native version**: 61.5
- **Platform tested**: iOS

**Comment by farbexot** [comment]
![IMG_0008](https://user-images.githubusercontent.com/10153413/77583183-ef9d1400-6ee0-11ea-954b-80c0a6030756.PNG)

I'm also getting this error alongside, but only on iPad again. I felt like it was about some entries that were in my manifest.json prior. so i wiped it with .clear() but the problem persits.

I found this thread: https://github.com/facebook/react-native/issues/9743 
which describes the same issue with AsyncStorage. They provided a solution but it didnt help me to fix my problem.

**Comment by Krizzu** [comment]
Hi @farbexot ,

Can you provide some repro steps?

**Comment by farbexot** [comment]
Hi Krizzu,

yes I found the problem. I am using items from a FlatList and have a function that fills up the rows in order to maintain proper layout. The renderItem calls AsyncStorage.getItem() and here the name of the items were undefined as they came from the pesudo-items.

I just added ` if(item !== undefined) ` before getItem()

Thanks for your help!
