### ISSUE TITLE
@react-native-community/async-storage does not work on IOS

### ISSUE THREAD

**Issue by hamoody-omar** [react-native-community/async-storage#319]
@react-native-community/async-storage does not work on IOS simulator. I have linked and unlinked many times, cleared the cache and installed the pods and still doesn't work. it works on my android emulator but not the IOS simulator.

<img width="438" alt="Screen Shot 2020-03-27 at 7 35 46 PM" src="https://user-images.githubusercontent.com/32809064/77808552-29e1ef00-7062-11ea-8a24-a95f089b0a6c.png">

**Comment by Krizzu** [comment]
Hey,

We have [troubleshooting guide](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Troubleshooting.md) that might come in handy.

Also, please provide basic info like RN version, AS version.

**Comment by hamoody-omar** [comment]
@Krizzu 
"@react-native-community/async-storage": "^1.8.1",
"react": "16.9.0",
"react-native": "0.61.5",

I followed the troubleshooting guide and I can see that my @react-native-community/async-storage is linked and also updated the pod RNCAsyncStorage and still does not work.

**Comment by maendamedia** [comment]
Had same issue. After adding the pod and run pod install and pod update RNCAsyncStorage it worked like a charm

**Comment by Krizzu** [comment]
> I followed the troubleshooting guide and I can see that my @react-native-community/async-storage is linked and also updated the pod RNCAsyncStorage and still does not work.

Just to clarify: With React Native 0.60+, you don't link projects anymore - it's done on builds phase for you. You just need to add script link to `Podfile`.

If you happen to still get an error, please let me know.
