### ISSUE TITLE
Crash when get large items

### ISSUE THREAD

**Issue by WQvist** [react-native-community/async-storage#322]
## Current behavior

I'm saving an array with 1000 values in one single key/value. When I get it, the phone freezes and the app crashes.
Same thing happen if I divide the array into multiple smaller ones and save multiple key/values.
I have no problem setting/getting smaller, simpler things.

## Expected behavior

It should fetch without a problem.

## Repro steps
In code below, I get "fetch complete" in the console, but never "getOld complete". That's when it freezes.
```
saveLogToDevice = async () => {
	try {
		await AsyncStorage.setItem(device.name, JSON.stringify(this.outputArray))
		
	} catch (e) {
		console.log(e)
	}
	console.log("data saved")
}

getOldLog = async () => {
	try {
		const value = await AsyncStorage.getItem(device.name)
		if(value !== null) {
			this.outputArray = JSON.parse(value)
			console.log("fetch complete")
		} else{
			console.log("No old log found")
		}
	} catch(e) {
		console.log(e)
	}
	console.log("getOld complete")
}
```

## Environment

- **Async Storage version**: LEGACY
- **React-Native version**: "0.61.5"
- **Platform tested**: Android
- **Logs/Error that are relevant**: Nothing that I can find via logcat. Just says that the system has died.

**Comment by Krizzu** [comment]
If you see `console.log("fetch complete")` it means it has done parsing, right? Is there something happening before `getOld complete` ?

**Comment by Krizzu** [comment]
If you need help, please do let me know. Closing this issue for now.
