### ISSUE TITLE
Backward compatibility with legacy native module from React Native

### ISSUE THREAD

**Issue by allenhsu** [react-native-community/async-storage#323]
## You want to:  
Discuss something

## Details:
I noticed that this standalone module is only checking native module registered under:
```
const RCTAsyncStorage =
  NativeModules.PlatformLocalStorage || // Support for external modules, like react-native-windows
  NativeModules.RNC_AsyncSQLiteDBStorage ||
  NativeModules.RNCAsyncStorage;
```
But the legacy module is registered under `NativeModules.AsyncLocalStorage`.

I checked most APIs and think they are compatible. So why not checking `NativeModules.AsyncLocalStorage` as well for better backward compatibility?

For now, to move to this standalone package, we have to upgrade client to support it. So we cannot push the update to older clients.

**Comment by Krizzu** [comment]
Hello,

Async Storage was separate from React Native's core to this Community's package. It's compatible with "legacy" Async Storage, so you should be able to upgrade.

**Comment by allenhsu** [comment]
Hi @Krizzu Thanks for the quick response. By compatible, do you mean no change of JS API, or it's compatible with `RCTAsyncLocalStorage` from `React/Core` without linking this repo?

**Comment by Krizzu** [comment]
@allenhsu 
You'll have to install this repo and linking would be done automatically (thanks to auto-linking in RN 0.60+).
Then use this library as you normally would use AsyncStorage (you just need to change import statement)

**Comment by allenhsu** [comment]
@Krizzu If the native protocol of this repo and `RCTAsyncLocalStorage` from `React/Core` are actually same, can we change it to:

```
const RCTAsyncStorage =
  NativeModules.PlatformLocalStorage || // Support for external modules, like react-native-windows
  NativeModules.RNC_AsyncSQLiteDBStorage ||
  NativeModules.RNCAsyncStorage ||
  NativeModules.AsyncLocalStorage;
```

To make it compatible with client that has not been linked with this repo? Because we have hot patch solution, we hope every new update can reach as many users as possible.

**Comment by Krizzu** [comment]
They're the same when it comes to the API, but Community's `AsyncStorage` has some features and fixes in place, so its "ahead" of Core's `AsyncStorage`, which is deprecated.

**Comment by allenhsu** [comment]
Yea. We would absolutely link with the new repo to adopt the latest changes and fixes. But if there's no breaking change to the API of the native module, I still think it a good idea to support the Core's `AsyncStorage` since it's just deprecated but not removed yet.

But it's also understandable if it cannot be added to this repo, to entirely decouple from the old module. If so, I think we can add it by maintaining our own fork or patching it with some post install script.

**Comment by Krizzu** [comment]
If that works for you, then of yeah, go ahead.
