### ISSUE TITLE
Can't build Android app after npm audit fix

### ISSUE THREAD

**Issue by martonbognar** [react-native-community/async-storage#325]
## Current behavior

Running `npx react-native run-android` throws an error.

## Expected behavior

The command should succeed.

## Repro steps

My repository is available at https://github.com/martonbognar/safedrunk-app/ but I don't think there is anything special about it. After running `npm audit fix`, I am now unable to build my app.

## Environment

- **Async Storage version**: "^1.9.0"
- **React-Native version**: "^0.62.1"
- **Platform tested**: Android
- **Logs/Error that are relevant**: 

When running `npx react-native run-android`, it gives the error:

```
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Path '/home/mici/programming/bali-app/node_modules/@react-native-community/async-storage/android/build/intermediates/compiled_local_resources/debug/out' is not a readable directory.
```

Which makes sense, the `intermediates` directory does not contain that directory.

When trying `./gradlew clean build --scan`, I get:

```
> Task :app:packageDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.lang.OutOfMemoryError (no error message)
```

I tried deleting the `node_modules` and the `android/app/build` directories and reinstalling, but it didn't help.

**Comment by Krizzu** [comment]
It seems like you need to increase memory for the wrapper.
What gradle wrapper version are you using?

**Comment by martonbognar** [comment]
I'll be honest, since posting this issue I've tried many things, and as a result I now get a different error message, related to a different module, so it's possible that the original issue wasn't in this repository, it just manifested this way for some reason. I really hate this whole ecosystem...

Since I can't reproduce the issue now, I'll just close the issue, at least if someone else experiences a similar problem, they have this issue to find now.

**Comment by mxs** [comment]
The following post helped me fix this issue https://github.com/oblador/react-native-vector-icons/issues/1142#issuecomment-611375415

```
rm -rf android/.gradle
rm -rf .gradle
rm -rf ~/.gradle
./gradlew clean
```
