### ISSUE TITLE
use item value in the native code

### ISSUE THREAD

**Issue by hanaechahid** [react-native-community/async-storage#326]
## You want to:  

Hello, I want to use an item value in the native code android and ios, that I have saved in the local storage with async storage.

is that possible? if yes, how can I do it?

thank you

**Comment by Krizzu** [comment]
Hey @hanaechahid ,

We have [brownfield integration docs here](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/advanced/BrownfieldIntegration.md). It's only covered by iOS platform, on Android we did not explore this possibility yet.

**Comment by Krizzu** [comment]
If you have further questions, please re-open.

**Comment by DevArenaCN** [comment]
@Krizzu Hi, so I have a question on my implementation. I would like to have the native side to read/write the AsyncStorage, I think there's a way to achieve that without  using delegate (https://github.com/react-native-community/async-storage/issues/80#issuecomment-483223913). The question is if the bridge is dead (js thread got killed when app is in bg) would this still work? I'm assuming this would only work with a valid js thread right?
If I'd go with delegate, I would just need to implement all the interfaces in RNCAsyncStorageDelegate.h or I'd need to handle the entire operation myself (creating storage, etc.)

**Comment by Krizzu** [comment]
No, because those native modules are singleton and live on native side, they're not bound to JS thread. You can think of JS only uses this like you'd do from other native part.
