### ISSUE TITLE
Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null in android windows

### ISSUE THREAD

**Issue by Vicky-SilverSky** [react-native-community/async-storage#337]
## Details:

Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null in android windows in react-native version 61.5
AsyncStorage version "^1.8.1"

**Comment by Krizzu** [comment]
Hey,

I need more details. Did you restart your app with `react-native run-android`? Note: RN 0.61 does not need to be linked by `react-native link`

**Comment by Vicky-SilverSky** [comment]
> Hey,
> 
> I need more details. Did you restart your app with `react-native run-android`? Note: RN 0.61 does not need to be linked by `react-native link`

yes i have restart project with react-native run-android and uninstalled previous version app and i've   not linked as RN .60 >= no need to linking

**Comment by AleksandarSimikic** [comment]
Same problem. 0.59 RN, i linked everything, imported and added in MainApp.java but still have same error. Tried to rebuild, same.

**Comment by Vicky-SilverSky** [comment]
> Same problem. 0.59 RN, i linked everything, imported and added in MainApp.java but still have same error. Tried to rebuild, same.

can you  please upload screenshots of required files..

**Comment by Krizzu** [comment]
How are other native modules handled in your project? Are they auto-linked? Is your `Application.java` different than default one? I know Wix navigation requires to change that file, so auto-linking cannot work.

**Comment by Vicky-SilverSky** [comment]
> How are other native modules handled in your project? Are they auto-linked? Is your `Application.java` different than default one? I know Wix navigation requires to change that file, so auto-linking cannot work.

No, i've to manually link for most of libraries

**Comment by Krizzu** [comment]
So it means you have to manually link Async Storage too. With auto-linking, it's all or nothing

**Comment by Vicky-SilverSky** [comment]
> h auto-linking, it's all or nothing

how i able to use all the libraries without linking, means How i change the Wix navigation as you told previously that it requires to change

**Comment by Krizzu** [comment]
If you use Wix navigation, you have to manually link the native modules (including Async Storage), because `MainApplication.java` is changed.

**Comment by Vicky-SilverSky** [comment]
> If you use Wix navigation, you have to manually link the native modules (including Async Storage), because `MainApplication.java` is changed.

Ok Thanks for your positive reply. 👍
