### ISSUE TITLE
Throwing unexpected  token error when trying to use with react native web

### ISSUE THREAD

**Issue by ajitdas123** [react-native-community/async-storage#339]
For a fresh project with react native web, when i am trying to run it on the website it's throwing an error saying unexpected token. However the same working fine on android device. A snapshot of the error has been attached with this thread.

## Expected behavior

It should run the same as on the android devices.

## Environment

- **Async Storage version**:^1.9.0
- **React-Native version**: ^0.61.5
- **React native web version**: 1.0.0-alpha.9
- **Platform tested**:web

![Screenshot 2020-04-21 at 4 39 10 PMsadasd](https://user-images.githubusercontent.com/20204881/79859795-2fc3b980-83ef-11ea-85c1-37a565722464.jpg)

**Comment by Krizzu** [comment]
Is pipeline different for RN windows? This looks like Flow is not supported

**Comment by ajitdas123** [comment]
Pipeline? Sorry I do not understand what you mean

**Comment by Krizzu** [comment]
I'm asking if your build for React Native Web has babel preset that parses Flow. From the code you posted, it looks like it does not. Can you provide some repro steps for me, so I could have a look?

**Comment by nickfujita** [comment]
I am seeing the same. We are using Typescript in our project, and not Flow, so would expect output files consumed by web to be in pure JS, rather than Flow. Would it be possible to have the output file for web not use flow syntax?

**Comment by ajitdas123** [comment]
@Krizzu  I haven't set anything. I just created a react project with create react app as per the documentation of react-native-web. Then I added the packages. Here is the code of `App.js`

Online Link of the same code base here: [Link Here](https://stackblitz.com/edit/react-jxnjjk)

```
import React, {Component} from 'react';
import logo from './logo.svg';
import './App.css';
import AsyncStorage from '@react-native-community/async-storage';
import {View,Text,Image} from 'react-native';

export default class App extends Component {
    componentDidMount() {
        AsyncStorage.setItem('app', 'Testing Application').then(response => {
            console.log('Storage Response', response)
        });
    }


    render() {
        return (
                <View style={{flex:1,justifyContent:'center',alignItems:'center'}}>
                    <Image source={logo} style={{height:100,width:200}}/>
                    <Text>React native web project</Text>
                </View>
        )
    }
}
```

**Comment by Krizzu** [comment]
I'm addressing the issue in #351
