### ISSUE TITLE
getItem & setItem is not available

### ISSUE THREAD

**Issue by kesireddy27** [react-native-community/async-storage#340]
## Current behavior
AsyncStorage in react-native has getItem & setItem methods that is working good.
Its not working after migrating to this repository.

As per the documentation in "README", after migrating to this repository, above mentioned methods are not available and so not working

## Expected behavior
Update the documentation.

**Comment by Krizzu** [comment]
Both Async Storage version have the same API. Can you be more specific ?

**Comment by sebber** [comment]
I accidentally ran upon the same issue, but it had to do that I was looking at multiple documentated usages, one using the old API directly from react native core.

The old api was documented as importing like:
`import { AsyncStorage } from 'react-native';`

while using this library you import the default insteadl, like this:
`import AsyncStorage from '@react-native-community/async-storage';`

**Comment by Krizzu** [comment]
If more issue arise, please reopen with more details, thanks
