### ISSUE TITLE
Issue with react native web

### ISSUE THREAD

**Issue by jamal-rahimzadegan** [react-native-community/async-storage#341]
./node_modules/@react-native-community/async-storage/lib/AsyncStorage.web.js
SyntaxError: C:\Users\Jamal\Desktop\rahnamapwa\node_modules@react-native-community\async-storage\lib\AsyncStorage.web.js: Unexpected token, expected ";" (21:42)

19 | };
20 |

21 | const createPromise = (getValue, callback): Promise<*> => {
| ^
22 | return new Promise((resolve, reject) => {
23 | try {
24 | const value = getValue();

**Comment by jamal-rahimzadegan** [comment]
`./node_modules/@react-native-community/async-storage/lib/AsyncStorage.web.js
SyntaxError: C:\Users\Jamal\Desktop\rahnamapwa\node_modules\@react-native-community\async-storage\lib\AsyncStorage.web.js: Unexpected token, expected ";" (21:42)

  19 | };
  20 | 
> 21 | const createPromise = (getValue, callback): Promise<*> => {
     |                                           ^
  22 |   return new Promise((resolve, reject) => {
  23 |     try {
  24 |       const value = getValue();`

**Comment by jamal-rahimzadegan** [comment]
./node_modules/@react-native-community/async-storage/lib/AsyncStorage.web.js
SyntaxError: C:\Users\Jamal\Desktop\rahnamapwa\node_modules\@react-native-community\async-storage\lib\AsyncStorage.web.js: Unexpected token, expected ";" (21:42)

  19 | };
  20 | 
> 21 | const createPromise = (getValue, callback): Promise<*> => {
     |                                           ^
  22 |   return new Promise((resolve, reject) => {
  23 |     try {
  24 |       const value = getValue();

**Comment by AlvSovereign** [comment]
To chime in, AsyncStorage is not an api for the DOM. You'll need to use `window.localStorage`.

**Comment by Krizzu** [comment]
@jamal-rahimzadegan I'm addressing the issue in #351 

@AlvSovereign AsyncStorage supports Web

**Comment by jamal-rahimzadegan** [comment]
I solved it by importing AsyncStorage from react native web (version: 0.11.7)
