### ISSUE TITLE
Return object object AsyncStorage

### ISSUE THREAD

**Issue by Rapprogtrain** [react-native-community/async-storage#344]
## Details:

Hello. I am trying to get data from AsyncStorage, but it returns object object, how I can return data normally? If i return data in console.log() all is ok, but when I call function it returns object object.

`const getTheme = async () => {
try {
const value = await AsyncStorage.getItem('theme');
console.log(value); // returns dark
return JSON.stringify(value)
} catch (error) {
alert(error)
}
};

alert(getTheme()) // [object, object]

const TabNavigator = createBottomTabNavigator(
{
Home: {
screen: Home,
navigationOptions: ({ navigation }) => ({
tabBarLabel: "Home",
tabBarVisible: getActiveRoute(navigation.state) !== "ArticleScreen",
tabBarIcon: ({ tintColor }) => (

)
})
},

Courses: {
  screen: Courses,
  navigationOptions: {
    tabBarLabel: "Courses",
    tabBarIcon: ({ tintColor }) => (
      <Icon name="ios-school" color={tintColor} size={24} />
    )
  }
}
},
{}
)

export default createAppContainer(TabNavigator);

class App extends React.Component {
render() {
return ;
}
}`

**Comment by Krizzu** [comment]
Maybe avoid doing `return JSON.stringify(value)` ?

**Comment by Rapprogtrain** [comment]
> Maybe avoid doing `return JSON.stringify(value)` ?

but how can i get value outside of the function??

**Comment by Krizzu** [comment]
I meant to drop `JSON.stringify` call.

**Comment by Rapprogtrain** [comment]
> I meant to drop `JSON.stringify` call.

return object object

**Comment by Krizzu** [comment]
Can you do:
```
return value;
```

**Comment by Rapprogtrain** [comment]
> Can you do:
> 
> ```
> return value;
> ```

yes, and when I call function it returns object object

**Comment by Krizzu** [comment]
If you're passing an object to `alert`, it'll be displayed as `[object Object]`.

Closing as this is not related to Async Storage. You can ask similar questions on [Stackoverflow tagged as `react-native`](https://stackoverflow.com/questions/tagged/react-native)
