### ISSUE TITLE
Legacy or v2 for a new app?

### ISSUE THREAD

**Issue by Guuz** [react-native-community/async-storage#345]
@Krizzu Or anyone else that knows:

### Should we use 1.9.0 or 2.0.0-rc.3 for a new project?

In https://github.com/react-native-community/async-storage/issues/113#issuecomment-612645670 you mention you'll be less active for v2. Is v2 in general less active? Is it considered final? I see more development on the v1 than the v2 branch.

What is the recommendation for new projects to use?

**Comment by Krizzu** [comment]
v1 (`master`) - the production version of Async Storage.
Consider v2 as a side try-project, which has not been tested throughly. `Legacy` backend is indeed v1 underneath.

> Is v2 in general less active?

I'm open for discussions/PRs, it's just that when I can, I spend time on v1.

> What is the recommendation for new projects to use?

v1 is more likely to have bug fixes quicker than on v2 now, so I'd say go with former.

**Comment by Guuz** [comment]
Thanks for the quick response! Sounds like v1 is the better option for now. We'll go with that!
