### ISSUE TITLE
No podspec found for `RNCAsyncStorage` in `../node_modules/@react-native-community/async-storage`

### ISSUE THREAD

**Issue by eddyoc** [react-native-community/async-storage#346]
> yarn add @react-native-community/async-storage

Installation is successful and my package.json looks like this

> "@react-native-community/async-storage": "^2.0.0-rc.3"

However when I try
> cd ios && pod install

I see

> [!] No podspec found for `RNCAsyncStorage` in `../node_modules/@react-native-community/async-storage`
## Expected behavior

Expected pod install to produce no error

## Environment

- **Async Storage version**: ^2.0.0-rc.3
- **React-Native version**: 0.61.5
- **Platform tested**: n/a
- **Logs/Error that are relevant**: included above

**Comment by Krizzu** [comment]
You need to add [Legacy storage](https://github.com/react-native-community/async-storage/blob/v2/packages/storage-legacy/README.md) and it'll be linked there
