### ISSUE TITLE
Gradle error: react-native-community_async-storage:checkDebugManifest'.

### ISSUE THREAD

**Issue by zulkufadsiz** [react-native-community/async-storage#347]
## Current behavior

Hello. When I bundle app in react-native  I got this error 
:react-native-community_async-storage:checkDebugManifest'.
    "react": "16.11.0",
    "react-native": "0.62.2"

## Expected behavior

I am using tensorflow in react native and how can i fix this issue.

## Environment

- **Async Storage version**: 
- **React-Native version**: 
- **Platform tested**: 
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Hi, I don't see any error messages. Can you provide more details?

**Comment by zulkufadsiz** [comment]
@Krizzu  I updated last version and issue resolved.
