### ISSUE TITLE
Use async storage in jest and not react native project

### ISSUE THREAD

**Issue by E-RROR** [react-native-community/async-storage#352]
Hi, i'm developing a schematic storage for react native [https://github.com/E-RROR/pleex](https://github.com/E-RROR/pleex) wrapped on async storage.
i need to call async storage and setItem and ....
but when install it with npm i --save-dev ...... i can't use it and get this error when run jest

> Jest encountered an unexpected token
> 
>     This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.
then i fix this error by removing ignore pattern in jest config
but then i get another error
 FAIL  __tests__/getall-test.js
  ● Test suite failed to run

    [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

    To fix this issue try these steps:

      • Run `react-native link @react-native-community/async-storage` in the project root.

      • Rebuild and restart the app.

      • Run the packager with `--reset-cache` flag.

      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app.

      • If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md

    If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-async-storage/issues

      at Object.<anonymous> (node_modules/@react-native-community/async-storage/lib/AsyncStorage.js:22:9)
      at Object.<anonymous> (node_modules/@react-native-community/async-storage/lib/index.js:5:44)

## Details:
npm: 6.14.4
platform: windows

"devDependencies": {
    "@babel/plugin-transform-runtime": "^7.9.6",
    "@babel/preset-typescript": "^7.9.0",
    "@react-native-community/async-storage": "^1.10.0",
    "@types/jest": "^25.2.1",
    "@types/react": "^16.9.34",
    "@types/react-native": "^0.62.7",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "^26.0.1",
    "babel-plugin-module-resolver": "^4.0.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react": "^16.13.1",
    "react-native": "^0.62.2",
    "typescript": "^3.8.3"
  }

this not a react native project its just an library for react native.
Thanks

**Comment by Krizzu** [comment]
Have you seen [Jest integration docs?](https://github.com/react-native-community/async-storage/blob/master/docs/Jest-integration.md)

**Comment by E-RROR** [comment]
thanks

**Comment by maxweb4u** [comment]
> Have you seen [Jest integration docs?](https://github.com/react-native-community/async-storage/blob/master/docs/Jest-integration.md)

Link is not working :(
