### ISSUE TITLE
Error [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null

### ISSUE THREAD

**Issue by hishamudin98** [react-native-community/async-storage#353]
# Current behaviour

Sorry, i am new in react native, i just want to run the simple apps using a device but it turns to error. it working when i run in browser that have asyncstorage 

# Repro steps

Steps I took are as follows:

- npm cache clean --force 
- npm start

# Environment

- Async Storage version: 1.10.0
- React-Native version: 0.61.4
- Platform tested: Android (not simulator)
- Expo version: 36.0.0

**Comment by Krizzu** [comment]
I see you're using Expo, so unfortunately, you won't be able to use this package, unless you eject (which I don't recommend for now, since you're new to RN). Keep on using `AsyncStorage` from Expo and don't mind warning for now.

**Comment by hishamudin98** [comment]
How to run the program if there still have an error. It works when use web browser but i want to use maps so it must run on device but the error haunted me. Please help me. @Krizzu

**Comment by Krizzu** [comment]
Again, if you're using Expo, then you need to remove dependency on this Async Storage (by removing its name in your `package.json` and running `npm install/yarn` again) and use [Async Storage from the core](https://docs.expo.io/versions/latest/react-native/asyncstorage/)

**Comment by hishamudin98** [comment]
wowww its working thank you! @Krizzu
