### ISSUE TITLE
CocoaPods is only supported on darwin machines

### ISSUE THREAD

**Issue by romandr25** [react-native-community/async-storage#364]
```
PS F:\Roma\prog\izigo\ios> npx pod-install
npx: installed 1 in 3.862s
Scanning for pods...
CocoaPods is only supported on darwin machines
```

No search results for that! Please help! I'll try to reboot meanwhile.

I updated yarn with `npm install -g yarn` and tried to install async-storage again:
```
 yarn add @react-native-community/async-storage
yarn add v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@react-native-community/eslint-config > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react@7.12.4" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has incorrect peer dependency "eslint@^3.17.0 || ^4 || ^5".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @react-native-community/async-storage@1.10.3
info All dependencies
└─ @react-native-community/async-storage@1.10.3
Done in 91.20s.
```
Could those warnings be related to the reason? I installed yarn just today... From `https://classic.yarnpkg.com/` with .msi file.

**Comment by Krizzu** [comment]
> CocoaPods is only supported on darwin machines

It means that CocoaPods are only available for MacOS. You can use [Expo](https://expo.io/), which has dependencies bundled inside, so you can develop iOS on Windows.

**Comment by romandr25** [comment]
> > CocoaPods is only supported on darwin machines
> 
> It means that CocoaPods are only available for MacOS. You can use [Expo](https://expo.io/), which has dependencies bundled inside, so you can develop iOS on Windows.

Thank you! Can I use it only for Android now BUT later easily use `pod install` with Expo or MacOS for iOS in that project?

**Comment by asalha** [comment]
> > > CocoaPods is only supported on darwin machines
> > 
> > 
> > It means that CocoaPods are only available for MacOS. You can use [Expo](https://expo.io/), which has dependencies bundled inside, so you can develop iOS on Windows.
> 
> Thank you! Just to be sure:
> Can I use it only for Android now AND later with Mac simply use `pod install` to make it work for iOS in that project? With no extra actions.
> 
> Hope the question makes sense :)

I am in exactly the same situation. What did you do since then?

Thanks in advance for your help.

**Comment by conormullangit** [comment]
> > > CocoaPods is only supported on darwin machines
> > 
> > 
> > It means that CocoaPods are only available for MacOS. You can use [Expo](https://expo.io/), which has dependencies bundled inside, so you can develop iOS on Windows.
> 
> Thank you! Just to be sure:
> Can I use it only for Android now AND later with Mac simply use `pod install` to make it work for iOS in that project? With no extra actions.
> 
> Hope the question makes sense :)

Hi, did you find a solution to this problem? Is it only MacOS that can use pod install?  Thanks,

**Comment by tido64** [comment]
> > > > CocoaPods is only supported on darwin machines
> > > 
> > > 
> > > It means that CocoaPods are only available for MacOS. You can use [Expo](https://expo.io/), which has dependencies bundled inside, so you can develop iOS on Windows.
> > 
> > 
> > Thank you! Just to be sure:
> > Can I use it only for Android now AND later with Mac simply use `pod install` to make it work for iOS in that project? With no extra actions.
> > Hope the question makes sense :)
> 
> Hi, did you find a solution to this problem? Is it only MacOS that can use pod install? Thanks,

There is no way to `pod install` on any other platform than macOS. CocoaPods is a dependency manager for apps on Apple platforms. You cannot build an app for Apple platforms without a Mac, unless you use a third-party service like Expo. This is not a "problem". It is just how things currently are if you want to develop an app for iOS/macOS.
