### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by satyam90** [react-native-community/async-storage#370]
## Current behavior

When I'm using AsyncStorage with getItem & setItem as per documentation, its throwing error: No _"authtoken storageTypeError: _asyncStorage.default.getItem is not a function"_

## Expected behavior

While going through the file "index.d.ts", I found them as _"get and set"_
## Environment

- **Async Storage version**: "^2.0.0-rc.3"
- **React-Native version**: "~0.62.2"
- **Platform tested**: Both iOS & Android
- **Logs/Error that are relevant**: No authtoken storageTypeError: _asyncStorage.default.getItem is not a function

**Comment by Krizzu** [comment]
When using v2, please refer to [v2 api documentation](https://github.com/react-native-community/async-storage/blob/v2/packages/core/docs/API.md)
