### ISSUE TITLE
defined multiple times

### ISSUE THREAD

**Issue by RicardoDolNL** [react-native-community/async-storage#375]
## Current behavior

I get a error while building a release for android:
`Error: /my-app/node_modules/@react-native-community/async-storage/android/build/.transforms/fc2daeb4ff0db30fd0f1f5e68862f91b/classes/classes.dex, Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /my-app/node_modules/@react-native-community/async-storage/android/build/.transforms/fc2daeb4ff0db30fd0f1f5e68862f91b/classes/classes.dex, /my-app/android/app/build/intermediates/external_libs_dex/release/out/classes2.dex
`

## Expected behavior

That I can build my release.

## Environment

- **Async Storage version**:  1.11.0
- **React-Native version**: 0.62.2
- **Platform tested**: Android
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Have you tried to clean build folders, `./gradlew clean`?

**Comment by danilo900** [comment]
I have migrated from  AsyncStorage (react-native) to that, and I needed to do the clean like @Krizzu  said.

Thanks

**Comment by Krizzu** [comment]
Please reopen if issue still exist

**Comment by RicardoDolNL** [comment]
Sorry for the late response, but no ./gradlew clean was the first thing i tried but that does not solve the problem

**Comment by anshumanburman** [comment]
`Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /Users/ansh/Documents/ANSH/FitnerApp/node_modules/@react-native-community/async-storage/android/build/.transforms/a5435cadaa866449cc02394986475e6b/classes/classes.dex, /Users/ansh/Documents/ANSH/FitnerApp/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes2.dex

`
i am also facing this issue when generating apk but app is running well on device in debug mode. Please tell me the solution if you have solved.? Thanks in advance.

**Comment by HimaniPatelTH** [comment]
@anshumanburman  i am also facing same issue . have you found any solution ?

**Comment by RicardoDolNL** [comment]
@anshumanburman @HimaniPatelTH the problem for me was that async-storage had a conflict with react-native-jitsi-meet dependency. Not only async-storage but also react-native-svg. So i had to exclude those inside my /app/build.gradle file:

```
    implementation(project(':react-native-jitsi-meet')) {
        exclude group: 'com.facebook',module:'hermes'
        exclude group: 'com.facebook.react',module:'react-native-svg'
        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
        transitive = true
    }

    implementation ('org.jitsi.react:jitsi-meet-sdk:2.+') {
        exclude group: 'com.facebook',module:'hermes'
        exclude group: 'com.facebook.react',module:'react-native-svg'
        exclude group: 'com.facebook.react',module:'react-native-community-async-storage'
        transitive = true
    }
```

This fixed it for me. So you might also have a dependency that already includes async-storage and you might also want to exclude it in the same way. Hope this helps.

**Comment by HimaniPatelTH** [comment]
@RicardoDolNL i have added dependency as jar file so this solution is not working .

**Comment by jawkhan** [comment]
I'm also facing this same issue. @RicardoDolNL, how do I work out which particular dependency I am getting a conflict with?

**Comment by theneekz** [comment]
> how do I work out which particular dependency I am getting a conflict with?
The error should tell you. For me, it gave
`Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /my-app/node_modules/@react-native-community/async-storage/android/build/.transforms/de7795affad299349439af66c4243cf0/classes/classes.dex, /my-app/@react-native-async-storage/async-storage/android/build/.transforms/78a73aac79dcb6c6543a824bace53f0e/classes/classes.dex`

Turns out @react-native-community/async-storage is deprecated, and I was using it in some places as well as @react-native-async-storage/async-storage. 

Change all the places I used -community to use this package then ran
```
yarn remove @react-native-community/async-storage
cd andriod
./gradlew clean
```

**Comment by mAnasAwan** [comment]
In my case, i had two AsyncStorage packages installed i.e 

> **@react-native-async-storage/async-storage**

> **@react-native-community/async-storage**

uninstalling/removing one of the package would give you module not found error, as some of other packages like @aws-amplify,@aws-sdk etc were importing AsyncStorage from either of two packages in **node_modules/${packageName}/core/lib-esm/StorageHelper/reactnative.js**

- [ ] just use single common **import AsyncStorage from** statement in all of your packages file as well as in your project files its either from **@react-native-async-storage/async-storage** in all or **@react-native-community/async-storage** in all, use find and replace feature of your editor
- [ ] remove package whose Import instance is 0 
- [ ] rebuild project

![Screenshot 2021-05-21 at 6 49 13 PM](https://user-images.githubusercontent.com/50512005/119147706-4494d580-ba65-11eb-80a1-1a748ca7259f.png)

**Comment by landonwjohnson** [comment]
> ```
> ./gradlew clean
> ```

this worked for me

**Comment by landonwjohnson** [comment]
> > how do I work out which particular dependency I am getting a conflict with?
> 
> The error should tell you. For me, it gave `Type com.reactnativecommunity.asyncstorage.AsyncLocalStorageUtil is defined multiple times: /my-app/node_modules/@react-native-community/async-storage/android/build/.transforms/de7795affad299349439af66c4243cf0/classes/classes.dex, /my-app/@react-native-async-storage/async-storage/android/build/.transforms/78a73aac79dcb6c6543a824bace53f0e/classes/classes.dex`
> 
> Turns out @react-native-community/async-storage is deprecated, and I was using it in some places as well as @react-native-async-storage/async-storage.
> 
> I changed all the places I used -community to use this package then ran
> 
> ```
> yarn remove @react-native-community/async-storage
> cd andriod
> ./gradlew clean
> ```
> 
> and was able to successfully build my release with`./gradlew assembleRelease`

Not just doing gradlew clean, but removing  @react-native-community/async-storage
