### ISSUE TITLE
Cannot perform this operation because the connection pool has been closed

### ISSUE THREAD

**Issue by anthinkingcoder** [react-native-community/async-storage#376]
## Current behavior
 java.lang.IllegalStateException
Cannot perform this operation because the connection pool has been closed.
com.reactnativecommunity.asyncstorage.ReactDatabaseSupplier.ensureDatabase(ReactDatabaseSupplier.java:106)
![image](https://user-images.githubusercontent.com/17498633/83212194-9035db80-a191-11ea-96c8-92b42c29081a.png)
![image](https://user-images.githubusercontent.com/17498633/83212339-eb67ce00-a191-11ea-9aea-ee34d18e2572.png)

## Environment

- **Async Storage version**:1.9 
- **React-Native version**: 0.59
- **Platform tested**: Android 7.0,level 24
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Hey @anthinkingcoder 

Do you have some repro steps?

**Comment by paryanihitesh** [comment]
Did we find the root cause for this issue?

**Comment by xwartz** [comment]
I have the same issue, any updates?

**Comment by khunghang16** [comment]
I have the same issue, any updates?

**Comment by krizzu** [comment]
You can find my comments regarding the issues in different threads, [for example this one](https://github.com/react-native-async-storage/async-storage/issues/824#issuecomment-1268593913)

**Comment by ashishsarin-fareye** [comment]
We are also facing the same issue. Does anyone found any solution for this?
