### ISSUE TITLE
Is it okay to store credentials in async storage ?

### ISSUE THREAD

**Issue by ShivamJoker** [react-native-community/async-storage#377]
## You want to:  

Hey I just want to know if is it safe to store data like purchase history or auth tokens ?
## Details:

Can anyone tamper with the data ? and what's the location it is stored in android device

**Comment by Krizzu** [comment]
Hey, 

For Android, we store data using SQLite, which stores a DB file on your device (normally **/data/data/<your.package.name>/databases/db_name.db.**). Async Storage do not provide any encryption/decryption tools, so anything stored in DB is in plain text. When it comes to sensitive data, I'd avoid storing anything (maybe unless you already hashed values).

Access Tokens (JWT for example), should usually be short-lived for security? It's perfectly fine to store those in DB, as they have expiration date.

**Comment by Blimeys** [comment]
Preferably not, you should use the [Keychain](https://developer.android.com/reference/android/security/KeyChain)

I have been using [react-native-keychain](https://github.com/oblador/react-native-keychain)

**Comment by Utkarsh15531** [comment]
What about windows? Keychain do not support windows.
