### ISSUE TITLE
React-native-windows throws error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null. 

### ISSUE THREAD

**Issue by exotexot** [react-native-community/async-storage#380]
![error-log](https://user-images.githubusercontent.com/10153413/83921108-fe743280-a77d-11ea-9711-8da920422a5b.PNG)
I'm getting this issue after experimenting with npx react-native run-windows, running on Version 0.62.preview-10. Having the latest version of AsyncStorage installed and getting the error:

Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null,

**Comment by exotexot** [comment]
Also when I perform react-native link as suggested, I get this

info Linking "@react-native-community/async-storage" iOS dependency
info iOS module "@react-native-community/async-storage" has been successfully linked
info Linking "@react-native-community/async-storage" Android dependency
info Android module "@react-native-community/async-storage" has been successfully linked

Not mentioning the windows platform whatsoever. I feel like I'm doing some general mistake somehow. Can please someone help?

I also downgraded to the stable react-native-windows version 0.61.5 to see if it was an issue with the latest 0.62 preview

**Comment by Krizzu** [comment]
For Windows, go for [manual linking guide](https://react-native-community.github.io/async-storage/docs/link#windows)

**Comment by exotexot** [comment]
After following the manual linking guide, building fails with the error "Build failed with message undefined. Check your build configuration."

I added the package to the solution and made the changes as stated in the linkin guide like so:
![app-cpp](https://user-images.githubusercontent.com/10153413/84016088-12d24e00-a97d-11ea-837b-6e9e0c13f678.PNG)
![pch](https://user-images.githubusercontent.com/10153413/84016091-136ae480-a97d-11ea-83ed-b7e61318a2f5.PNG)

**Comment by exotexot** [comment]
Alright. I've learned now, that I need to build once through Visual Studio before I can use react-native run-windows through the terminal.
