### ISSUE TITLE
Can I lose my storage data?

### ISSUE THREAD

**Issue by kazzkiq** [react-native-community/async-storage#381]
## You want to:  
Update my app from RN `0.60` to `0.62`.

## Details:
I make heavy use of this awesome lib on my app, and the time has come that I will update it to RN 0.62, along with other libraries too (like React Navigation, etc).

My question is: **By updating RN and those libs, its there any chance I lost the access to my current persisted storage data?**

It isn't quite clear how RN access/finds this local data, and I'm worried that by updating versions I might lose access to it (the new app version could use a "new instance" of AsyncStorage and ignore the older one, etc).

Does that makes sense? Or can I update my app without worries?

**Comment by Krizzu** [comment]
Data saved by Async Storage is located on your device. Updating unrelated dependencies would not have impact on it.

What version of Community's Async Storage are you using?

**Comment by kazzkiq** [comment]
Accordingly to my `package-lock.json`: `v1.9.0`

**Comment by Krizzu** [comment]
We changed a location of storage data for iOS in earlier releases (and internal migration), so you're good to upgrade.
