### ISSUE TITLE
Changing js files to ts

### ISSUE THREAD

**Issue by keyblade95** [react-native-community/async-storage#382]
## Motivation

I am trying to share code between react native and react. The following files inside the `lib` folder cannot be evaluated since they contains typescript annotations:
- AsyncStorage.js
- AsyncStorage.web.js
- hooks.js

## Description

It is sufficient to rename the files above if this does not cause other issues:
- AsyncStorage.ts
- AsyncStorage.web.ts
- hooks.ts

**Comment by keyblade95** [comment]
Maybe this is not sufficient since I got also:

```
Module parse failed: Unexpected token (21:42)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| 
> const createPromise = (getValue, callback): Promise<*> => {
|   return new Promise((resolve, reject) => {
|     try {
```

**Comment by Krizzu** [comment]
Hey,

By `typescript annotations` you mean types, correct? We're using `Flow` in source code, TS types are located [here](https://github.com/react-native-community/async-storage/tree/master/types). [Bob](https://github.com/react-native-community/bob) is used to generate modules for different targets (and are already stripped out of Flow Types).

What version of Async Storage you use?

**Comment by keyblade95** [comment]
Sorry for the request, but it was my fault. I was trying to use this library in React Web through this wrapper: https://github.com/sunnylqm/react-native-storage, but I noticed that this is obviously not possible!

**Comment by Krizzu** [comment]
You can use Async Storage directly in Web platform
