### ISSUE TITLE
Remove `mergeItem` in v2

### ISSUE THREAD

**Issue by arniu** [react-native-community/async-storage#388]
## Motivation

1. The Web [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) has no such an API;
2. Only `mergeItem` assume the content is JSON string, which is not generic as others;
3. We should keep the public API concise.

And as a result, the deprecated `deep-assign` can be removed too.

**Comment by Krizzu** [comment]
v2 has no merge item in default types - just as extension for legacy.
