### ISSUE TITLE
Incorrect url anchoring on the website

### ISSUE THREAD

**Issue by Tudor0404** [react-native-community/async-storage#398]
[On the usage page](https://react-native-community.github.io/async-storage/docs/usage/), a [link](https://react-native-community.github.io/async-storage/docs/usage/api) at the bottom is provided to head over to the api page. The url is incorrect, it should instead be https://react-native-community.github.io/async-storage/docs/api/ (/api/ instead of /usage/api/).

**Comment by Krizzu** [comment]
Good catch. Would you be able to create PR with changes?
