### ISSUE TITLE
Lost data on iOS after releasing an update

### ISSUE THREAD

**Issue by peternoordijk** [react-native-community/async-storage#402]
## Current behavior

Our app uses async-storage to store JSON serialised data. It's really not getting any more complicated than `AsyncStorage.getItem` and `AsyncStorage.setItem`. After we release an update we get complaints from users who lost their data. These complaints are consistently tied to when we release a new version of the app.

## Expected behavior

`AsyncStorage.getItem` to "recognise" data from before the update.

## Repro steps

We haven't been able to reproduce it the issue ourselves entirely, but based on the support requests it's something along the following:

- Open app on iOS device
- Release new version of app
- Start update on device, but don't finish it yet (so unplug internet for example)
- Perform an action in the iOS device which triggers `AsyncStorage.setItem`.
- Finish update
- Reopen app
- Data is gone

## Environment

- **Async Storage version**: ^1.7.1
- **React-Native version**: 0.61.5
- **Platform tested**: iOS
- **Logs/Error that are relevant**: -

**Comment by peternoordijk** [comment]
I most of all wonder if this is a known issue and if there's a way for me to prevent it from happening in the future.

**Comment by Krizzu** [comment]
I'm sorry to hear that.

`AsyncStorage` stores saved data in [Application Support directory ](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#contents), which is not removed during app updates (it's even backed up by default). 

Have you been able to reproduce this with the repro steps?

**Comment by peternoordijk** [comment]
Hi @Krizzu , the weird thing is that I'm not (yet). I thought this might have been a known issue or something like that. I'll try to reproduce it and will update this issue once I know more.

**Comment by aravi365** [comment]
@peternoordijk  i am getting the same issue on both android and ios. I am storing my accessToken for backend calls using asyncstorage, but its getting cleared after all the store updates . Any idea how to reproduce it?

**Comment by peternoordijk** [comment]
Hi @aravi365 , I'm not exactly sure if we're having related issues, but I think it's a better idea to use https://github.com/oblador/react-native-keychain specifically for tokens

**Comment by peternoordijk** [comment]
I'm still trying to get more information on this

**Comment by JoelOnGithub** [comment]
I am experience similar issues. After an update through the app store, all storage is removed. 

We are using react native 0.60.5, async storage version ^1.6.3, around 2 weeks ago it occured for the first time. 

As far as we know it only happened on iPhone 11 pro devices.

@peternoordijk what ways are you using to get more information on this?

**Comment by peternoordijk** [comment]
@JoelOnGithub sorry for the late response. So far just whatever information the users reported and also event logs. But neither seem to be really useful so far...

**Comment by unfrgivn** [comment]
Having similar issues that I’m unable to reproduce and seems to be a lot of users on iOS 13.5.1 with iPhone 11s (but that’s could be coincidental as it’s a popular combination). 

Started in early June with switching to community version of AsyncStorage on RN 0.62.2 and now users are logged out without knowing it and not receiving push notes. I will post here if I can find anything useful.

**Comment by peternoordijk** [comment]
I just released an update and there was one user with lost data. However there was some app specific code which might have been related. I'll keep an eye out at the next update: I hope this issue wasn't part of this library after all.

**Comment by auaden** [comment]
Hi @unfrgivn @peternoordijk any updates? I am facing the same issue with our users getting logged out every time they quit the app, due to the authToken getting wiped out. Seems to affect a handful of iPhone 8 and XR users. The frustrating thing is I can't replicate this on my simulator and my phone..

**Comment by jordangrant** [comment]
Hey @auaden might be a long shot but something came to mind. When working with Ionic, there was a case in which access to secure storage was not possible if the phone did not have a passcode protecting it. Give that a try.

**Comment by auaden** [comment]
Hi @jordangrant thanks for the suggestion, but I tried turning off the passcode and still couldn't replicate the issue :( 

The app is on:
- react-native: 0.61.5
- @react-native-community/async-storage: 1.12.0

**Comment by peternoordijk** [comment]
Hi @auaden, my last update on this was that I found some code which might have caused the loss of our user data. This code was specifically for our app though: so not part of this library. This issue hasn't occurred anymore for my app since then. In a week or so I'll release another update. If that goes well then I'm pretty sure it's not an issue of this library. 

In any case I think it's a good idea to double check where you're storing the data. For me I used an ID in the key for `AsyncStorage.setItem` which was `undefined` in some edge cases.

**Comment by peternoordijk** [comment]
I'm going to close this issue as it really seems to have been solved. So for anyone else who has this issue: just double check the code which calls `AsyncStorage.setItem` and `AsyncStorage.getItem` or check any code which wraps these functions 🙂

**Comment by Chantall647** [comment]
> Hi @auaden, my last update on this was that I found some code which might have caused the loss of our user data. This code was specifically for our app though: so not part of this library. This issue hasn't occurred anymore for my app since then. In a week or so I'll release another update. If that goes well then I'm pretty sure it's not an issue of this library.
> 
> In any case I think it's a good idea to double check where you're storing the data. For me I used an ID in the key for `AsyncStorage.setItem` which was `undefined` in some edge cases.

Can you give me an example of some or one of the edge cases ? I am facing the same problem rn

**Comment by ikimiler** [comment]
> @peternoordijk i am getting the same issue on both android and ios. I am storing my accessToken for backend calls using asyncstorage, but its getting cleared after all the store updates . Any idea how to reproduce it?

Can you please give me an example of some or one of the edge cases ? I am facing the same problem rn

**Comment by peternoordijk** [comment]
Hi @ikimiler and @Chantall647 , sorry for the very late response. The edge cases all had to do with general React (Native) situations; asynchronous data reading and data fetching at the same time, incorrect dependencies in the hooks, etc. In my case we were also working with a relatively old version of React. React version 17 and earlier (and their corresponding React Native versions) have this thing in which every setState call in an asynchronous callback causes the component to rerender. In my case I would call setIsLoading(false) and then setData(response), but in that case there would be one render in which isLoading would be false and data would still be null or undefined or whatever. I ended up wrapping all those asynchronous calls in a unstable_batchedUpdates function. There’s articles about this specific function, for example [this one](https://javascript.plainenglish.io/batch-updates-in-react-17-or-earlier-versions-5f76d58e3af1). I hope this helps!

**Comment by peternoordijk** [comment]
It might also help to call setState with a callback so that you are sure that you deal with the very latest version of that state (instead of dealing with hook dependencies). Read more [here](https://legacy.reactjs.org/docs/hooks-reference.html#functional-updates)

**Comment by ikimiler** [comment]
> 嗨，很抱歉回复很晚。边缘情况都与一般的 React（原生）情况有关;异步数据读取和数据获取同时进行，钩子中的依赖关系不正确等。就我而言，我们也在使用一个相对较旧的 React 版本。React 版本 17 及更早版本（及其相应的 React Native 版本）具有这种功能，其中异步回调中的每个 setState 调用都会导致组件重新渲染。在我的情况下，我会调用 setIsLoading（false） 然后调用 setData（response），但在这种情况下，会有一个渲染，其中 isLoading 为 false，数据仍为 null 或未定义或其他任何内容。我最终将所有这些异步调用包装在一个 unstable_batchedUpdates 函数中。有关于这个特定函数的文章，例如[这个](https://javascript.plainenglish.io/batch-updates-in-react-17-or-earlier-versions-5f76d58e3af1)。我希望这会有所帮助！

thx,i try it
