### ISSUE TITLE
'setItem' undefined

### ISSUE THREAD

**Issue by wincod75** [react-native-community/async-storage#403]
## Current behavior

When I try to set an item, it always fails with undefined

## Expected behavior

It shouldn't fail, I'm logging out the value right before setItem and it's not undefined

## Repro steps

```
import { AsyncStorage, useAsyncStorage } from '@react-native-community/async-storage';

async function storeUserId(userId) {
    try {
      console.log("Pre Storage " , userId);
      await AsyncStorage.setItem('userId', userId);
    } catch (e) {
      console.log("Storage Failed " , e);
    }
 }

  async function confirmCode() {
    try {
      await confirm.confirm(code);
      loginPhone(confirm).then(resp => {
        getMembersPromise(resp).then(res => {
          
          if (res === undefined) {
            return;
          }

          let userId = res.id;
          storeUserId(userId);
         
          return;
    
        });
      }).catch(error => {
        return error;
      });
 
    } catch (e) {

    }
  }
```

## Environment

- **Async Storage version**: 1.11.0
- **React-Native version**: 62.2
- **Platform tested**: iOS
- **Logs/Error that are relevant**: TypeError: Cannot read property 'setItem' of undefined

**Comment by Krizzu** [comment]
How do you import AsyncStorage into your project?

**Comment by wincod75** [comment]
My bad: `import { AsyncStorage, useAsyncStorage } from '@react-native-community/async-storage';`

**Comment by Krizzu** [comment]
use default import
`import AsyncStorage from '@react-native-community/async-storage';`

**Comment by wincod75** [comment]
So... the solution is to import twice?

`import { useAsyncStorage } from '@react-native-community/async-storage';
import AsyncStorage from '@react-native-community/async-storage';`

**Comment by Krizzu** [comment]
`import AsyncStorage, { useAsyncStorage}  from '@react-native-community/async-storage';`
