### ISSUE TITLE
Allow RegExp for multiGet/multiRemove matching

### ISSUE THREAD

**Issue by mrprkr** [react-native-community/async-storage#404]
## Motivation

I'm using this for caching API requests locally and follow a pattern `{key: @API_${path}}`
Occasionally, there might be a need for the Cache to be reset (change of pattern, storage bloat etc)
Because the `${path}` can be dynamic and include IDs, it's not possible to hard-code these values in a clear cache function

## Description

Allow method to match results using a regular expression

## New feature implementation

Allow ```AsyncStorage.multiRemove(keys)``` to be passed keys as: ```keys = [new RegExp '/@_API/']```
OR introduce new method ```AsyncStorage.removeMatchingKeys(new RegEx( '/@API_/')```

**Comment by Krizzu** [comment]
I think there's no need for adding new API, when you can achieve this by:

- getting all keys used (`AsyncStorage. getAllKeys()`)
- filtering the keys list to matching regexp
- passing that list to `AsyncStorage.multiRemove()`

**Comment by mrprkr** [comment]
Good idea

**Comment by eddietex** [comment]
I would think a regex 

> I think there's no need for adding new API, when you can achieve this by:
> 
> * getting all keys used (`AsyncStorage. getAllKeys()`)
> * filtering the keys list to matching regexp
> * passing that list to `AsyncStorage.multiRemove()`

I would think a pattern matching option would still be desirable if it would perform better than this suggestion ( O(N), where N is the number of existing keys ).
Is anyone else interested in this?
