### ISSUE TITLE
A problem occurred configuring project ':react-native-community_async-storage'

### ISSUE THREAD

**Issue by VikBn** [react-native-community/async-storage#405]
## Current behavior
After installing AsyncStorage "yarn add @react-native-community/async-storage --save" Android Studio throw an exception https://i.imgur.com/h0F4Uve.png

**A problem occurred configuring project ':react-native-community_async-storage'.
Unsupported BuildConfig type : Long**

How can I solve it?

## Repro steps

1) Clone this repo https://github.com/VikBn/AsyncTest.git
2) yarn or npm i
3) Try to run it on Android Studio
## Environment

- **Async Storage version**: "^1.11.0"
- **React-Native version**: "^0.63.1",
- **Platform tested**:  "Android 4.1 Canary 10"
- **Logs/Error that are relevant**: http://i.imgur.com/EE6I40h.png

**Comment by Krizzu** [comment]
Haven't tested it with android plugin 4.1 - can you try with v3.5.3?

In your project `android/build.gradle` use 
```
classpath("com.android.tools.build:gradle:3.5.3")
```

**Comment by VikBn** [comment]
@Krizzu Thank's a lot! It's solved the problem.

**Comment by hassanhashmi999** [comment]
@Krizzu thank you
its working for me
