### ISSUE TITLE
Query quota and prompt user to increase?

### ISSUE THREAD

**Issue by quinthar** [react-native-community/async-storage#411]
## Motivation

Different platforms seem to have different amounts of storage quota available, whether limited by the platform itself (ie, a 5MB limit for the Web version), or perhaps limited by disk space.  It would be nice to know how much space is available in order to manage usage to stay under that limit, as well as have some mechanism to request the user to allocate more.

## Description

Add methods that allows:
* Querying the total amount of storage allowed to this application
* Querying the total amount of storage currently used by this application
* Prompt the user to request a higher quota

## New feature implementation

 I would imagine this would require finding the specific API's for each platform, and I could even imagine it returning some kind of `UNKNOWN` value on platforms that don't support quota management.  But since Chrome 13 (for example) there is an API available (https://developer.chrome.com/apps/offline_storage#managing_quota) that could be used for the web implementation, which is probably the most space-constrained option so is the most important.

**Comment by Krizzu** [comment]
Hey @quinthar,

Thanks for sharing your ideas. Unfortunately, I'm afraid that we won't be able to provide this feature in feasible way. For web, `LocalStorage` is used from the beginning, which has fixed limit of 5 MB. Changing storage to one that supports Quota API  means we'll have to provide a migration path (which can be error-prone). Also I could not find info about compatibility for other browsers. [Looking at Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/API/StorageQuota) it looks like it's deprecated and not widely adopted.

For other platforms, capacity is limited to Filesystem (exception is Android, which by default is set to 5 MB, [but can be changed if necessary](https://react-native-community.github.io/async-storage/docs/advanced/db_size)).

**Comment by quinthar** [comment]
Ah, got it.  Yes, this still seems like some bleeding edge stuff.  This link is pretty good https://whatwebcando.today/storage-quota.html  Overall it seems like most modern browsers support *some* method of doing it, but it's pretty nonstandard at this point.  Thanks for considering the request!
