### ISSUE TITLE
Package removed from yarn registry?

### ISSUE THREAD

**Issue by piotrmoszkowicz** [react-native-community/async-storage#412]
Have someone removed by mistake package from yarn registry?

```yarn add @react-native-community/async-storage                                                 ░▒▓ 1 ↵ | 11:29:30 
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-community%2fasync-storage: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/praca/Desktop/ChoicesApp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.```

**Comment by suresht2s** [comment]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-native-community%2fasync-storage - Not found
npm ERR! 404 
npm ERR! 404  '@react-native-community/async-storage@^1.6.1' is not in the npm registry.
Can someone look into this?

**Comment by phanvungoc** [comment]
![Screen Shot 2020-08-06 at 16 47 59](https://user-images.githubusercontent.com/65708344/89517212-9be1f600-d803-11ea-87b5-48882d1c71be.png)

**Comment by Krizzu** [comment]
Looks like it's NPM issue:
https://status.npmjs.org/

**Comment by piotrmoszkowicz** [comment]
Yes, it's npm issue. You are right!
