### ISSUE TITLE
 Put the complete path to 'MainApplication.java' file on the Manual linking

### ISSUE THREAD

**Issue by caiovini980** [react-native-community/async-storage#413]
## You want to:  

I was installing the feature in my project and I saw on the documentation, more specifically on the third step of the Android tutorial where we need to apply some commands on 'MainApplication.java' file, that there isn't the full path to the java file (like the other instructions).

So, I would like to know if it's viable to change that path to the complete one, because for some new developers can be kinda difficult to find that file.

Thanks.

**Comment by Krizzu** [comment]
Hello,

Sounds good to me. Would you like to open a [PR to documentation and change the path to](https://github.com/react-native-community/async-storage/blob/master/website/docs/Linking.md#android) `(android/app/src/main/java/your/package/MainApplication.java)` ?

**Comment by caiovini980** [comment]
Sure, thanks :)

**Comment by caiovini980** [comment]
Which branch should I use?

**Comment by Krizzu** [comment]
Target `master`
