### ISSUE TITLE
Async-storage doesn't work on tvOS

### ISSUE THREAD

**Issue by lkinasiewicz** [react-native-community/async-storage#416]
## Current behavior

Using the lib on tvOS throws "permission denied" error.

## Expected behavior

It is possible to use the lib to store data on tvOS.

## Repro steps

Just use the library so that it tries to create directory for its files, e.g.:
```js
AsyncStorage.getAllKeys()
  .then(keys => AsyncStorage.multiRemove(keys))
  .catch(error => console.error('Storage clean failed:', error));
```

## Environment

- **Async Storage version**: 1.11.0
- **React-Native version**: 0.61.5
- **Platform tested**: tvOS 13.4.8 device - could not reproduce in simulator
- **Logs/Error that are relevant**:
`[Error: Failed to create storage directory.Error Domain=NSCocoaErrorDomain Code=513 "You don't have permission to save the file "RCTAsyncLocalStorage_V1" in the folder "com.org.example"." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/0E076B5B-F577-4D0B-A4E4-58FF3EDF7B5A/Library/Application Support/com.org.example/RCTAsyncLocalStorage_V1, NSUnderlyingError=0x28205dfe0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}]`

\
I think the regression is caused by this change: https://github.com/react-native-community/async-storage/commit/4e49db6308882515a284a183c8e9daf5a50b33ef#diff-54c57f4041d9a698ab027d21344b6e63R98

According to https://developer.apple.com/library/archive/documentation/General/Conceptual/AppleTV_PG/index.html#//apple_ref/doc/uid/TP40015241 section *Local Storage for Your App Is Limited* - on tvOS data should be stored either in `NSUserDefaults` (which is limited to 500KB on tvOS) or in `NSCachesDirectory`. I guess async-storage should use the latter.

**Comment by Krizzu** [comment]
Hey @lkinasiewicz,

That's interesting. AsyncStorage used [NSCacheDirectory previously for tvOS](https://github.com/react-native-community/async-storage/blob/master/ios/RNCAsyncStorage.m#L87-L89), but now it's moved to `NSApplicationSupportDirectory` (more reliable on iOS). `NSCacheDirectory` can be deleted in case of low  memory and I can't find reliable source of where tvOS should keep files.

I'll do bunch of tests later on and probably bring back `NSCacheDirectory`.

**Comment by olafurnsig** [comment]
@Krizzu any update or temp fix?

**Comment by Krizzu** [comment]
@olafurnsig 

Temp fix would be to locally move [this conditional check](https://github.com/react-native-community/async-storage/blob/master/ios/RNCAsyncStorage.m#L87-L91), few [lines below](https://github.com/react-native-community/async-storage/blob/master/ios/RNCAsyncStorage.m#L98). I'll try to test and send PR this week

**Comment by olafurnsig** [comment]
@Krizzu 

Still getting this though in the react native console:
` WARN     Persistent storage is not supported on tvOS, your data may be removed at any point.`

**Comment by Krizzu** [comment]
@olafurnsig That's due how tvOS is designed. Pretty much all data stored should be purgeable, hence that's why `AsyncStorage` stores data in such place (NSCachesDirectory). You can read more [in programming guide for tvOS in "Local Storage for Your App Is Limited" section](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppleTV_PG/index.html#//apple_ref/doc/uid/TP40015241)

**Comment by olafurnsig** [comment]
So to persist, say some authentication token, I would need to save it manually in DefaultPreferences, since AsyncStorage uses the NSCacheDirectory that can be purged at any given moment?
