### ISSUE TITLE
No mock for 'useAsyncStorage' in jest

### ISSUE THREAD

**Issue by rawatnaresh** [react-native-community/async-storage#417]
I'm using both `AsyncStorage` and `useAsyncStorage` in my application but it turns out there is no mock [implementation](https://github.com/react-native-community/async-storage/blob/master/jest/async-storage-mock.js) for 'useAsyncStorage` and I'm getting an error

![image](https://user-images.githubusercontent.com/29520305/90015585-8586df00-dcc8-11ea-9295-e8d542dabdd0.png)

is there a way i can fix this without switching my code to the `AsyncStorage`

**Comment by KieranO547** [comment]
I used this (in my `jest.setup.js` which is included in my `jest.config.js` via the: `setupFiles: ['<rootDir>/jest.setup.js'],` to get up and running:
```
jest.mock('@react-native-community/async-storage', () => ({
  useAsyncStorage: jest.fn(),
}));
```

If you want to test based on it returning some example data then adjust `jest.fn()` to `jest.mockReturnValue({...data})`. Should be enough for you to continue writing your tests :)

**Comment by rawatnaresh** [comment]
Thank you for your reply @KieranO547 . I updated your answer like this and it worked.
```
jest.mock('@react-native-community/async-storage', () => ({
  useAsyncStorage: () => ({
    getItem: jest.fn(),
    setItem: jest.fn(),
  }),
}));
```
