### ISSUE TITLE
database or disk is full (code 13 SQLITE_FULL)

### ISSUE THREAD

**Issue by perfecten** [react-native-community/async-storage#427]
I got a error :"database or disk is full (code 13 SQLITE_FULL)" at AsyncStorage.setItem(key, val);

What is the max size limit?
Just one key's value ?
or All key's values?

**Comment by UtillYou** [comment]
[Size](https://react-native-community.github.io/async-storage/docs/advanced/db_size/)
They said 6 MB

**Comment by perfecten** [comment]
@UtillYou Thanks.

is Just one key's value less than 6mb?
or are All key's values less then 6mb?

**Comment by UtillYou** [comment]
They didn't say in the document. But I believe it is the total size, not just one key. Because if it is only one key, you can save many keys which will over the limit.

**Comment by perfecten** [comment]
I think The limit size is for total.

there is a const MAX_SQL_KEYS  in AsyncStorageModule.java, 
`private static final int MAX_SQL_KEYS = 999;`
maybe it is the key's limit count.

**Comment by UtillYou** [comment]
No, `MAX_SQL_KEYS ` is used to limit the sql query one time. It is not the keys limit.

**Comment by Krizzu** [comment]
Yes, 6mb is the limit of DB file on a device

**Comment by perfecten** [comment]
donot keys have a limit ? @UtillYou

**Comment by UtillYou** [comment]
As long as total size is less than 6mb, you can define as many keys as you want.

**Comment by perfecten** [comment]
Thanks very much.
I increase the limit to 10mb temporary. 
in next month I will save data as a file

**Comment by jblancoh** [comment]
If you need to increase the space, you need to set AsyncStorage_db_size_in_MB = 10 in Gradle.properties
https://react-native-async-storage.github.io/async-storage/docs/advanced/db_size/

**Comment by BrodaNoel** [comment]
Do you know how to increase that limit using Expo? We don't have access to the Gradle.properties file in Expo

**Comment by amitchaudhary140** [comment]
Can someone help how to increase the size using Expo?

**Comment by prerakmathur05** [comment]
Can someone help me and @amitchaudhary140 to resolve it in expo?

**Comment by SuyanShrestha** [comment]
I pretty much fetched a lot of things out from a food api named themealdb and tried putting up the data in my asyncstorage, but since the max size is only 6mb what should i do

**Comment by jerone** [comment]
> Do you know how to increase that limit using Expo? We don't have access to the Gradle.properties file in Expo

Looks like a great feature request.

**Comment by amitchaudhary140** [comment]
@SuyanShrestha Yes I managed to solve this problem. I created a plugin file "app.plugin.js" at the root level. Below is the code:

```
const { withGradleProperties } = require("@expo/config-plugins");

module.exports = (config) => {
  return withGradleProperties(config, (config) => {
    // Check if the property already exists
    const existingPropertyIndex = config.modResults.findIndex(
      (item) =>
        item.type === "property" && item.key === "AsyncStorage_db_size_in_MB"
    );

    // Update the value if it exists, otherwise add a new property
    if (existingPropertyIndex !== -1) {
      config.modResults[existingPropertyIndex].value = "50";
    } else {
      config.modResults.push({
        type: "property",
        key: "AsyncStorage_db_size_in_MB",
        value: "50",
      });
    }

    return config;
  });
};
```

Please ensure you have "@expo/config-plugins": "^7.8.4" installed.
