### ISSUE TITLE
In simulator and emulator works fine but not in the real devices

### ISSUE THREAD

**Issue by Doosra-App** [react-native-community/async-storage#430]
## Current behavior

In the dashboard screen I am getting the values from the AsyncStorage based on values I am calling Api. In the simulator its working fine but in the real devices it is not calling the api not getting the values from async storage.
https://stackoverflow.com/questions/52001902/only-works-with-debug-js-remotely-on-android

## Environment

- **Async Storage version**: 1.12.0
- **React-Native version**: 0.61.5
- **Platform tested**:Both Android and ios
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Hey,

can you provide repro repo or code snippet that I could have a look into?

**Comment by tido64** [comment]
I'm closing this issue since you got an answer on StackOverflow.
