### ISSUE TITLE
Replace Shared Preferences with Jetpack Datastore

### ISSUE THREAD

**Issue by PritishSawant** [react-native-community/async-storage#434]
## Motivation
Shared Preferences on Android is slow and is bound to be buggy as it fail without warning. Jetpack Datastore solves this issue

## Description
https://android-developers.googleblog.com/2020/09/prefer-storing-data-with-jetpack.html?linkId=98693079

**Comment by Krizzu** [comment]
AsyncStorage uses SQLite

**Comment by PritishSawant** [comment]
@Krizzu  Thanks for letting me know
