### ISSUE TITLE
Correct and clarify error message

### ISSUE THREAD

**Issue by jinhale** [react-native-community/async-storage#437]
## 🐛 Bug Report

I get a dead link in an error message of an incorrectly configured mock module: 

```
If this happens while testing with Jest, check out docs how to integrate AsyncStorage with it: https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Jest-integration.md
```

## To Reproduce

Run an intentionally failed test using `<PROJECT-ROOT>/__mocks__/async-storage.js` with contents of `export default from '@react-native-community/async-storage/jest/async-storage-mock';` and nothing else.  The test fails to run - it doesn't yield a failed result after running. 

## Expected behavior

The URL should exist. 

## envinfo

```
PS C:\Users\me\project> npx envinfo --preset jest

  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Users\me\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    jest: ^26.0.1 => 26.0.1
```
- **Async Storage version**: 1.7.1
- **React-Native version**: 0.61.4
- **Platform tested**: jest on Windows

**Comment by jinhale** [comment]
I'm not sure where to post but the error message directed me here: 

```
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-async-storage/issues
```

**Comment by Krizzu** [comment]
Please checkout [Jest integration docs](https://react-native-community.github.io/async-storage/docs/advanced/jest) as `<PROJECT-ROOT>/__mocks__/async-storage.js` is not a good way to mock `AsyncStorage`

**Comment by jinhale** [comment]
> Please checkout [Jest integration docs](https://react-native-community.github.io/async-storage/docs/advanced/jest) as `<PROJECT-ROOT>/__mocks__/async-storage.js` is not a good way to mock `AsyncStorage`

Thank you for providing the correct documentation link. That solves my personal problem, but it doesn't solve the issue.  Is the correct documentation provided in a more recent version? Will the correct link be given in a future release?
