### ISSUE TITLE
AsyncStorage mock methods do not return promises

### ISSUE THREAD

**Issue by srmagura** [react-native-community/async-storage#452]
## Current behavior

The `getItem`, `setItem`, .etc methods from [async-storage-mock.js](https://github.com/react-native-community/async-storage/blob/master/jest/async-storage-mock.js) return `null` instead of a valid Promise object like the real `AsyncStorage`. As a result, any code that attempts to await the returned promises fails when the mock is swapped in.

## Expected behavior

`getItem`, `setItem`, .etc return promises.

## Repro steps

```
jest.mock('@react-native-community/async-storage')

it('returns promise', async () => {
     try {
         await expect(AsyncStorage.setItem('test', 'test')))
     } catch {
         assert.fail('Did not return a promise that resolves.')
     }
})
```

## Environment

- **Async Storage version**: 1.12.0
- **React-Native version**: N/A
- **Platform tested**: Node
- **Logs/Error that are relevant**: N/A

--------------------------

**Would you accept a PR for this issue?**

**Comment by Krizzu** [comment]
Hey @srmagura 

1. `async` function always returns Promise
2. That repro does not looks like a correct test, [here are the jest docs for async tests](https://jestjs.io/docs/en/asynchronous#promises)

**Comment by srmagura** [comment]
@Krizzu You are totally right. I took the time to write a proper test and it passed. It turns out I had made a mistake registering the mock in my main repo which led me to believe it wasn't returning promises. Sorry!

**Comment by Krizzu** [comment]
@srmagura No worries, glad you got it working
