### ISSUE TITLE
AsyncStorage not working as expected in iOS

### ISSUE THREAD

**Issue by txusillo** [react-native-community/async-storage#453]
## Current behavior

Whenever I logout and close the application on iOS, the AsyncStorage keys and values are gone. On Android everything is working fine.

## Expected behavior

When I close the application running on production or TestFlight in iOS, AsynStorage should persist. I use AsyncStorage for storing the files the user already downloaded in the device.

## Repro steps

Open the application, do some process that sets keys and values using AsyncStorage.setItem(key,value). Reopen the application and the keys and values are gone.

## Environment

- **Async Storage version**: 1.12.0
- **React-Native version**: 0.60.5
- **Platform tested**: iOS and Android. iOS has the problem.
- **Logs/Error that are relevant**: I don't have any logs.

**Comment by Krizzu** [comment]
Hey @txusillo 

We'd need more details, because there could be either bad implementation or something else. Did you try to run our Example app and see if you could reproduce?

**Comment by txusillo** [comment]
@Krizzu, sorry to bother you and thank you for your response. I've been trying to catch this bugs for weeks now. During this morning I found out that the version of aws-amplify was using another conflicting package with asyncstorage and that was causing the bug. I updated my version of aws-amplify, that also uses this package, and now AsyncStorage is working as expected on iOS.
