### ISSUE TITLE
react-native-web implementation of AsyncStorage

### ISSUE THREAD

**Issue by cohawk** [react-native-community/async-storage#52]
Should the react-native-web implementation of AsyncStorage also reside in this community library?

When changing to @react-native-community/async-storage the web version of my React Native app fails on `multiMerge`

I believe it would be a simple copy paste of the localStorage code here: https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/AsyncStorage/index.js

And it appears the react-native-web maintainers agree with the functionality residing in this library - https://github.com/necolas/react-native-web/issues/1260

Thank you.

**Comment by Krizzu** [comment]
Thanks @cohawk for pointing this out!

I'm moving [discussion over there](https://github.com/necolas/react-native-web/issues/1260), if you think it'd be nice to continue here, let me know.


thanks.

**Comment by necolas** [comment]
Please continue the discussion here and lift any code from RNW that is necessary.

**Comment by necolas** [comment]
@krizzu Please reopen this issue

**Comment by necolas** [comment]
This is the last commit in React Native for Web that will include `AsyncStorage` - https://github.com/necolas/react-native-web/tree/33dc3cb01869cde556387e1cbc4e43323015b5b7/packages/react-native-web/src/exports/AsyncStorage

**Comment by Krizzu** [comment]
Reopening the issue to continue to talk about making Web support first-class citizen in this repo. Currently working on implementing core of AS v2, and soon going to start on adding Storages.

**Comment by brunolemos** [comment]
I see the coding work on v2 has started but apparently became stale. So how should one proceed to add web support to this repo? Master branch? Legacy?

**Comment by Krizzu** [comment]
@brunolemos Once #186 is done, I think it'd be a good start to add web support.

**Comment by JesseRWeigel** [comment]
@Krizzu if you would like help with adding web support, please let me know. I use RNW with AsyncStorage and am holding off on upgrading.

**Comment by Krizzu** [comment]
I know it took some time but - I'm open for help with Web storage. If you're interested, please respond to this issue.

I've prepared a basic scaffold that work can be best on. Checkout to `master` branch and see `packages/storage-web` package.

Some todo list:
- Follow [instructions to create a storage backend](https://github.com/react-native-community/async-storage/blob/master/packages/core/docs/Writing_Storage_Backend.md)
- Make it compatible with both `localStorage` and `sessionStorage` (add an option to select one to use, when creating an instance of this storage)
- Add unit tests
- Update Readme

I'm going to help whoever takes this one. 
Thanks a lot in advance!

**Comment by JesseRWeigel** [comment]
I am interested. I will try and get started on it sometime this week.

**Comment by JesseRWeigel** [comment]
Hey @Krizzu ! I got localStorage and sessionStorage working. I wanted to let you take a look before I go any further. I didn't write any tests yet and I am not used to working with TypeScript, so I may not have done it correctly. Please let me know if I am on the right track when you get a chance! https://github.com/JesseRWeigel/async-storage/blob/web-storage/packages/storage-web/src/index.ts

**Comment by Krizzu** [comment]
@JesseRWeigel Great, please create PR so we can discuss it there

**Comment by jasonivers** [comment]
Is there any word on this moving forward?  I'd really like to be able to keep updated on react-native-web, but I currently cannot because it no longer supports AsyncStorage.  I'd love to be able to help, but unfortunately I don't have the time to give to this right now.

**Comment by Krizzu** [comment]
@jasonivers Hey,

Web supports already lives in [v2 of AsyncStorage](https://github.com/react-native-community/async-storage/tree/master/packages/storage-web). This is not the final version, as I'm [still working on some improvements.](https://github.com/react-native-community/async-storage/pull/284)

**Comment by kopax** [comment]
Hi, I am not able to upgrade to react-native-web 0.12.0 because of AsyncStorage support removed. I use it for native, on  the web I use the localStorage. How can I perform my upgrade without breaking native? Thanks!

**Comment by wong2** [comment]
For those upgrading to react-native-web 0.12.0 but blocked by this, here is my solution:

1. save the last version of AsyncStorage file to your project from https://unpkg.com/react-native-web@0.11.7/dist/exports/AsyncStorage/index.js
2. alias AsyncStorage import to your local file. I'm using webpack:
```
resolve: {
  alias: {
    'react-native$': 'react-native-web',
    '@react-native-community/async-storage': path.resolve(__dirname, './AsyncStorage.web.js'),
  },
  ...
}
```

**Comment by kopax** [comment]
I am afraid this won't work with expo because expo is using metro not webpack (If I am correct).

I use AsyncStorage in native and localStorage on the web =/

**Comment by awinograd** [comment]
That's not correct. Expo uses web pack for web builds. See the
@expo/webpack-config npm package

**Comment by wong2** [comment]
@kopax AsyncStorage from react-native-web **is** using localStorage underhood

**Comment by kopax** [comment]
> That's not correct. Expo uses web pack for web builds. See the @expo/webpack-config npm package

I am not concerned about the web but the natives ios and android application. Do they also use webpack in development? Isn't it metro supposed to build the react native application?

> @kopax AsyncStorage from react-native-web **is** using localStorage underhood, it just wraps it with the same api as native `AsyncStorage`

Glad to know and thanks, but I am concerned about the IOS/Android application.

**Comment by kopax** [comment]
@wong2, I have test to fix my issue using:

    config.resolve.alias['react-native-web/dist/exports/AsyncStorage'] = resolve(__dirname, './AsyncStorage.web.js');


I stil have this error:

    Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage' in '/home/dka/workspace/test-native/node_modules/expo/build/Notifications'

**Comment by wong2** [comment]
@kopax how do you import AsyncStorage in your code?

**Comment by kopax** [comment]
@wong2 it is not in my code, it is in expo source code:

https://github.com/expo/expo/blob/e65bceb325baf9a70ecea0cacfb117969134c89d/packages/expo/src/Notifications/Notifications.ts#L4

**Comment by wong2** [comment]
@kopax sorry I'm not sure how to do that with expo

**Comment by kopax** [comment]
Me neither, I guess I am stuck with react-native-web 0.11, too bad I was actively waiting for the `useNativeDriver` fix :(

**Comment by mrKorg** [comment]
What about not Expo projects? I have "NativeModule: AsyncStorage" error too.

"@react-native-community/async-storage": "^1.12.0",
"react-native-web": "^0.13.14"
