### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by jpolo** [react-native-community/async-storage#65]
## You want to:  

Hi !

Are react-native-community packages extracted from react-native core supporting officially flow ?

## Details:

There are some @flow annotation in sources but not all, and there is no flowconfig file in the npm package. This leads to a typing regression when using flow checker.

I've seen a great work about linking standardization by react-native-community, and I think it could be great if the same job was done for flow typing.

**Comment by jpolo** [comment]
That's why I would like to discuss "standard" before pushing any PR. If flow typing is not strictly enforced, it is not really useful and can be easily broken. Example : the `@flow` annotation is missing in `index.js`  which set the entire module to be typed as `any`.

We could enforce flow annotation using eslint plugin : https://github.com/gajus/eslint-plugin-flowtype#require-valid-file-annotation and include that in the eslint react-community config.

**Comment by Krizzu** [comment]
I believe "standards" are good as guidance, not strictly enforced rules. Some packages, like [react-native-webview](https://github.com/react-native-community/react-native-webview) moved fully to typescript. It's not always the case that everyone will use particular technology (in that case - flow).

I guess we can turn this eslint rule here, as it looks useful in this repo.

**Comment by Krizzu** [comment]
We're moving to TS in v2, with support Flow.
