### ISSUE TITLE
No podspec found issue

### ISSUE THREAD

**Issue by zmefz** [react-native-community/async-storage#78]
## You want to:  
Prevent issue for others.
Hopefully, it will help someone.

## Details:

In case of this issue:
```
[!] No podspec found for `react-native-async-storage` in `../node_modules/@react-native-community/async-storage`
```
Just check out [this](https://github.com/react-native-community/react-native-async-storage/commit/5ab6602ddd07b038450ce41d0937a7aeabdeccb7#diff-57c7b4305e459e93473e3c9ebdb80e5a) commit and at **Podfile** change line:
**Form**
```
pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'
```
**To**
```
pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
```

**Comment by lightman73** [comment]
To add to @zmefz comment, don't forget to update your pods after changing the pod name. 

Just in case, I would suggest to remove Podfile.lock, as well as the Pods folder, do a complete pod install from scratch, clean the build folder, and rebuild the project. This way, you are sure not to have any leftover reference to the wrongly named react-native-async-storage pod in your project.

**Comment by Krizzu** [comment]
Thanks @zmefz 	@lightman73 	

We've got a [Troubleshooting guide now, so we can reference this whenever common issues arise](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/Troubleshooting.md)

**Comment by gsteja2307** [comment]
thanks for the life saver <3

**Comment by aecorredor** [comment]
To anyone running into this issue with a monorepo, make sure you're not hoisting `@react-native-community/async-storage`

**Comment by Prabandha1** [comment]
Remove this live from the podfile 

pod 'react-native-async-storage', :path => '../node_modules/@react-native-community/async-storage'

then run  pod install
